### ISSUE TITLE
Null attributes

### ISSUE THREAD

**Issue by mchicote** [intercom/intercom-android#101]
Hi
I'm getting some strange behavior when I try to update a user's custom attribute with a null value. 
For example, if I go:

````
Map userMap = new HashMap<>();
Map customAttributes = new HashMap <>();
customAttributes.put("gender", user.getGender());
userMap.put("custom_attributes", customAttributes);
Intercom.client().updateUser(userMap);
````

If `user.getGender()` is null, the whole update fails. I know that I could check this myself but it would be much nicer if I did not had to. 

Btw, I think this also happens in the iOS SDK.

Thanks
Marcos

**Comment by mchicote** [comment]
I'm registering the user with email before this.

**Comment by harkin** [comment]
hi @mchicote 

I can't reproduce this, I'm able to update custom attributes while other custom attributes are null. What version of the library are you seeing this on and are you seeing any errors in logcat as it happens?

**Comment by mchicote** [comment]
Library version 1.0.0 (could this be the problem?)
I think the problem is on io/intercom/android/sdk/utilities/AttributeValidator.class:45 when called with the custom_attributes map. But I can't find the class in the repo anymore....sound like a version issue, right?

**Comment by mchicote** [comment]
btw, I'm seeing this on logcat

```
06-18 10:01:11.712    2023-2023/com.tobuy.android.stage E/Intercom-Android﹕ ERROR: The attribute null is not a number, string or boolean.
06-18 10:01:11.712    2023-2023/com.tobuy.android.stage E/Intercom-Android﹕ ERROR: updateUser method failed: the attributes Map provided contains invalid objects
```

**Comment by harkin** [comment]
@mchicote apologies for the delay in getting back to you on this. Yeah this looks like a versioning issue. We did do some client side validation in that version but we've removed it in more recent versions because really the client shouldn't be doing validation like that, especially when what the server accepts can change.

**Comment by mchicote** [comment]
Great! Thanks!
