### ISSUE TITLE
Font assets clashing

### ISSUE THREAD

**Issue by hvisser** [intercom/intercom-android#103]
In our app we bundle the Roboto fonts in the assets directory, e.g. `assets/fonts/roboto-medium.ttf`. Apparently the Intercom SDK is doing the same with different casing (OS X doesn't mind). The app will build fine, but crash at runtime because of this. It might be better to package the intercom fonts in a more unique location to prevent clashing with application resources.

**Comment by harkin** [comment]
You're spot on there, we'll namespace the fonts and I'll make sure there aren't any other resources that might cause a clash

**Comment by hvisser** [comment]
Great, thanks!

**Comment by harkin** [comment]
v1.1.2 was just released and has namespaced fonts, I also caught some assets in raw that weren't namespaced (but those weren't likely to cause a clash anyway). Let me know if you come across anything else that causes an issue like this and we can fix it
