### ISSUE TITLE
MainActivity leaked

### ISSUE THREAD

**Issue by ntoskrnl** [intercom/intercom-android#104]
I use LeakCanary in my app to detect memory leaks.

Every time I close my application, LeakCanary reports a leak of `io.intercom.android.sdk.activities.MainActivity`

![screenshot_2015-07-06-13-16-57](https://cloud.githubusercontent.com/assets/1446492/8520566/fe9ff1cc-23e3-11e5-93d0-e3857bd79c9c.png)

![screenshot_2015-07-06-13-17-00](https://cloud.githubusercontent.com/assets/1446492/8520569/05677c14-23e4-11e5-8615-5ecbdc636474.png)

**Comment by harkin** [comment]
:( looking into what's going on here

**Comment by harkin** [comment]
The event bus we use is holding onto references to something in a list that it shouldn't be once you close a conversation.

**Comment by harkin** [comment]
I believe this is fixed; the list that was holding onto a reference is no longer doing so. That fix is in v1.1.2

Going to close this as I can't detect this now, but let me know if you see this again and I'll be on it's case :+1:

**Comment by ntoskrnl** [comment]
Well done! :+1:
