### ISSUE TITLE
Illegal argument exception in unread conversations api call, missing callback

### ISSUE THREAD

**Issue by gennadiiivanov** [intercom/intercom-android#106]
```
java.lang.IllegalArgumentException: IntercomApiInterface.getUnreadConversations: Must have either a return type or Callback as last argument.
       at retrofit.RestMethodInfo.methodError(RestMethodInfo.java:107)
       at retrofit.RestMethodInfo.parseResponseType(RestMethodInfo.java:270)
       at retrofit.RestMethodInfo.<init>(RestMethodInfo.java:97)
       at retrofit.RestAdapter.getMethodInfo(RestAdapter.java:213)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:236)
       at java.lang.reflect.Proxy.invoke(Proxy.java:397)
       at $Proxy0.getUnreadConversations()
       at io.intercom.android.sdk.api.Api.getUnreadConversations(Api.java:375)
       at io.intercom.android.sdk.api.PollingManager$1.run(PollingManager.java:30)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5834)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

Happened in 1.1.1 version.

**Comment by harkin** [comment]
That's a strange crash, a callback is passed in as the last argument to that method. How often are you seeing this crash? It should be on every launch if there was a problem.

**Comment by gennadiiivanov** [comment]
> That's a strange crash, a callback is passed in as the last argument to that method. How often are you seeing this happen? It should be on every launch of your app if there is a problem.

It happens very rarely. But still, this is a crash that we have inside your library.


> Are you including version 1.9.0 of retrofit in your project?

We are not using retrofit in our project.

**Comment by harkin** [comment]
Of course. Unfortunately I can't reproduce the crash. Do you have any more information about when it happens or under what circumstances it crashes?

Are you including the transitive dependencies of our library so? I just want to make sure it's not a version problem

**Comment by gennadiiivanov** [comment]
> Of course. Unfortunately I can't reproduce the crash. Do you have any more information about when it happens or under what circumstances it crashes?

We have no any additional information.



> Are you including the transitive dependencies of our library so? I just want to make sure it's not a version problem

Yes, we do

```
  compile ('io.intercom.android:intercom-sdk:1.1.1@aar') {
    // Please note that the same libraries from this build file and libraries from Intercom described in the following
    // section https://github.com/intercom/intercom-android#remote-dependencies should have the same version to avoid
    // crashes and unexpected behaviour.
    transitive = true
  }
```

**Comment by harkin** [comment]
Do you know what device(s) or what versions of android this crash happened on? 

The obvious reason this might crash is if a callback wasn't passed into that method. If that were the case everyone would see the crash and it would happen very often, which isn't the case here it seems. I haven't been able to reproduce this so now I'm wondering under what circumstances it could happen.

Do you see any Out Of Memory errors in your app? Is your app multidexed and/or is it near the 65k method limit?

**Comment by gennadiiivanov** [comment]
> Do you know what device(s) or what versions of android this crash happened on?
> 
> The obvious reason this might crash is if a callback wasn't passed into that method. If that were the case everyone would see the crash and it would happen very often, which isn't the case here it seems. I haven't been able to reproduce this so now I'm wondering under what circumstances it could happen.
> 
> Do you see any Out Of Memory errors in your app? Is your app multidexed and/or is it near the 65k method limit?

@harkin it happened only on Samsung devices, Android 5:
84% - SM G900M
16% - SM G900F

Looks like the crash happened in Out Of Memory circumstances because crash reporting system shows 98% RAM used on these devices.

Our app is multidexed.

**Comment by harkin** [comment]
I was hoping it'd be one or the other to narrow things down. I know with some versions of the gradle build tools there are multidex issues where classes either aren't included or are in some way removed from the classpath. That manifested in no class def found exceptions but I think it's worth checking here. The version we saw errors with was gradle build tools 1.0.1, are you by chance using that version?

I think for now it's reasonable to assume that this error is in some way related to running out of memory, it would be very coincidental to get an unusual crash and have 98% RAM usage with the two unrelated. Having said that, this crash is atypical of OOM errors that I've seen.

We profile our library to ensure it never gets memory hungry in unreasonable circumstances. From the stack trace it appears that none of the UI elements of the library were visible/inflated so it would have a very low memory footprint. 

It's a little unusual that this has only occurred on variations of the Samsung Galaxy S5, are the majority of your users on an S5 or do you have a more even distribution? If the latter it would indicate that there's something unique about the S5 that causes this to happen. 

I don't have any solid theories on why this is happening. My hunch is that there is a memory leak somewhere in your app, be it our library, something in your codebase or one of your other dependencies.  I'm going to spend some time profiling our library on an S5 and I'll update this with anything I find. If you could do some similar profiling in your app when it's nearing those extreme usage circumstances it would give us more insight into where the memory is being used, a heap dump when it's in that state would be amazing.

**Comment by gennadiiivanov** [comment]
> The version we saw errors with was gradle build tools 1.0.1, are you by chance using that version?

We are using build tools 1.1.0



> I think for now it's reasonable to assume that this error is in some way related to running out of memory, it would be very coincidental to get an unusual crash and have 98% RAM usage with the two unrelated. Having said that, this crash is atypical of OOM errors that I've seen.

I agree with this




> It's a little unusual that this has only occurred on variations of the Samsung Galaxy S5, are the majority of your users on an S5 or do you have a more even distribution? If the latter it would indicate that there's something unique about the S5 that causes this to happen.

It happens only on Samsung Android 5 as I mentioned earlier



> I don't have any solid theories on why this is happening. My hunch is that there is a memory leak that is exacerbated, or perhaps only present, on an S5 somewhere in your app, be it our library, something in your codebase or one of your other dependencies. I'm going to spend some time profiling our library on an S5 and I'll update this with anything I find. If you could do some similar profiling in your app when it's nearing those extreme usage circumstances it would give us more insight into where the memory is being used, a heap dump when it's in that state would be amazing.

Ok, we will try to profile and find the circumstances as well. The problem is that we cannot reproduce the crash on our in house devices.

**Comment by harkin** [comment]
@gennadiiivanov I've spent some time profiling the library on our Samsung S5. I haven't come across any memory leaks or  situations where we're holding onto an unreasonable amount of memory over a long period of time etc. Have you found anything?

**Comment by gennadiiivanov** [comment]
> @gennadiiivanov I've spent some time profiling the library on our Samsung S5. I haven't come across any memory leaks or situations where we're holding onto an unreasonable amount of memory over a long period of time etc. Have you found anything?

@harkin we didn't have a time to work on this problem yet. Can you just put a simple try/catch into your code?
It is interesting that crash is happening only on Android 5. Maybe the library (retrofit) update will solve a problem?

**Comment by harkin** [comment]
Update this issue when you do and we can work from there to find a solution.

I'd rather not drop try/catch blocks around without understanding the cause of the problem. It's a bandaid, not a fix to the problem. I'd wager a new crash would show up somewhere else almost immediately. 

Retrofit is a java library, it doesn't have any reliance on android. I'd be very willing to believe that there's something unusual in the version of Lollipop running on Samsung S5s though.

**Comment by gennadiiivanov** [comment]
> I'd be very willing to believe that there's something unusual in the version of Lollipop running on Samsung S5s though.

I am pretty sure it happens because of it. We have around 35% of Android 5 users and it happens only for them.
My question is: why it happens only inside this call stack.
Looks like you are trying to parse memory heavy response from API, right? In this case it makes sense to have an exception catch since you don't know how OutOfMemory exception is handled inside the third-party library (retrofit).

**Comment by harkin** [comment]
The response is in most cases quite small, typically under 2kb (your milage may very depending on how many messages you send through Intercom and how often your users read them).

I don't know much about the innards of Retrofit but here's what I'm seeing when I look through the source. Retrofit throws an [IllegalStateException here](https://github.com/square/retrofit/blob/2f4caa6f5df8e7f47a881266bbfc723f537b0b47/retrofit/src/main/java/retrofit/RestMethodInfo.java#L270) if the method signature for the call is incorrect, i.e. if it either doesn't take a callback or it doesn't return something. I can't say this with 100% confidence (being unfamiliar with the library) but I believe that is checked before any network activity is initiated. Obviously the method signature is correct or it would crash in 100% of cases. 

When you say it only happens for Android 5.0 users, is this still exclusively on Samsung S5 devices? It feels like an overly aggressive garbage collector is collecting something it shouldn't be because the device is so low on memory.

I don't think the solution is to find what that thing is and catch an exception, I think the solution is to figure out why the device is so low on memory.

**Comment by gennadiiivanov** [comment]
> When you say it only happens for Android 5.0 users, is this still exclusively on Samsung S5 devices? It feels like an overly aggressive garbage collector is collecting something it shouldn't be because the device is so low on memory.

Yes, it happens exclusively on Samsung S5. And feels like this.



> I don't think the solution is to find what that thing is and catch an exception, I think the solution is to figure out why the device is so low on memory.

It is a standard situation. It happens when device performs a lot of image or video processing operations (especially in background). The solution is to correctly handle this case. We handle this in the app by listening specific `onLowMemory` application call back and all the `OutOfMemory` exceptions and clearing the memory in this case. I think this is a correct and only the one way how we need to handle this.

**Comment by gennadiiivanov** [comment]
@harkin we did a memory profiling and couldn't find anything abnormal in the app. There are some memory spikes in the app but this is an expected behavior and we correctly handle this case. I think we should let client apps take care about these cases and assume that memory is managed correctly inside the Intercom library.

**Comment by harkin** [comment]
I've made some tweaks to ensure our memory footprint stays as low as possible and we're running tests and QA at the moment and we'll be releasing a new version once we're happy with it. None of these changes are going to help if an app is using 98+% of the available memory though. In those extraordinary circumstances something is going to break.

**Comment by harkin** [comment]
v1.1.3 is up now
