### ISSUE TITLE
New message does not appear after closing conversation activity

### ISSUE THREAD

**Issue by behzodbek** [intercom/intercom-android#109]
1. Open new message by clicking  PreviewView;
2. Read all unread messages
3. Close ConversationActivity
4. Send new message to app.
If app is on background, than arise PN and user will be notify about new message, Unless PreviewView does notify about new message. Is it bug?

**Comment by tylergo** [comment]
@behzodbek please add photos

**Comment by harkin** [comment]
@behzodbek Are you on a plan that supports real time message delivery?

**Comment by behzodbek** [comment]
https://www.dropbox.com/s/4jikksr8p871g27/device-2015-07-21-002318.mp4?dl=0
1. Send message to user though Intercom.
2. Open App and click PhotoView - open conversation. 
3. Close it. 
4. Send new message through the Intercom. There is not any update on App screen. Any notification about new message. The PhotoView does not appearing.
5. Reopen app again. PhotoView tells that there is a new message 2

**Comment by harkin** [comment]
@behzodbek Learn Pro and Support Pro are the two packages in Intercom that include real time messaging. You need to be on one of those packages to get instant message delivery in app.

We're currently working on achieving a better delivery time for anyone using this library that isn't on a package that has real time messaging

**Comment by harkin** [comment]
v1.1.3 is live and will improve this for you
