### ISSUE TITLE
Custom TaskStackBuilder for Notification

### ISSUE THREAD

**Issue by behzodbek** [intercom/intercom-android#110]
Pelase add opportunity adding custom TaskStackBuilder for Notification. 
Now in my app start point of app is Splash Activity. It checks some data and may open MainActivity in 3 seconds. 
Intercom.client().openGCMMessage call does not work if I add into MainActivity. If I add Intercom.client().openGCMMessage(Uri uri) call into SplashActivity by clicking notification it opens SplashActivity and top of SplashActivity openes Intercom ConversationActivity. There is a timer which openes Main activity and finishes SplashActivity. Overall there is MainActivity on top of ConversationActivity. I want to set my custom TaskStack for Intercom Notification.

**Comment by tylergo** [comment]
@behzodbek please add pictures with descriptions

**Comment by DaleCantwell** [comment]
@behzodbek thanks for the feedback. We are always looking for ways to improve our GCM capabilities. A TaskStackBuilder could be very useful for many situations so I will add to our list of GCM featur requests. We won't be able to work on it right away but I will update this thread as soon as we look into it.
In the meantime would it be possible in your integration to add the SplashActivity intent data to your MainActivity so that you can call openGCMMessage in MainActivity?

**Comment by behzodbek** [comment]
@DaleCantwell could you clarify please? 
Do you mean like that?
SplashActivity.java
...
Uri uri = getIntent().getData();
Intent intent = new Intent(this, MainActivity.class);
intent.setData(uri);
startActivity(intent);
...

MainActivity.java
...
 Intercom.client().openGCMMessage(getIntent().getData());
...
I think it useless. It is no matter where we register it. There is same url.

If you meant another approach please could you clarify it?

**Comment by DaleCantwell** [comment]
@behzodbek I have tested this successfully here. If on your splash screen calling Intercom.client().openGCMMessage(getIntent().getData()) works but draws intercom over your splashscreen. Somewhere in your code you will make an intent to move from your splashscreen to your mainactivity. I would debug that intent to make sure that setting the intent data has worked there. 
If it has then we know that openGCM will work on the next screen. 
Could you debug this further and see where the uri gets lost or if there are any logs stating what happened when you called openGCMMessage?
Thanks
Dale

**Comment by DaleCantwell** [comment]
Fixed in v1.1.5 using new method openGCMMessage(Intent, TaskStackBuilder);
