### ISSUE TITLE
Custom Chat GUI

### ISSUE THREAD

**Issue by fschramm001** [intercom/intercom-android#111]
Hi,

is it possible to handle the intercom chat in a custom gui? We want to style the intercom chat like facebook messenger.

Cheers,
Flo

**Comment by adamkmccarthy** [comment]
Hi @fschramm001. Unfortunately we don't offer the flexibility to style the UI in the manner you're looking for at the moment. We may look into this in the future though, if we do you'll hear about it here first. Thanks!

**Comment by fschramm001** [comment]
Hi, thanks for your fast reply. Just publish your sdk ;-)
