### ISSUE TITLE
Control SDK logging

### ISSUE THREAD

**Issue by hvisser** [intercom/intercom-android#112]
The SDK outputs a lot of logging which is useful during development, but not in a release build. I'd prefer it if the Intercom SDK would use the standard method of controlling log out put using `adb setprop log.tag.Intercom-Android VERBOSE` and to have some mechanism to turn of all SDK logging on release builds.

**Comment by harkin** [comment]
Yes! This is on our roadmap but isn't something we'll be working on in the immediate future. I'll update this issue once we have a better idea of when it'll happen.

**Comment by DaleCantwell** [comment]
Added in v1.1.5 using method Intercom.setLogLevel(IntercomLogger.VERBOSE); Other IntercomLogger levels are
    VERBOSE
    DEBUG
    INFO
    WARN
    ERROR
    ASSERT
    DISABLED
Default level is WARN
