### ISSUE TITLE
Android M permission for android.permission.SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by mbernier85** [intercom/intercom-android#116]
I don't know when you plan on testing Android M, but we wanted to test it on our app, but it seems like your Lib is asking for a permission, which I added in the AndroidManifest

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission-sdk-m android:name="android.permission.SYSTEM_ALERT_WINDOW" />

For some reason, it's still not working. Here is the crash

```
Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@e0acddb -- permission denied for this window type
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:596)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
            at io.intercom.android.sdk.preview.PreviewService.init(PreviewService.java:206)
            at io.intercom.android.sdk.preview.PreviewService.onCreate(PreviewService.java:123)

```

**Comment by harkin** [comment]
Weird, that is the permission we ask for. We'll be testing M soon, I'll update this issue when we know more about why it doesn't work

**Comment by condesales** [comment]
Any news about this one?
I'll have to drop Intercom integration from my app for now in order to support android M..

**Comment by mbernier85** [comment]
Android 6.0 was officially launched with the SDK, do you have an estimated time when this will be fixed ?

**Comment by mbernier85** [comment]
Just tried android 6.0 SDK with Android preview 3, still the same issue

I think you might need to add Permission check for it to work correctly.

**Comment by condesales** [comment]
Well, thats a problem @mbernier85 since I don't use Intercom to create system alert windows.
I don't want to ask the user for a permission that the app will never user, makes no sense.

**Comment by mbernier85** [comment]
I didn't mean to say this to you, but the creator of Intercom SDK.

I don't use this feature too, and yet I still need the permission. They need to work on the way to initialize the Lib.

**Comment by DaleCantwell** [comment]
@mbernier85 @condesales Thanks for feedback and for checking out the SDK with M. We will have a fully working Android Integration with M before it is released. Currently though as M is in preview we need to fully look into what changes we will need to make and what effects the new features will have on the SDK. Once we are satisfied that we are totally stable with M we will release an update. I understand that this can be frustrating for early adopters of M but unfortunately with an SDK we can't jump on board right away.
I am looking into fixing the new permissions today. Regarding the permission for the System Window, we require that to draw our chathead preview over the host app. That will not be changing in this update. If enabling the permission is not an option in your integration I would suggest looking at our public API (https://doc.intercom.io/api/). It will allow you to do all of the event logging with no visuals (thus no permissions). The main downside is that you won't be able to log Android device data.
I will update this thread as we progress with our M investigation.

**Comment by harkin** [comment]
Quick update: I'm investigating this

The short of it is that the permission we request, `android.permission.SYSTEM_ALERT_WINDOW`, cannot be asked for programatically in Marshmallow and instead the user has to enable it in some settings menu. We're looking into alternative strategies

**Comment by condesales** [comment]
@harkin what do you mean by  
> cannot be asked for programatically in Marshmallow
?

The only way I can see this working is the library checking the permissions and catching the exceptions android might throw. 
Also under Intercom docs you need to add a section about it, telling the developers that in order to X feature to work they need to request Y permission using the new permission SDK 

¯\_(ツ)_/¯

**Comment by harkin** [comment]
@condesales I mean that if you try to request that permission by doing
`requestPermissions(new String[]{Manifest.permission.SYSTEM_ALERT_WINDOW}, 1234);` 
then the user isn't even shown a dialog, instead `onRequestPermissionResult` is called with whatever the value of the toggle in settings is for that app.

We are going to check for permissions in the library where appropriate. The issue here for us is that with the change to system windows we're going to lose some functionality in the library unless the user goes off and flips a toggle buried somewhere in the settings menu and we don't consider that an acceptable requirement to put on anyone who wants to use the library. So we're looking for alternative ways to implement some functionality.

I'm not sure that any of this will need to be exposed to the developer once it's complete. The library will be able to manage requesting permissions and dealing with grants and denies.

**Comment by harkin** [comment]
I've updated the library and fixed this issue and another permissions related crash for attachments. We're starting a QA run for the library on Marshmallow to make sure there aren't any surprises. If that goes well we'll release the next version

**Comment by hvisser** [comment]
What is the status of this bug? We are prepping our app for the M launch and this issue is blocking us.

**Comment by harkin** [comment]
@hvisser @mbernier85 @condesales thanks for your patience with this

We have a release candidate ready now that addresses these marshmallow issues. If you could get in contact with us at team@intercom.io we can get you set up with it

**Comment by harkin** [comment]
We've released 1.1.4 with support for M

**Comment by condesales** [comment]
Thank you guys!

**Comment by mderazon** [comment]
We're migrating our app to 6.0 now as well. Can you please update what permissions / permissions groups are necessary / optional for intercom sdk ?
is `SYSTEM_ALERT_WINDOW` still necessary ?

**Comment by harkin** [comment]
@mderazon `INTERNET`, `READ_EXTNERAL_STORAGE`, `MANAGE_DOCUMENTS` and `SYSTEM_ALERT_WINDOW` are the 4 essentials that we have in our manifest for the base module, nothing optional there. For the gcm module `WAKE_LOCK`, `...c2dm...RECEIVE`  and `VIBRATE` are the 3 essentials we put in the manifest and the two optional ones here are `ACCESS_NETWORK_STATE` and `READ_PHONE_STATE` that we'll use if you request them or do different things if we don't have those permissions.

I'm currently working on an update that will remove the need for  `SYSTEM_ALERT_WINDOW`, it'll be ready soon

**Comment by gupta-sachin** [comment]
Is there any expected date for library without SYSTEM_ALERT_WINDOW. Why the issue is not re-opened?

**Comment by harkin** [comment]
@gupta-sachin This issue was fixed 30 odd days ago, the latest version of the library is fully compatible with Marshmallow.  The update I'm working on isn't directly related; we've wanted to remove the system window permission for a long time. No hard dates I'm afraid, I'd expect it within the week

**Comment by gupta-sachin** [comment]
I am using a marshmallow device, and if I revoke this permission from settings, app is crashing even with latest version of library.

**Comment by harkin** [comment]
@gupta-sachin that sounds weird, I don't think it's related to this issue. Can you open a new issue for this with all the details?

**Comment by harkin** [comment]
version 1.1.8 is out now and doesn't use the system alert permission

**Comment by khuranakaran** [comment]
@harkin how did u resolve this issue?

**Comment by harkin** [comment]
@khuranakaran the long term plan to fix this issue was a large enough refactor so that we didn't need the systems alert window permissions. No permission no problem!

The short term solution we went with was to change the window layer we were drawing to if we didn't have that permission (ie on Marshmallow devices). Off the top of my head I can't remember which layer we moved to, there were a few prospective ones. Toast maybe

**Comment by creativepaddy** [comment]
WHY MY APP STILL CRASHES.. I DONT UNDERSTAND WHY THE PERMISSION THING GONE AWAY.. IF THERE IS SOME IMPROVEMENTS, THEN WHY I CANT SEEN

HERE IS MY CRASH REPORT ERROR ATTACHED WITH THIS COPY..
PLEASE DO SOMETHING..

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.digitaldietapps.bluelightfilter.nightshift, PID: 3759
                  java.lang.RuntimeException: Unable to create service com.digitaldietapps.bluelightfilter.nightshift.filterServiceNight: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3c8afb8 -- permission denied for this window type
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                      at android.app.ActivityThread.-wrap4(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3c8afb8 -- permission denied for this window type
                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                      at com.digitaldietapps.bluelightfilter.nightshift.filterServiceNight.onCreate(filterServiceNight.java:88)
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                      at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ronocod** [comment]
@creativepaddy it looks like your issue is related to your code, not Intercom code.

**Comment by sourav8256** [comment]
@creativepaddy are you using proguard? try disabling that!
