### ISSUE TITLE
API failed error

### ISSUE THREAD

**Issue by anshul90** [intercom/intercom-android#117]
Hi, 

I'm using intercom in 2 different projects. One project is even live and it doesn't have any problem. But another project has so many problems if I implement anything I always get error in my logcat of API FAILED ERROR.

Can you please tell me why I'm getting this?

Thanks.
Anshul Tyagi

**Comment by harkin** [comment]
We try to print out whatever response we get from our servers detailing why a call to our API might have failed. If you aren't seeing any additional information in logcat then that typically means that there is an issue connecting to the server.

Are you using any kind of proxy to intercept traffic on that device?

**Comment by anshul90** [comment]
Yes, I have implemented Twilio service in my app to get incoming fby using background service. I don't have any problem with Twilio service. It works fine if I don't integrate intercom in my project. As I integrate it, my logcat starts giving me error of intercom API failed and

pjsua_acc.c ....SIP registration failed, status=302 (Moved Temporarily)
 pjsua_acc.c .....Unable to create/send REGISTER: Object is busy (PJSIP_EBUSY) [status=171001]

Thanks,
Anshul Tyagi

**Comment by harkin** [comment]
I'm not terribly familiar with the Twilio SDK; does Intercom work correctly when you aren't depending on Twilio?

**Comment by anshul90** [comment]
Actually, it doesn't. I cannot send sms via SMS. Is it any facility you provide?

**Comment by harkin** [comment]
No, Intercom doesn't doesn't have any feature like that or that would interfere with that

**Comment by anshul90** [comment]
Can you please tell me the issue of API failed btw?

**Comment by harkin** [comment]
The issue there is that network requests from the Intercom library aren't getting to our server. This could be because of a poor internet connection, lack of internet connection, some intermediary proxy etc. I'd suggest creating a new app and just following the [installation guide](http://docs.intercom.io/Install-on-your-mobile-product/installing-intercom-for-android) to see if it works there, or run one of the sample apps in this repo to confirm that

**Comment by anshul90** [comment]
ok thanks Harkin.

**Comment by harkin** [comment]
@anshul90 follow up here we were talking through Intercom too, did you get this sorted?

**Comment by anshul90** [comment]
Yea @harkin , I sorted out that. The problem was in the targetSDKVersion of Manifest.xml.

**Comment by harkin** [comment]
ah, that's great to know incase we see this again, thanks!
