### ISSUE TITLE
Suggestion on signature of Intercom.client().logEvent

### ISSUE THREAD

**Issue by hy9be** [intercom/intercom-android#121]
Hi,
I suggest to change the signature from 
``Intercom.client().logEvent(String tag, Map<String, Object> eventData)``
to
``Intercom.client().logEvent(String tag, Map<String, ?> eventData)``

So that the api can be integrated with any existing logging api (wrapped by a single method). For example, if some logging api need ``Map<String, String>`` as parameter, current signature creates big problem, because we cannot cast ``Map<String, String>`` to ``Map<String, Object>``. If Intercom changes ``Object`` to ``?``, problem solved.

**Comment by DaleCantwell** [comment]
Hi @hy9be 
Thanks for the feedback. We will look into this. I can see the use cases for it but we'll need to make sure we protect against any types that won't work with the API. I will let you know where we go with this. In the meantime to not hold up your development could you add your map to a Map<String, Object>. There are a few ways to do this, below is a very basic example.

```JAVA
        Map<String, String> stringMap = new HashMap<>();
        Map<String, Object> intercomMap = new HashMap<>();

        stringMap.put("a","1");
        stringMap.put("b","2");

        intercomMap.putAll(stringMap);
```

**Comment by hy9be** [comment]
@DaleCantwell 
Thanks for the reply. I will try the way you showed.

**Comment by harkin** [comment]
We changed this in the latest version :+1:

**Comment by hy9be** [comment]
Thanks a lot!
