### ISSUE TITLE
Nullpointer Exception in CallbackHolder

### ISSUE THREAD

**Issue by renard314** [intercom/intercom-android#122]
Link to Crashlytics report
http://crashes.to/s/dfbeff86706

**Comment by harkin** [comment]
What's happening here is that the response object generated from a successful (200) network request is (unexpectedly) null. I'll look into why this is happening; it could potentially be a problem with some backend code but I'm not confident that it is. It's curious that this has happened exclusively on rooted phones.

**Comment by gennadiiivanov** [comment]
@harkin I have the same in 1.1.3 version: http://crashes.to/s/ebac0fb90b2 . This is the top crash that we have in the app.

**Comment by harkin** [comment]
98% of those devices are rooted too. It's hard to imagine that being a coincidence. 

@renard314 @gennadiiivanov  have either of you seen this been able to reproduce this yourself or could you contact a user that has been affected by this crash? Assuming that all these phones being rooted is relevant then the two things that spring to mind to me are a custom OS having some funky behaviour or, more likely, an Xposed module interfering. Narrowing down what OS and/or what Xposed modules are at play here would speed up finding a fix dramatically.

**Comment by renard314** [comment]
I have not been able to reproduce and the crash unfortunately.

**Comment by gennadiiivanov** [comment]
@harkin I haven't been able to reproduce it as well.

**Comment by renard314** [comment]
another occurrence in 1.1.3. This time the phone is not rooted
http://crashes.to/s/5db406e914d

**Comment by renard314** [comment]
Another crash that might be related. This one is in LightBoxActivity
http://crashes.to/s/ddc4ceb8f9e

**Comment by gennadiiivanov** [comment]
@harkin what is the status of this issue? When do you plan to fix and release it?

**Comment by harkin** [comment]
I'm thoroughly confused about how a device being rooted makes it *much* more likely to encounter this and somewhat concerned about that but I can't find any answers there.

@renard314 that crash you saw in the LightBoxActivity came from someone running your app on the 'Full Android On Emulator'. I've seen this before and suspect someone launched the LightBoxActivity directly and didn't navigate to it through the normal flow (tapping on an image). As such it was in a weird state and this can't happen in the real world. 

Most of my time has been taken up working on Marshmallow related issues. I'll be working on a fix for this tomorrow. We aren't going to release another version of the library that doesn't work on Marshmallow so this fix will be released once we're happy with our performance and correctness on M

**Comment by harkin** [comment]
We're checking for these nulls in the latest version :+1:
