### ISSUE TITLE
Call Of Intercom.initialize(...) method on Android crash

### ISSUE THREAD

**Issue by timemarkov** [intercom/intercom-android#129]
I need help with initialize of Intercom on Android platform. I have Android C++ Qt\QML application and want to use your service. I include intercom-sdk-base-classes.jar in my project and when call method  Intercom.initialize(...) the application crash. Can you provide to me jars which I need to put in my project (dependency for intercom-sdk-base-classes.jar).

**Comment by harkin** [comment]
I'm not familiar with that kind of setup for an Android app.

If you can specify dependencies using gradle or maven that's the ideal situation where it's easy for you to update them. 

Next best is if you can include a `.aar` dependency. It's not ideal but not a great deal of effort.

If your only option is using `.jars` then it's more involved

@timemarkov let me know how you can include dependencies and I'll walk you through getting Intercom set up

**Comment by timemarkov** [comment]
I need only to put jars from which depends  intercom-sdk-base-classes.jar  in one libs folder. That is all I need to do. Only I need the jars if you have or give me link from where I can download

**Comment by harkin** [comment]
In that case you can find the jars you need here: https://github.com/intercom/intercom-android/tree/master/jar/intercom-sdk-base/libs

I'd suggest taking both and removing the one you currently use. We've made some changes to how we package dependencies recently so you'll want the base-classes jar that matches the packaged dependencies.

If you're planning to target Android Marshmallow with your app then you'll want to check back in a few days and update the jars you use; there are a few bugs in the current version with regard to permissions that I'm in the process of fixing

**Comment by timemarkov** [comment]
I put that jar in libs folder but application still crash. Does that jar is only dependency?

**Comment by harkin** [comment]
Yes that jar is the only dependency you'll need. Do you have a stacktrace of the crash?

**Comment by timemarkov** [comment]
@harkin Here is trace:

W/Qt A11Y ( 9255): Could not activate platform accessibility.
D/AndroidRuntime( 9255): Shutting down VM
W/dalvikvm( 9255): threadid=1: thread exiting with uncaught exception (group=0x41765e48)
E/AndroidRuntime( 9255): FATAL EXCEPTION: main
E/AndroidRuntime( 9255): Process: com.groupsinc.android.cincofit, PID: 9255
E/AndroidRuntime( 9255): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.groupsinc.android.cincofit/com.groupsinc.MainActivity}: java.lang.IllegalArgumentException: Component class io.intercom.android.sdk.preview.PreviewService does not exist in com.groupsinc.android.cincofit
E/AndroidRuntime( 9255):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2202)
E/AndroidRuntime( 9255):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
E/AndroidRuntime( 9255):  at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/AndroidRuntime( 9255):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
E/AndroidRuntime( 9255):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9255):  at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 9255):  at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 9255):  at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9255):  at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 9255):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime( 9255):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
E/AndroidRuntime( 9255):  at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 9255): Caused by: java.lang.IllegalArgumentException: Component class io.intercom.android.sdk.preview.PreviewService does not exist in com.groupsinc.android.cincofit
E/AndroidRuntime( 9255):  at android.os.Parcel.readException(Parcel.java:1469)
E/AndroidRuntime( 9255):  at android.os.Parcel.readException(Parcel.java:1419)
E/AndroidRuntime( 9255):  at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:2943)
E/AndroidRuntime( 9255):  at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:1288)
E/AndroidRuntime( 9255):  at io.intercom.android.sdk.Intercom.changeComponentState(Intercom.java:295)
E/AndroidRuntime( 9255):  at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:54)
E/AndroidRuntime( 9255):  at io.intercom.android.sdk.Intercom.initialize(Intercom.java:45)
E/AndroidRuntime( 9255):  at com.groupsinc.MainActivity.onCreate(MainActivity.java:70)
E/AndroidRuntime( 9255):  at android.app.Activity.performCreate(Activity.java:5275)
E/AndroidRuntime( 9255):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 9255):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
E/AndroidRuntime( 9255):  ... 11 more

"com.groupsinc.android.cincofit" died.

**Comment by harkin** [comment]
I'm pretty sure it does exist, it's in the same jar as Intercom so if you're calling initialize it should be there.

Is there some kind of [manifest merger](http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger) in your toolchain? I've a hunch that the service isn't being correctly added to your `AndroidManifest.xml` file. 

The things that should end up in your manifest can be found [here](https://github.com/intercom/intercom-android/blob/master/jar/intercom-sdk-base/AndroidManifest.xml). A simple test to see if this is it would be to manually copy them over

**Comment by timemarkov** [comment]
@harkin I have update as you suggest. Now still have crash with follow logs:

W/dalvikvm(12694): threadid=1: thread exiting with uncaught exception (group=0x41765e48)
E/AndroidRuntime(12694): FATAL EXCEPTION: main
E/AndroidRuntime(12694): Process: com.groupsinc.android.macfitomur, PID: 12694
E/AndroidRuntime(12694): java.lang.NoClassDefFoundError: io.intercom.android.sdk.R$color
E/AndroidRuntime(12694):  at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:64)
E/AndroidRuntime(12694):  at io.intercom.android.sdk.identity.AppIdentity.<init>(AppIdentity.java:28)
E/AndroidRuntime(12694):  at io.intercom.android.sdk.identity.IdentityStore.<init>(IdentityStore.java:19)
E/AndroidRuntime(12694):  at io.intercom.android.sdk.Bridge.<init>(Bridge.java:32)
E/AndroidRuntime(12694):  at io.intercom.android.sdk.Bridge.init(Bridge.java:41)
E/AndroidRuntime(12694):  at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:55)
E/AndroidRuntime(12694):  at io.intercom.android.sdk.Intercom.initialize(Intercom.java:45)
E/AndroidRuntime(12694):  at com.groupsinc.MainActivity.onCreate(MainActivity.java:70)
E/AndroidRuntime(12694):  at android.app.Activity.performCreate(Activity.java:5275)
E/AndroidRuntime(12694):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(12694):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
E/AndroidRuntime(12694):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
E/AndroidRuntime(12694):  at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/AndroidRuntime(12694):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
E/AndroidRuntime(12694):  at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12694):  at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(12694):  at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(12694):  at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12694):  at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12694):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(12694):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
E/AndroidRuntime(12694):  at dalvik.system.NativeStart.main(Native Method)
I/Process (12694): Sending signal. PID: 12694 SIG: 9

**Comment by timemarkov** [comment]
@harkin Also can you give some instruction about which resources need (does it is need to be added?) to be added (or jars are enough) in project? As i can see from log have problem with color:

E/AndroidRuntime(12694): java.lang.NoClassDefFoundError: io.intercom.android.sdk.R$color

Thanks in advance

**Comment by harkin** [comment]
Ah right you haven't grabbed any assets or other things. To get the library working correctly you'll need to include the assets and resources found [here](https://github.com/intercom/intercom-android/tree/master/jar/intercom-sdk-base). 

If you plan to use proguard you'll also need to include the proguard file found there

**Comment by harkin** [comment]
Gonna close this out for now, let me know if you're still having trouble setting this up and we can reopen the issue

**Comment by timemarkov** [comment]
Hello,

Finnaly I success to integrate but found one issue. When android:versionCode in my AndoridManfest.xml file is different from 1 call of itercom initialize method return follow error:

E/AndroidRuntime( 9735): Caused by: java.lang.IllegalArgumentException: Component class io.intercom.android.sdk.preview.PreviewService does not exist in com.groupsinc.android.goldsgymbedford
Please can you give me some help here?

Thanks in advance.

**Comment by DaleCantwell** [comment]
@timemarkov Could I get you to send on your AndroidManifest.xml? If you'd rather not share it on github feel free to message us on intercom.io, mention me (@DaleCantwell) in the subject or somewhere in the issue and our team will assign it to me.
As I have never built an Android app using C++ in Qt we may need some back and forth to get to solve this problem so a private conversation in Intercom may be better suited. i will post any fixes to the issue in this thread before closing.

**Comment by timemarkov** [comment]
<?xml version="1.0"?>
<manifest package="com.groupsinc.android.cincofit" xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.5.3" android:versionCode="1" android:installLocation="auto">
    <application android:hardwareAccelerated="true" android:name="com.groupsinc.MainApplication" android:label="CINCOfit" android:icon="@drawable/ic_launcher" android:screenOrientation="portrait">
        <activity android:configChanges="orientation|uiMode|screenLayout|screenSize|smallestScreenSize|locale|fontScale|keyboard|keyboardHidden|navigation" android:name="com.groupsinc.MainActivity" android:label="CINCOfit" android:screenOrientation="portrait" android:launchMode="singleTop">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <meta-data android:name="android.app.lib_name" android:value="gmobilev2"/>
            <meta-data android:name="android.app.qt_sources_resource_id" android:resource="@array/qt_sources"/>
            <meta-data android:name="android.app.repository" android:value="default"/>
            <meta-data android:name="android.app.qt_libs_resource_id" android:resource="@array/qt_libs"/>
            <meta-data android:name="android.app.bundled_libs_resource_id" android:resource="@array/bundled_libs"/>
            
            <meta-data android:name="android.app.bundle_local_qt_libs" android:value="-- %%BUNDLE_LOCAL_QT_LIBS%% --"/>
            <meta-data android:name="android.app.bundled_in_lib_resource_id" android:resource="@array/bundled_in_lib"/>
            <meta-data android:name="android.app.bundled_in_assets_resource_id" android:resource="@array/bundled_in_assets"/>
            
            <meta-data android:name="android.app.use_local_qt_libs" android:value="-- %%USE_LOCAL_QT_LIBS%% --"/>
            <meta-data android:name="android.app.libs_prefix" android:value="/data/local/tmp/qt/"/>
            <meta-data android:name="android.app.load_local_libs" android:value="-- %%INSERT_LOCAL_LIBS%% --"/>
            <meta-data android:name="android.app.load_local_jars" android:value="-- %%INSERT_LOCAL_JARS%% --"/>
            <meta-data android:name="android.app.static_init_classes" android:value="-- %%INSERT_INIT_CLASSES%% --"/>
            
            <meta-data android:value="@string/ministro_not_found_msg" android:name="android.app.ministro_not_found_msg"/>
            <meta-data android:value="@string/ministro_needed_msg" android:name="android.app.ministro_needed_msg"/>
            <meta-data android:value="@string/fatal_error_msg" android:name="android.app.fatal_error_msg"/>
            

            
            
            

            
            
            <meta-data android:name="android.app.background_running" android:value="false"/>
            
        </activity>
        <service android:enabled="true" android:exported="true" android:isolatedProcess="false" android:label="beacon" android:name="org.altbeacon.beacon.service.BeaconService"/>
        <service android:enabled="true" android:name="org.altbeacon.beacon.BeaconIntentProcessor"/>
        <activity android:name="com.groupsinc.NativeDialog.ImagePickerActivity" android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="com.groupsinc.NativeDialog.PICK_IMAGE"/>
            </intent-filter>
        <meta-data android:name="android.app.lib_name" android:value="gmobilev2"/>
        </activity>
        <service android:name="com.parse.PushService"/>
        <receiver android:name="com.groupsinc.GroupsParsePushBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.USER_PRESENT"/>
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>

                
                <category android:name="com.groupsinc.android.cincofit"/>
            </intent-filter>
        </receiver>
        <receiver android:name="com.groupsinc.GroupsParsePushBroadcastReceiver" android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE"/>
                <action android:name="com.parse.push.intent.DELETE"/>
                <action android:name="com.parse.push.intent.OPEN"/>
            </intent-filter>
        </receiver>
        <activity android:name="com.facebook.LoginActivity" android:label="@string/app_name" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:screenOrientation="portrait">
            <meta-data android:name="android.app.lib_name" android:value="gmobilev2"/>
        </activity>
        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/app_id"/>

        <meta-data android:name="com.groupsinc.parse.applicationId" android:value="%%PARSE_APPLICATION_ID%%"/>
        <meta-data android:name="com.groupsinc.parse.clientKey" android:value="%%PARSE_CLIENT_KEY%%"/>
        <meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/push_icon"/>
    </application>
    <uses-sdk android:minSdkVersion="11"/>
    <supports-screens android:largeScreens="true" android:normalScreens="true" android:anyDensity="true" android:smallScreens="true"/>

    
    
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>

    
    <permission android:protectionLevel="signature" android:name="com.groupsinc.android.cincofit.permission.C2D_MESSAGE"/>
    <uses-permission android:name="com.groupsinc.android.cincofit.permission.C2D_MESSAGE"/>

    
    

</manifest>

**Comment by timemarkov** [comment]
Hello Dale,
Please can you write mail and I will send to you. I can not attach here.
Best Regards,
Time

**Comment by DaleCantwell** [comment]
@timemarkov if you go to https://www.intercom.io/ and click the in app messenger at the bottom right you can write into the intercom team. I think that will be the best way for us to gather the most information on this bug.

**Comment by DaleCantwell** [comment]
@timemarkov I had a look over your manifest file. It looks like in Qt you use a line like this
<uses-sdk android:minSdkVersion="11"/>
Could you try use this instead
<uses-sdk android:minSdkVersion="9"/>
Just to see if it works? I understand this may cause issues in the rest of your app as you wish to target 11 but I would be interested to see if this is a manifest merger issue.

**Comment by swats1010** [comment]
I also have similar issue 👍 


 FATAL EXCEPTION: main
                                                      java.lang.NoClassDefFoundError: io.intercom.android.sdk.IntercomLifecycleTracker
                                                          at io.intercom.android.sdk.Injector.getLifecycleTracker(Injector.java:192)
                                                          at io.intercom.android.sdk.Injector.initWithAppCredentials(Injector.java:65)
                                                          at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:63)
                                                          at io.intercom.android.sdk.Intercom.initialize(Intercom.java:43)
                                                          at se.wifog.activity.AppController.onCreate(AppController.java:28)
                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3236)
                                                          at android.app.ActivityThread.access$2200(ActivityThread.java:117)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:966)
                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                          at android.os.Looper.loop(Looper.java:123)
                                                          at android.app.ActivityThread.main(ActivityThread.java:3647)
                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:507)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
                                                          at dalvik.system.NativeStart.main(Native Method)

I am using flavours for my app for different intercom sdk versions  and added this too in my manifest 
  <uses-sdk tools:overrideLibrary="io.intercom.android.sdk"/>

but still it crashes at initialize

**Comment by ronocod** [comment]
@swats1010 do you have multidex enabled on your app?

**Comment by swats1010** [comment]
yes I do have them enabled and i have flavours in my app like this :


Thanks & Regards

Swati Agarwal

Ph No. : +918588836180

**Comment by swats1010** [comment]
defaultFlavor {
            minSdkVersion 9

            signingConfig signingConfigs.key
            multiDexEnabled true
            dependencies
                    {
                        compile 'io.intercom.android:intercom-sdk-base:1.+'

                    }

        }
        example {
            applicationId 'se.com.example'
            minSdkVersion 15

            signingConfig signingConfigs.key
            multiDexEnabled true
            dependencies
                    {
                        compile 'io.intercom.android:intercom-sdk-base:3.+'

                    }
        }

Thanks & Regards

Swati Agarwal

Ph No. : +918588836180

**Comment by swats1010** [comment]
and in my manifest this too <uses-sdk
tools:overrideLibrary="io.intercom.android.sdk"/>...

apologies for multiple email .. some problem with my system controls



Thanks & Regards

Swati Agarwal

Ph No. : +918588836180

**Comment by swats1010** [comment]
I am testing on device with APi level 9


Thanks & Regards

Swati Agarwal

Ph No. : +918588836180

**Comment by ronocod** [comment]
Have you set up the multidex support library as described here? https://developer.android.com/studio/build/multidex.html

**Comment by swats1010** [comment]
Yes , i have this compile 'com.android.support:multidex:1.0.0'



Thanks & Regards

Swati Agarwal

Ph No. : +918588836180

**Comment by ronocod** [comment]
Can you file a separate issue for this? I don't think this is the same problem as the original one in this thread.

**Comment by swats1010** [comment]
sure


Thanks & Regards

Swati Agarwal

Ph No. : +918588836180
