### ISSUE TITLE
Multiple Intercom threads

### ISSUE THREAD

**Issue by AndrejLukasevic** [intercom/intercom-android#136]
Hi, i have noticed, in Crashlytics, that i have a huge amount of threads ~300. Most of them created by intercom.
Is it ok?
I think that it makes OutOfMemoryError be thrown more often because of it
![thrads problem](https://cloud.githubusercontent.com/assets/5744352/10358749/29fc0bd0-6d9a-11e5-8c8f-0113606806fc.PNG)
Version 1.1.2

**Comment by DaleCantwell** [comment]
@AndrejLukasevic that doesn't look correct. I would recommend updating to 1.1.7 but either way 1.1.2 shouldn't be generating that number of threads. 
There are a few possibilities I can think of. We will need to get more information about your Intercom integration. I've just pinged you in intercom so we can talk there. Once we have a resolution we can update this public issue without any of your private integration details.

**Comment by AndrejLukasevic** [comment]
Here a link to crashlytics: http://crashes.to/s/db7f414fb52
As you can see there was crash, when user tried to open intercom chat window. And it crashed because of android.os.TransactionTooLargeException.

But lets focus on those Threads. As you can see there is a lot of them.

I am using retrofit 1.9.0 library that i assume have dependency on OkHttp  library.
http://search.maven.org/#artifactdetails%7Ccom.squareup.retrofit%7Cretrofit%7C1.9.0%7Cjar

I am not sure how to check which version of OkHttp it uses.

Also using Picasso 2.5.2 lib, that also uses OkHttp Client

Here is my all dependencies:

dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:22.1.0'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.darwinsys:hirondelle-date4j:1.5.1'
    compile 'com.google.android.gms:play-services-base:7.5.0'
    compile 'com.google.android.gms:play-services-maps:7.5.0'
    compile 'com.google.android.gms:play-services-location:7.5.0'
    compile 'com.google.android.gms:play-services-analytics:7.5.0'
    compile 'com.google.android.gms:play-services-gcm:7.5.0'
    compile 'com.rengwuxian.materialedittext:library:2.1.4'
    compile 'com.github.navasmdc:MaterialDesign:1.5@aar'
    compile('com.amazonaws:aws-android-sdk-core:2.2.1') {
        exclude group: 'commons-logging'
    }
    compile 'com.amazonaws:aws-android-sdk-s3:2.2.1'
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    compile('io.intercom.android:intercom-sdk:1.1.2@aar') {
        transitive = true
        exclude group: 'com.google.android.gms' // excluding. it fixes conflicts
    }
    compile 'com.pnikosis:materialish-progress:1.4'
    compile 'com.davemorrissey.labs:subsampling-scale-image-view:2.3.0'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.retrofit:converter-jackson:1.9.0'
    compile 'com.github.castorflex.smoothprogressbar:library:1.0.0'
    compile 'com.etsy.android.grid:library:1.0.5'
    compile 'org.quanqi:mpandroidchart:1.7.4.1'
    compile 'eu.inmite.android.lib:android-styled-dialogs:1.2.0'
    compile 'com.github.andrejlukasevic:job-queue-manager:1.3.0'
    compile 'org.apmem.tools:layouts:1.9@aar'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'org.apache.httpcomponents:httpmime:4.2.5'
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.4'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.4.4'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.4'
    compile 'com.google.zxing:core:3.2.0'
    compile 'com.pixplicity.multiviewpager:library:1.0'
    compile files('libs/android-integration-3.1.0.jar')
    compile('com.crashlytics.sdk.android:crashlytics:2.2.4@aar') {
        transitive = true;
    }
}

**Comment by harkin** [comment]
@AndrejLukasevic sorry for taking so long to get back to you on this

You're spot on, that is waaay too many threads. The short version is that we have a websocket connection and it spins up a thread for itself to do it's work on. When you background an app we disconnect from the websocket but were *not* stopping that thread and it was leaking. I'm fixing this now, next version of the library will include this fix

**Comment by harkin** [comment]
small update: I can reproduce this in some sample apps. Still trying to track down the root cause

**Comment by harkin** [comment]
I have root caused this (finally). The short of it is exactly what you'd expect really: poor thread management. Substantial dev work around this area is making the fix hard to release on the 1.x branch. On the 3.x line (currently in beta) this has been addressed. 

I'll leave this open until 3.x is out of beta, suggested fix is going to be 'update to 3.x' then

**Comment by ronocod** [comment]
We've released version 3.0.0 which fixes this by using less threads and limiting the number of threads we create. If you still see this issue after updating to 3.0.0 please let us know.
