### ISSUE TITLE
JSON data is not synced in Intercom dashboard

### ISSUE THREAD

**Issue by shailendraborse** [intercom/intercom-android#140]
HashMap<String, Object> attr = new HashMap<String, Object>();
  attr.put("custom_attributes", jsonObject);
  Intercom.client().updateUser(attr);

Plzzzz suggest where I am doing wrong , I am sending the logs events that is synced with dashboard.
But my json data is not updated in account sections.

**Comment by harkin** [comment]
@shailendraborse are you seeing anything in logcat when you do this update? We log everything with the 'Intercom-Android' tag

**Comment by harkin** [comment]
oh, you're passing a `JSONObject` in I'm guessing? That won't work here unfortunately, you'll need to use `Map`s and `List`s as appropriate like in the examples [here](http://docs.intercom.io/Install-on-your-mobile-product/configuring-intercom-for-android)
