### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by Dcodechef** [intercom/intercom-android#141]
Hi,
I am getting null pointer exception in 
Caused by: java.lang.NullPointerException
17	at	io.intercom.android.sdk.utilities.DeviceUtils.generateMacId(DeviceUtils.java:62)
18	at	io.intercom.android.sdk.utilities.DeviceUtils.generateDeviceId(DeviceUtils.java:37)
19	at	io.intercom.android.sdk.user.DeviceData.generateDeviceData(DeviceData.java:26)
20	at	io.intercom.android.sdk.api.Api.ping(Api.java:133)

Kindly review this.

Thanks in advance.

**Comment by harkin** [comment]
@Dcodechef what version of the library are you seeing this one? Is it on any specific device or widespread?

**Comment by harkin** [comment]
Going by the line numbers you've provided it looks like this stacktrace is from a 0.9.x beta version of the library. 

The last [issue](https://github.com/intercom/intercom-android/issues/88) with `DeviceUtils` was fixed in v1.0.4. We're currently on v1.1.7, I'd suggest updating to that.
