### ISSUE TITLE
Where can I find the information of "Deep Linking in messages"?

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#146]
Thank you.

**Comment by DaleCantwell** [comment]
Hi @shiami, we currently don't have docs on deeplinking. We do support deep linking in that if you put a deep link in a message body or as the url in a button and your app or an app on your phone supports that native url scheme it will open it. 
Feel free to send us a message at www.intercom.io and we can help you with any more detailed cases or any feature requests regarding deep linking.
