### ISSUE TITLE
How can I get the unread status in the app?

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#147]
1. Knowing there are unread messages.
2. How many amount of unread messages?

Thank you.

**Comment by DaleCantwell** [comment]
Hi @shiami, we handle all of this internally. If you have integrated Intercom Android in your app and are not setting the visuals to be gone whenever the logged in user gets a message they will see a chat preview pop up over their current activity. This chat preview also has a number count to let you know how many messages they currently have.
We don't have any direct callbacks on this to let developers know the unread message count.
