### ISSUE TITLE
Could you provide more custom interface to setup or even better to open source the SDK?

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#148]
We love your platform and service. 
We are working on an O2O service that deeply involve the customer management. 

But your SDK is still very limit to change anything.
Even we can not change the language to Traditional Chinese since our main customers are in Taiwan.
Do you have any plan to open more customized settings especially to change the UI.
We really care about the user experience and the consistency experience in our product.

If you are planning to open source the SDK, it is even better.
We can commit our works to complete the SDK and release its power.

Hope you guys can think about it and working on it as soon as possible.
Cheers!

**Comment by eoin** [comment]
I'm afraid we don't currently have plans to open-source the SDK, but increased customisation and localisation are both on our roadmap.
