### ISSUE TITLE
How to handle GCM manually?

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#150]
I need to handle multiple GCM from different SDK.
How can I handle the GCM by myself?

Thanks.

**Comment by DaleCantwell** [comment]
@shiami could I get more information on what you are trying to do? Is it that you have set up Intercom GCM and you have another third party GCM integration you are trying to enable? 
Currently if you integrate Intercom GCM we will create the push message for you, is there a particular SDK that you are encountering a conflict with?

**Comment by shiami** [comment]
Yes, I have set up Intercom GCM and trying to add another GCM by our own or another 3rd party service like Layer.

Is that going to be a trouble?

**Comment by DaleCantwell** [comment]
As long as ayer has some protection against drawing other SDKs push messages there shouldn't be an issue. Reopen this issue if you come across any conflicts with other third party push integrations.
