### ISSUE TITLE
Can't get push notification on my phone

### ISSUE THREAD

**Issue by MikhailSkiyAtWork** [intercom/intercom-android#151]
I downloaded the sample for android. Change all Api_Key and all other necessary staff. In Intercom admin panel I see my user and send him a message. But I see this message only when open the app. If the app closed I don't see any push notifications. Should I use broadcast receiver and service for it? Also I have another app where I creaetd broadcast and service to start necessary activity if the push was sent, but it also doesn't work. So that is why I tried sample but it also doesn't work. So what I did wrong? Can you explain how to rise push notifications by intercom?

**Comment by DaleCantwell** [comment]
@MikhailSkiyAtWork are you seeing any errors in the log during registration?
There are many reasons this could be failing:
1. The device doesn't have an up to date play services (that should be in the logs). 
2. The google developer console SDK key is either not matching or not included in your Android integration on Intercom (that is located in your Intercom Integrations page where you get your API Key).
3. The Sender ID in the sample app is not matching the one found in your google developer console

Could you make sure the following line is hit
https://github.com/intercom/intercom-android/blob/master/samples/intercom-gcm-sample/gcmsample/src/main/java/io/intercom/gcmsample/MainActivity.java#L262 and that regID is not null or empty.

**Comment by DaleCantwell** [comment]
@MikhailSkiyAtWork going to close this guy out for now, ping us if this is still an issue for you.
