### ISSUE TITLE
How to unregister GCM?

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#152]
I still received gcm notification after calling the following method.

    private void logout(){
    // This resets the Intercom library's cache of your user's identity and wipes the slate clean.
    Intercom.client().reset();

    // Now that you have logged your user out and reset, you can register a new
    // unidentified user in their place.
    Intercom.client().registerUnidentifiedUser();
    }

**Comment by DaleCantwell** [comment]
@shiami thanks for letting us know about this issue. I'll look into reproducing this

**Comment by shiami** [comment]
Any updates?

I found that the SDK provide a way to register GCM id.

    Intercom.client().setupGCM(regId, R.mipmap.ic_launcher);

But no way to unregister it.

**Comment by DaleCantwell** [comment]
Our next update will have a fix for this issue. Reset will now clear the device token.
