### ISSUE TITLE
Stop repackaging other libraries. DexMethodCount

### ISSUE THREAD

**Issue by trevjonez** [intercom/intercom-android#154]
At current I am seeing in my build that you have repackaged a stack of libraries that count against the overall dex count. List is as follows(based on version 1.1.8@aar)

`com.google.gson` : 964
`com.squareup.okhttp` : 1692
`com.squareup.otto` : 57
`com.squareup.picasso` : 536
`com.squareup.okio` : 499
`com.squareup.retrofit` : 493
`uk.co.senab.photoview` : 258

In my case i already have okhttp, picasso, and okio within my project which means that I am loosing ~2700 methods to your repackaged libraries. You should simply specify the dependencies in your gradle build and let them come in transitively.

Given the 65K limit of android and the huge amount of reach your library has(or will gain) in today's marketplace this repackaging is really a dis-service to the community.

**Comment by harkin** [comment]
Thanks for the feedback, we've actually discussed this [in the past](https://github.com/intercom/intercom-android/issues/126#issuecomment-135748670) (you can follow links in that issue to other related issues if you want to). I'm not going to rehash the whole thing again; there are arguments for and against repackaging the dependencies and currently we feel that the advantages for us outweigh the disadvantages.

**Comment by ronocod** [comment]
We now offer a build of the SDK which brings in most of its dependencies transitively. You can find a guide to integrating it [here](https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/using-transitive-dependencies-with-intercom-for-android). If you use some of the libraries the SDK uses (e.g. Retrofit) then using this version should lower our impact on your method count. If you use this version then we highly recommend you make sure to use the same library versions as the SDK does.
