### ISSUE TITLE
Can't upload file sometimes

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#155]
E/Intercom-Android: ERROR: Upload failed: request body io.intercom.com.squareup.okhttp.MultipartBuilder$MultipartRequestBody@ee0127c

**Comment by shiami** [comment]
It might failed many times.
Please help to deal with it or provide a better log to see what's going wrong.

Thanks.

**Comment by DaleCantwell** [comment]
Hi @shiami 
Do you have any additional information? Some sueful details would be:
Filetype
Size
Where it is stored (local, dropbox, googledrive ect)
Thanks,
Dale

**Comment by shiami** [comment]
Just normal images captured using mobile phone's camera.
Stored in sdcard of my phone of course.

Sometimes it took several retries to successfully upload the image.

We are located in Taiwan. Where is your server by the way?

**Comment by DaleCantwell** [comment]
@shiami our servers for file uploads are located in the US. Depending on internet speeds and size of the file it is totally possible to see legit failures like that. As this isn't causing a crash it feels like a legit timeout. I'm going to close this issue for now but if you see this happen again and can gather any additional information then we can look into it further.
