### ISSUE TITLE
Require all strings defined in the values.xml

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#156]
There are some strings are hard-coded in the java classes:

1. [Inline Image] in the conversation list
2. Timestamps (For example: 9m ago) in the conversation list and message list.
3. "SEND" and "CANCEL" in the photo upload.
4. Might be more..

Could you define those strings in the values.xml so that we can override them in our main app with the same strings' id? 

It's very important for us to serve our customers not using English.
Thank you.

**Comment by DaleCantwell** [comment]
@shiami we plan on supporting localisation very soon. We will be moving any hard coded strings in Java files as part of this.

**Comment by DaleCantwell** [comment]
@shiami this has been updated and will be available when we release v1.1.14
I will close out this issue once that version is released.
Thanks again for letting us know about those hard-coded strings.

**Comment by shiami** [comment]
Good to know. Thanks!
