### ISSUE TITLE
App icon for GCM not working

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#159]
Intercom.client().setupGCM(regId, R.mipmap.ic_launcher);

It does not change the app icon in the GCM notification.

**Comment by DaleCantwell** [comment]
Hi @shiami, I can't reproduce the issue. I have tried with drawables and mipmaps. Could you put a breakpoint on that line and make sure it is being hit?

**Comment by shiami** [comment]
Yes, it is called. But the icon in the notification is a completely white square.

**Comment by DaleCantwell** [comment]
@shiami are you following the Material guidelines for the icon? 
From the following page http://developer.android.com/design/patterns/notifications.html under the heading "Use distinct icons" it explains:
"Don't use color to distinguish your app from others. Notification icons should only be a white-on-transparent background image." and that "Android uses these icons as masks (that is, only the alpha channel is used), the image should generally be drawn at full opacity."

![image](https://cloud.githubusercontent.com/assets/2615468/11505829/3a512202-9844-11e5-8013-9aec6b9d9232.png)

To solve your problem try and create a new resource that uses only white and transparency. A sample you can test that is bundled with the SDK is the following ``` R.drawable.intercomsdk_default_push```
