### ISSUE TITLE
Not received GCM notifications from Auto Messages, and Intercom API calls

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#160]
I can receive GCM notifications if I send from Intercom website or Intercom Android app.
But can not receive GCM notifications from Auto Messages, nor Intercom API calls.
Is there any difference or do I miss something?
Please help.

**Comment by skylerwshaw** [comment]
Hey Shiami, I've responded to your conversation started within the Intercom dashboard. This issue is unrelated to the `intercom-android` SDK.
