### ISSUE TITLE
Intercom breaks Retrofit network manager

### ISSUE THREAD

**Issue by iamcharleych** [intercom/intercom-android#165]
In my project I'm using Retrofit 2.0 + Rx. Also I'm using Intercom for analytics.
```compile('io.intercom.android:intercom-sdk:1.+@aar') {
        transitive = true
}```
When I'm running on Android 5+ everything seems to be fine. When I'm running up to 5.0 (min sdk version 15) - I'm always getting crashes and the log says smth like this:
``` Could not find class 'rx.internal...``` for most of the RxJava classes.

Here are my retrofit and rx dependencies: 
```
'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.squareup.retrofit:adapter-rxjava:2.0.0-beta2'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'io.reactivex:rxjava:1.1.0'
```

If I comment Intercom - everything's fine.

May be you have any ideas? Or maybe I should provide some more details.

**Comment by harkin** [comment]
It sounds like you're going over the 64k method limit and need to enable multidexing in your project

**Comment by iamcharleych** [comment]
Yep! You're right. Thanks
