### ISSUE TITLE
GCM icon not shown for all notification styles

### ISSUE THREAD

**Issue by mzorz** [intercom/intercom-android#166]
Might be related to this issue here (https://github.com/intercom/intercom-android/issues/159) - I think I'm having an issue with this too. I'm passing a custom drawable that follows the material design principles, etc. and it is shown alright in the status bar area but it's not showing (it shows some other default icon which doesn't look good). Check the screenshots attached.

![screen shot 2015-12-24 at 8 21 52 am](https://cloud.githubusercontent.com/assets/6597771/11994134/98f64f7c-aa18-11e5-9cec-3c0f606b132e.png)
![screen shot 2015-12-24 at 8 20 38 am](https://cloud.githubusercontent.com/assets/6597771/11994135/98f78e46-aa18-11e5-8a71-d0cb5a785d88.png)

Here's the kid icon (white with transparent background):

![ic_kid](https://cloud.githubusercontent.com/assets/6597771/11994203/4b70edce-aa19-11e5-8c20-52d3bc3bf722.png)

Please advise
Merry Christmas
Mario

**Comment by DaleCantwell** [comment]
Hi @mzorz thanks for contacting us. The icon you pass in is used for the notification icon which is used in the status bar and depending on the OS a small bubble to the bottom right of the large icon, see the bottom notification in the diagram. What we use for the main icon (labeled as photo in the image below) is the senders avatar. If you set up a profile picture on Intercom for that account it will show your avatar there. The avatar you are seeing is our default for if you don't have an avatar set up. 

![image](https://cloud.githubusercontent.com/assets/2615468/11996394/bd318744-aa59-11e5-9e66-a1678206e0e7.png)
