### ISSUE TITLE
Dependencies section in README

### ISSUE THREAD

**Issue by rohans310** [intercom/intercom-android#169]
This is not an issue, just a question I have. Sorry if this is not the right place for this. Why does the README state that the compileSdkVersion needs to be 23?

Thanks.

**Comment by harkin** [comment]
@rohans310 here's good or you can always contact us through our messenger on intercom.io :)

The compileSdkVersion should always be the latest available even if you're targetting a previous version of Android still. To the best of my knowledge the library will work if you compile against 22 but there's no reason to do that and we can't give any guarantees as we've been compiling against 23 for months now.

**Comment by rohans310** [comment]
Thanks @harkin ! I thought so too. I've read it's preferred to have the compileSdk and targetSdk versions the same.
