### ISSUE TITLE
Crittercism integration stops images from loading inside Intercom. 

### ISSUE THREAD

**Issue by lithid** [intercom/intercom-android#171]
We are seeing an issue that effects all devices running a release build with `debugging = false` and multidex enabled. The issue is that no images load inside of intercom. Contact images do not show up, they just show the default contact image. Images inside the conversations do not show up. Seems like any image that intercom attempts to load over the network doesn't work correctly and fails when the conditions above are met.

I attempted to enable verbose logging for intercom using `Intercom.setLogLevel(IntercomLogger.VERBOSE)`. I do not see the details I was hoping to find while troubleshooting this issue. I would like to find out what the issue is to why the images just don't load, whether it be a network issue, a failed json response, a parsing issue.

I don't know if it is 100% a multidex issue, but I know 100% that not using multidex fixes the issue. This issue is also fixed by running with `debugging = true` in `build.gradle`

**Comment by harkin** [comment]
Hi @lithid. That's unusual. 

If it's multidex related then what I expect is happening is that there's a dex file being generated that is, for some reason, not being referenced/parsed/loaded correctly at runtime and this particular dex file is where some/all of the image loading (we use [Picasso](https://github.com/square/picasso)) code lives. 

It's unusual that this is only happening for pre Lollipop devices. Are you extending the [MultiDexApplication](https://developer.android.com/reference/android/support/multidex/MultiDexApplication.html) and including the multidex support library v1.0.1 in your app? 

It's also unusual that this is only happening for release builds, but explainable in that the dex files generated could look very different for debug and release builds. Are there any other major differences between your debug and release builds, for example are you running Proguard on release? If yes could you try running it on your debug build and seeing if you experience this issue.

**Comment by lithid** [comment]
We are running proguard on release.
```
        debug {
            signingConfig signingConfigs.debug
            minifyEnabled false
            debuggable true
            testCoverageEnabled true
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            proguardFile 'proguard.cfg'
            debuggable false
            testCoverageEnabled false
        }
```

If I change `debuggable false` > `debuggable true`, everything works as expected. Proguard still runs, just enabled debugging and seems strange to me as well.

**Comment by harkin** [comment]
Hm. Is everything else definitely working in your app? We've seen cases where another part of the codebase starts failing silently when the build changes slightly. 

Just to be 100% sure, are you extending the MultiDexApplication and including the multidex support library v1.0.1 in your app?

**Comment by lithid** [comment]
> Hm. Is everything else definitely working in your app? We've seen cases where another part of the codebase starts failing silently when the build changes slightly.
> 
> Just to be 100% sure, are you extending the MultiDexApplication and including the multidex support library v1.0.1 in your app?

Yes to both.

**Comment by bsiegel** [comment]
It may be worth noting that we saw this exception occur in a build that is experiencing the image loading problem, though it may not necessarily be related:

```
01-14 11:08:05.401 19537-19537/? W/MessageQueue: Handler (android.os.Handler) {42519c80} sending message to a Handler on a dead thread
                                                 java.lang.RuntimeException: Handler (android.os.Handler) {42519c80} sending message to a Handler on a dead thread
                                                     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                     at android.os.Handler.enqueueMessage(Handler.java:626)
                                                     at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                     at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                     at android.os.Handler.postDelayed(Handler.java:394)
                                                     at io.intercom.android.sdk.api.PollingManager.poll(PollingManager.java:157)
                                                     at io.intercom.android.sdk.api.PollingManager.resetInboxPoll(PollingManager.java:144)
                                                     at io.intercom.android.sdk.Inbox.ConversationsListFragment.fetchNewConversations(ConversationsListFragment.java:252)
                                                     at io.intercom.android.sdk.Inbox.ConversationsListFragment.onCreate(ConversationsListFragment.java:83)
                                                     at android.app.Fragment.performCreate(Fragment.java:1678)
                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                     at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
                                                     at android.app.Activity.performStart(Activity.java:5460)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:146)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bsiegel** [comment]
It may also be worth noting that we use Picasso 2.5.0 + OkHTTP 2.1.0 in our application.

**Comment by lithid** [comment]
I ran an experiment today to see if Picasso was doing something strange because of our two versions. I first tried to create a new activity and load an image url using our version of Picasso to make sure it is working with basic configuration. I then loaded intercoms package for Picasso and didn't have any issue loading urls. I don't think the issue is Picasso. Please advise.

**Comment by lithid** [comment]
@harkin Good morning. Do you guys have anything we can try on our end? Any update on this issue from your end? This is still effecting our users. Thanks.

**Comment by keiththompson** [comment]
@lithid I've got a bare bones project [here](https://gist.github.com/keiththompson/ff95c33abc0c3c8f3337) with the same conditions you've outlined above, but haven't managed to reproduce the problem. 
Can you see something different from your dependencies or proguard rules from mine?

**Comment by lithid** [comment]
> @lithid I've got a bare bones project here with the same conditions you've outlined above, but haven't managed to reproduce the problem. 
> Can you see something different from your dependencies or proguard rules from mine?

Great thanks for taking a look. Looking over the example, it doesn't appear that would create more then 1 dex file and actually be over the dex 64K limit.  I don't believe this is actual conditions for multidex. Maybe add a bunch more libraries and make sure to keep them in proguard so unused methods/classes are not deleted?

I will start a new project to re-create the issue and share with you this project today, but please try to re-create yourself as well.

**Comment by keiththompson** [comment]
@lithid I've updated the gist I sent you previously with some added dependencies to push the method count to 77151. I've test on < 5.0 devices and still the images are loading as expected.

**Comment by lithid** [comment]
> @lithid I've updated the gist I sent you previously with some added dependencies to push the method count to 77151. I've test on < 5.0 devices and still the images are loading as expected.

Cool thanks for that. Using your configuration, I don't see the issue either. I also happen to notice that all intercom classes in your example are on the same dex file, where in our configuration, they are not. Still trying to re-create this in an example application and I think this might be the issue. It is known that multidex can cause issues when expected classes being called are in another dex.

**Comment by lithid** [comment]
After a day of really breaking down the application I found that this issue has nothing to do with MultiDex/proguard. The issue is if we initialize crittercism with your SDK, we have this issue. Here is a gist I created to outline a recreation of the issue. https://gist.github.com/lithid/42982b045f17c6432c76

**Comment by keiththompson** [comment]
@lithid I've just ran the code you posted (with my own keys) and still can't reproduce. 
I've tried with both 2.0.0-alpha8 and 1.3.1 versions of the build tools Gradle plugin. I'm using Android Studio Preview 8. Does any of this differ to your machine?

**Comment by lithid** [comment]
@keiththompson I am using 1.3.1 in our production application and 1.5.0 in my example application. Both do show the issue existing. In both my example application and our production application the issue exists if Crittercism is initialized with our Crittercism key. Both show the issue non-existent by removing or commenting out the Crittercism code.

If you are running the Android Studio Preview, are you also running preview build tools? We do not run Preview versions for our build environment or our dev environment.

I am able to reproduce this by copying my code into a new android application from scratch.

**Comment by lithid** [comment]
@keiththompson Also, I guess it is important to ask how you are trying to reproduce this? If you are starting off without the crittercism code and the images load fine, then load the crittercism code, images would most likely still show up since you are using cache in the intercom sdk for image loading.

I have been testing by making sure the the application is removed during each test case.

**Comment by lithid** [comment]
I just updated my environment to use the latest Android Studio Preview 9 and all the updated build tools and SDK tools and the issue still exists.

**Comment by lithid** [comment]
Are you also testing on a device or emulator with 5.0 or below?

**Comment by lithid** [comment]
I have attached example APKs, can you please test these?
[test-apk-examples.zip](https://github.com/intercom/intercom-android/files/112542/test-apk-examples.zip)

**Comment by keiththompson** [comment]
I'm testing on an actual 4x device, clean install. I've pretty much the same setup as your gist. I've initialised both sdk's in the Application and called `displayConversationsList` in my Activity. 

I'll test your apk's now.

**Comment by lithid** [comment]
I am also attaching two screenshots to make sure we are inline as to what the issue is we are looking for.

Not working:
![screen shot 2016-02-01 at 11 32 55 am](https://cloud.githubusercontent.com/assets/530067/12723469/9f05b3fc-c8d7-11e5-8569-195a369bfb41.png)

Working:
![screen shot 2016-02-01 at 11 28 40 am](https://cloud.githubusercontent.com/assets/530067/12723478/a436db4e-c8d7-11e5-9a95-a20b4af569a4.png)

**Comment by keiththompson** [comment]
What device or emulator are you using?
I've ran both of these on a Samsung Galaxy S2 (4.0.4)

app-debug-no-images.apk | app-debug-working-images.apk
------------ | -------------
![screenshot_2016-02-01-16-32-53](https://cloud.githubusercontent.com/assets/3908455/12723539/c40d6b16-c901-11e5-914a-06b1eafc8fc1.png) | ![screenshot_2016-02-01-16-39-28](https://cloud.githubusercontent.com/assets/3908455/12723757/aaefb796-c902-11e5-9cd0-61c141fdfdc3.png)

**Comment by keiththompson** [comment]
I've managed to replicate this with an Emulated Nexus 4.
I'm going to debug this further and I'll keep you posted.

**Comment by lithid** [comment]
Here is a list of devices that we have tested on and the ones below 5.0 we have not been able to see the images loading. These are all physical devices running in our farm.

```bash
SCH-R960	SCH-R960		4.2.2	docker
One_M8	One_M8			4.4.2	docker		
LGUS995	LGUS995		5.0.1	docker		
MotoG3	MotoG3			5.1.1	docker		
Nexus 5	Nexus 5		2013-11-14	6.0.1	docker		
SCH-I545L	SCH-I545L	Default		5.0.1	docker		
SM-G800R4	SM-G800R4		5.1.1	docker		
SM-G900R6	SM-G900R6	Default		5.0	docker		
SM-G920R4	SM-G920R4		5.1.1	docker		
SM-G928R4	SM-G928R4		5.1.1	docker		
SM-N915R4	SM-N915R4		5.0.1	docker		
One	One	US Cellular		5.0.2	docker		
One M9	One M9			5.0.2	docker			
C5155	C5155		4.0.4	docker		
C5170	C5170		4.0.4	docker		
C5170	C5170		4.0.4	docker		
E6782L	E6782L		4.4.2	docker		
LGUS550	LGUS550			5.0.2	docker		
LGUS990	LGUS990		4.4.2	docker		
LGUS991	LGUS991			5.1	docker		
MILESTONE3	MILESTONE3		2.3.6	docker		
MotoE2(4G-LTE)	MotoE2(4G-LTE)			5.1	docker		
N9516	N9516		4.4.2	docker		
N9835	N9835		4.3	docker		
Nexus 6	Nexus 6		2014-12-10	6.0	docker		
A0001	OnePlus One	2014-05-31	5.1.1	docker		
R72043b2ff94	R72043b2ff94				docker		
SCH-I435L	SCH-I435L	Default		4.4.2	docker		
SCH-R950	SCH-R950		4.4.2	docker		
SCH-R950	SCH-R950		4.4.2	docker		
SM-G530R4	SM-G530R4		5.1.1	docker		
SM-G900R4	SM-G900R4			5.0	docker		
SM-G925R4	SM-G925R4			5.1.1	docker		
SM-N900R4	SM-N900R4			5.0	docker		
SM-N910R4	SM-N910R4		5.0.1	docker		
SM-N920R4	SM-N920R4		6.0.1	docker		
SM-N920T	SM-N920T			5.1.1	docker		
SPH-L710	SPH-L710		4.4.2	docker		
USCC-E6762	USCC-E6762		4.4.4	docker		
XT1019	XT1019		5.1	docker		
XT1042	XT1042		5.1	docker		
XT1050	XT1050		4.4.2	docker		
XT1093	XT1093			5.1	docker		
XT1250	XT1250
```

**Comment by lithid** [comment]
> I've managed to replicate this with an Emulated Nexus 4.
> I'm going to debug this further and I'll keep you posted.

Thanks

**Comment by keiththompson** [comment]
Our SDK is SSL pinned to heighten security, Crittercism is intercepting all requests to our CDN and thus breaking the SSL handshake. However, updating to the latest version of Crittercism (5.5.1) and rebuilding the project has fixed the issue for us at least. 

`compile 'com.crittercism:crittercism-android-agent:5.5.1'`

Can you confirm this in your project?
Thanks.

**Comment by lithid** [comment]
> Our SDK is SSL pinned to heighten security, Crittercism is intercepting all requests to our CDN and thus breaking the SSL handshake. However, updating to the latest version of Crittercism (5.5.1) and rebuilding the project has fixed the issue for us at least.
> 
> compile 'com.crittercism:crittercism-android-agent:5.5.1'
> 
> Can you confirm this in your project?
> Thanks.

This appears to resolve this after an initial build. After testing the updated crittercism library we should be able to include it. Thanks for your help.

**Comment by lithid** [comment]
> This appears to resolve this after an initial build. After testing the updated crittercism library we should be able to include it. Thanks for your help.

Can you please update the intercom library to have more verbose logging? This seems like an issue that could have easily been identified with a few more well placed logs on network calls.

**Comment by keiththompson** [comment]
@lithid Absolutely, we'll include this in a release soon.
