### ISSUE TITLE
Update OkHttp dependency to OkHttp3

### ISSUE THREAD

**Issue by jahunt1** [intercom/intercom-android#173]
I am migrating my app to use OkHttp3. Please consider updating the OkHttp dependency so I don't have to have two different versions of the OkHttp library included in my APK.

**Comment by DaleCantwell** [comment]
Hi @jahunt1. Thanks for reaching out to us. We namespace our dependancies so we shouldn't interfere with your okhttp version. We plan on updating to OkHttp3 in our next major release, let us know if you run into any issues with having the two versions in the meantime and we will investigate any issue.

**Comment by jahunt1** [comment]
I suppose that I could have been more clear that my concern is staying below the 65k method count limit by actively managing my dependencies rather than worrying about package name conflicts. @DaleCantwell: Thank you for the heads up, I will eagerly await the next major release.

**Comment by DaleCantwell** [comment]
@jahunt1 dependancy management has been a difficult choice for us. There is a lot more context in this issue https://github.com/intercom/intercom-android/issues/50
Initially to not impact the method limit we didn't namespace dependancies. After a long discussion on the other issue we decided to go with what the majority wanted which was to take the extra method hit to not have to worry about dependancy conflicts. 
We will continue to discuss options around this and always welcome input from developers using our SDK. Hopefully we can come to a solution that will benefit everyone. In the meantime we will try to keep our dependancies as up to date as possible.
