### ISSUE TITLE
What libraries are used in the library project?

### ISSUE THREAD

**Issue by Kolyall** [intercom/intercom-android#175]
'Multiple dex files define' error after adding : 
 compile ('io.intercom.android:intercom-sdk:1.+@aar') {//for intercom
        transitive = true
}

What I can exclude from it?

**Comment by Kolyall** [comment]
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/ads/identifier/AdvertisingIdClient$Info;

**Comment by Kolyall** [comment]
Fixed by:
compile ('io.intercom.android:intercom-sdk:1.+@aar') {//for intercom
        transitive = true
        exclude group: 'com.google.android.gms'
        exclude module: 'play-services-ads'
       }

**Comment by DaleCantwell** [comment]
@Kolyall thanks for writing in. This typically happens when the version of the playstore in the host app is not the same as the Intercom SDK.
As of our current version (1.1.14) we are using     
```compile 'com.google.android.gms:play-services-gcm:8.4.0'```

**Comment by chitranshu** [comment]
Fix provided by @Kolyall helped me too.. Thanks a lot.
