### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by trevjonez** [intercom/intercom-android#179]
Looking over at [the issue on the iOS sdk](https://github.com/intercom/intercom-ios/issues/100) it seems that there is concern about when the localization is valid. This is any easy fix on android. Simply package a separate AAR file for each set of resources and let the consuming users pick which to include in their build.

The resource merger will throw them in and thus the control of what strings get included where, is in the hands of the integrating team not you.

The attached strings file should suffice for the Spanish translations (as of 1.1.11)

[strings.txt](https://github.com/intercom/intercom-android/files/131721/strings.txt)

**Comment by harkin** [comment]
Hey,

Thanks for the suggestion! Localisation is on our roadmap but I don't have any details on when it will happen. We've talked internally about the right way to do this. We don't want the Intercom messenger to be localised in languages that you don't support; equally though we don't want it to be a pain to add localization. If you supported ~30 odd languages having to add ~30 odd AARs to your project for that would be very cumbersome.

In the meantime you can add localizations locally by putting that strings file in a `values-es` folder.

**Comment by ronocod** [comment]
Happy to say that we have localization in 38 languages in our [3.0.0](https://github.com/intercom/intercom-android/releases/tag/3.0.0) release. Please try it and let us know what you think! 🌍 🌎 🌏
