### ISSUE TITLE
Large delay between sending and receiving messages

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#180]
I use 1.1.15 version.
I have large lag (~1-2 min) between sending message from web console and receiving it in my android app. It happens on intercom conversation screen and any other. I enable gcm with correct gcm registration id and don't hide messages popup with help of `intercom.setVisibility(Intercom.GONE)`. 
But if my app is in the background messages are received almost immediately (~5 sec) and system notification shown correctly.

**Comment by DaleCantwell** [comment]
Hi @danikula, thank you for reporting the issue. I wasn't able to reproduce it. Could I get you to write into us at https://www.intercom.io/ so that we could get some details on your app and conversation ids that were involved. Ask for Dale in the message and I'll follow up immediately.

**Comment by ronocod** [comment]
Hi @danikula, are you still seeing this issue? We'd like to close this if it's solved.

**Comment by danikula** [comment]
It seems this issue is not actual.
