### ISSUE TITLE
Reduce Method Count

### ISSUE THREAD

**Issue by MohMah** [intercom/intercom-android#182]
Hi, I was looking at method count of your library cause I ran into method limit problem. you have too much methods:
```
io (6795 methods, 4318 fields)
  intercom (6636 methods, 4245 fields)
    com (3319 methods, 1711 fields)
      squareup (2293 methods, 1321 fields)
      google (1026 methods, 390 fields)
    android (2067 methods, 2163 fields)
      sdk (2050 methods, 1737 fields)
    okio (499 methods, 83 fields)
    retrofit (493 methods, 213 fields)
      client (70 methods, 25 fields)
      mime (61 methods, 20 fields)
      http (27 methods, 0 fields)
      converter (15 methods, 4 fields)
      android (7 methods, 3 fields)
      appengine (7 methods, 1 field)
    uk (258 methods, 75 fields)
      co (258 methods, 75 fields)
```
I have retrofit in my dependencies and here it gets added twice for example. I think it could be fixed.

**Comment by DaleCantwell** [comment]
Hi @MohMah 
Thanks for contacting us. This is a concern that we have given a lot of thought. Initially we didn't repackage our dependancies. I have linked below to the relevant issue requesting that we start repackaging.  
https://github.com/intercom/intercom-android/issues/50

My colleague @harkin provides a detailed response on our decision to repackage here:
https://github.com/intercom/intercom-android/issues/126#issuecomment-135748670

We are always looking into alternatives but for the time being we don't plan on changing this. 
Thanks again for reaching out to us.

**Comment by MohMah** [comment]
Thanks for your response, I understand the concerns, but it would be great to give developers the different options.
Sadly we won't be able to use Intercom because of this issue and multidexing is just too much headache, so you're basically losing some customers, why not give that option to developers who are aware of the concerns.

**Comment by DaleCantwell** [comment]
@MohMah I'm sorry to hear that this is a blocker for integrating with Intercom. Essentially offering the two versions would reintroduce the potential for version conflicts again. For example in your case here if you use retrofit 1.6 and our sdk requires 2.0 we would run into a conflict. Not knowing if developers have integrated with the version that has namespaced dependancies or not makes it very difficult for us to help solve issues people might run into.
We are happy to help with setting up multidexing in the short term if that would be useful.

**Comment by ronocod** [comment]
We now offer a build of the SDK which brings in most of its dependencies transitively. You can find a guide to integrating it [here](https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/using-transitive-dependencies-with-intercom-for-android). If you use some of the libraries the SDK uses (e.g. Retrofit) then using this version should lower our impact on your method count. If you use this version then we highly recommend you make sure to use the same library versions as the SDK does.

**Comment by trevjonez** [comment]
![post-60053-unbreakable-kimmy-schmidt-its-mkk8](https://cloud.githubusercontent.com/assets/5386503/18518343/cf79d36a-7a5c-11e6-8362-ecfefb1060fd.gif)
