### ISSUE TITLE
When you go to "Contact us" then view the "Conversation", start a "New conversation" then going back to the "Conversation" section, the loading does not stop.

### ISSUE THREAD

**Issue by mevipul** [intercom/intercom-android#183]
View conversation
Tap back.
Tap the pencil icon to start a "New conversation".
Tap back again. Observe the loading wheel does not stop.
http://bugs8.gatserver.com/uploads/36f8d9a4f54fad63d2031112b13cde92.mp4

**Comment by DaleCantwell** [comment]
@mevipul thank you for logging this issue and providing a video to demonstrate it. Could I ask you to check what version of the Android SDK you are running?

**Comment by DaleCantwell** [comment]
I was able to reproduce the issue on our newest version (1.1.15). I'll look into fixing this now.

**Comment by DaleCantwell** [comment]
Issue is fixed, we will ship this fix as part of 1.1.16 this week. Thanks again for logging this with us.

**Comment by harkin** [comment]
fixed in 1.1.16 :+1:
