### ISSUE TITLE
Useless keyboard on image viewer screen

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#184]
Affected 1.1.15 version.

How to reproduce: 

1. open conversation
2. upload image
3. tap on EditText to show keyboard
4. tap on image

App shows image viewer screen with opened keyboard. Keyboard should be closed before opening image viewer.

**Comment by DaleCantwell** [comment]
@danikula thanks for reporting this and providing steps to reproduce, I will look into fixing the issue.

**Comment by harkin** [comment]
fixed in 1.1.16
