### ISSUE TITLE
Introductory text for new messages is ellipsized after pressing the FAB but no way to show full text

### ISSUE THREAD

**Issue by yonatancups** [intercom/intercom-android#200]
## Version info
  - Intercom for Android version: 3.0.0-beta3
  - Android OS version: 6.0.1
  - Android Device: Nexus 5

## Expected behavior
When the FAB is pressed a collapsingToolbarLayout window is shown with some text that we define (team intro). The text should either be fully visible or there should be a way of opening the full text. Alternatively, the textbox in settings to input the team intro shouldn't allow saving longer texts.

## Actual behavior
The text is ellipsized, but there isn't a way of going to the full version. Pressing on the text doesn't expand it nor is it expandable by itself.

## Steps to reproduce
 1. Write some really long text to be displayed at the top of the new message window (app settings -> msngr settings -> team intro)
 2. Open a new message with the FAB button
 3. The text is ellipsized and the ellipse can't be expanded

**Comment by DaleCantwell** [comment]
Hi @yonatancups 
Thanks for your feedback, we really appreciate it. Could you get a screenshot of the ellipsized text? Or even just the string you used so I can replicate it. As you suggested we should either show more lines in the SDK or we should restrict the textbox that allows you to add the team profile. 
I'll update this issue with any changes made to the profile.

**Comment by ronocod** [comment]
The length of the team intro is limited to 160 characters now, and as of version 3.0.8 it should be fully visible on all devices.
