### ISSUE TITLE
Message button it's too far from the edge of the screen

### ISSUE THREAD

**Issue by orlando** [intercom/intercom-android#205]
Hello Guys,

I'm trying to use Intercom Android in a React native app. Everything is working but the message button looks to far from the edge of the screen.

![screen](https://cloud.githubusercontent.com/assets/849872/15780128/bee8138e-29d2-11e6-9da3-952dd34add6b.png)

## Version info
  - Intercom for Android version: 1.1.20
  - Android OS version: 4.4.2
  - Android Device: LG-D950G

## Expected behaviour

Message button to be closer to the corner

## Actual behavior

Message button is too far from the edge of the screen

**Comment by ronocod** [comment]
Hi @orlando,

The button is appearing as designed here. We're gonna be making some updates to our UI soon, I'll update this once they're released so you can see if you like our new UI better 😄 ✨

**Comment by orlando** [comment]
@ronocod Awesome!. I thought it was broken :sweat_smile:. I'll release the app like that and wait for the new UI to come.

Thanks again! 🚀

**Comment by DaleCantwell** [comment]
Hi @orlando,
We have released version 3.0.0 https://github.com/intercom/intercom-android/releases/tag/3.0.0
The placement of the messenger button has been changed, to enable it you need call Intercom.client().setLauncherVisibility(Intercom.Visible)
We now have more custom launcher options than before, allowing you to create your own launcher and add an unread badge.
You can find out more here: https://docs.intercom.io/messenger-v3/upgrade-to-the-new-messenger-android

**Comment by orlando** [comment]
Cool!, I'll check it out. Thanks @DaleCantwell
