### ISSUE TITLE
java.lang.NullPointerException: NexusSocket.java

### ISSUE THREAD

**Issue by Digisha** [intercom/intercom-android#206]
We recently started getting crash in our app

## Version info
  - Intercom for Android version: 1.1.15
  - Android OS version: 4.4.2
  - Android Device: SM-G900R4

## Expected behavior
- Our app should not crash

## Actual behavior
- App is crashing

## Logs
```
0 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.intercom.android.sdk.nexus.NexusEvent.toJsonFormattedString()' on a null object reference
!	1	at io.intercom.android.sdk.nexus.NexusSocket.onOpen(NexusSocket.java:170)
2	at io.intercom.com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:151)
3	at io.intercom.com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
4	at io.intercom.com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
5	at io.intercom.com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
6	at io.intercom.com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
7	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
8	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9	at java.lang.Thread.run(Thread.java:811)
```

**Comment by ronocod** [comment]
Hi @Digisha,

Can you try updating to 1.1.20 to see if this helps? Could you also tell us if you are using OkHttp in your app, and if so, what version?

**Comment by Digisha** [comment]
We will update intercom sdk to 1.1.20 in our next version. 
We are using OkHttp v2.1.0 in our app.

**Comment by ronocod** [comment]
Hey @Digisha, are you still getting this crash? I'd like to close this off if it's resolved.

**Comment by Digisha** [comment]
@ronocod our build with the updated intercom SDK v1.1.21 will be in production today. I will update you at the end of this week.

**Comment by ronocod** [comment]
@Digisha that's great, thanks :)

**Comment by Digisha** [comment]
Hi @ronocod, we haven't received this crash on our app with intercom SDK v1.1.21. Looks like it is resolved with the updated intercom SDK.

**Comment by ronocod** [comment]
Wonderful, thanks for letting us know :)
