### ISSUE TITLE
App crash due to intercom sdk (Notification android.app.RemoteServiceException)

### ISSUE THREAD

**Issue by NammariMarkavip** [intercom/intercom-android#208]
## Version info
  - Intercom for Android version: 1.1.19
  - Android OS version: android5.0,5.1.15.1.1 ,6.0.16.0.1,5.05.0,6.0.16.0.1,6.06.0
  - Android Device:Samsung Galaxy Note4,Samsung Galaxy S4,Samsung Galaxy E5,Samsung Galaxy Note 3,SM-G930F,Xperia Z3 Dual ,One (M8).

## Expected behavior
No crash should occur 
## Actual behavior
Crash occur when you show notifictiaons i most of them in-app notifications 
## Steps to reproduce
Try to generate notifciation in status bar or in-app notifications 
## Logs

0	android.app.RemoteServiceException: Bad notification posted from package com.private.app: Couldn't create icon: StatusBarIcon(pkg=com.private.appuser=0 id=0x7f0201d3 level=0 visible=true num=0 )
1	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1535)
2	at android.os.Handler.dispatchMessage(Handler.java:102)
3	at android.os.Looper.loop(Looper.java:155)
4	at android.app.ActivityThread.main(ActivityThread.java:5696)
5	at java.lang.reflect.Method.invoke(Native Method)
6	at java.lang.reflect.Method.invoke(Method.java:372)
7	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
8	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by ronocod** [comment]
Hi @NammariMarkavip,

We're already tracking this issue as https://github.com/intercom/intercom-android/issues/198, you can find more information about it there.
