### ISSUE TITLE
Beta - Api call failed: No body returned from the server

### ISSUE THREAD

**Issue by Mathbl** [intercom/intercom-android#210]
## Version info
  - Intercom for Android version: beta 4
  - Android OS version: 6.0
  - Android Device: Emulator 2.0

With latest Beta, I'm not able to register user. When I'm using v1.1.21 everything works. 

```java
Intercom.client().setSecureMode("hash_returned_by_server", session.getUser().getId());
Intercom.client().registerIdentifiedUser(new Registration().withUserId(session.getUser().getId()));
```
(I also call .reset() when user logout from my app).

Any idea?

## Logs
```java
06-15 13:27:16.894 16519-16519/com.myapp.android E/Intercom-Android: ERROR: Failed to register or update user: No body returned from the server
06-15 13:29:39.235 16519-16519/com.myapp.android E/Intercom-Android: ERROR: Api call failed: No body returned from the server
```

**Comment by DaleCantwell** [comment]
@Mathbl it appears that your app is not fully opted into the beta. I have directly messaged you in Intercom with further instructions. If that solves this issue let us know here so we can close this issue out.
Thanks
-DC

**Comment by DaleCantwell** [comment]
Hi @Mathbl, I'm going to close out the issue for now, it looks like your opted into the beta from our end but if you are running into any integration issues let us know and I can reopen this.
