### ISSUE TITLE
Unable to load conversation after clearing app cache

### ISSUE THREAD

**Issue by imperat0r** [intercom/intercom-android#211]
Loading conversation using method : Intercom.client().displayConversationsList(); works fine except one situation: when I use android settings to clear application data (cache). I thought it is some network error but I figured out after some time that this would be steps to reproduce (in step one will explain my configuration):
1. Install intercom in application onCreate method as explained in tutorial, after logging in use Registration.create().withEmail("bob@example.com") method to login user. I also have Google cloud messaging setup and it works fine. When I use  Intercom.client().displayConversationsList() conversation is loaded fine, I'm able to send message, receive message. Small popup blue ballon is also working when new message is received. When app is in background and I send message to "user" push notifications are sent so everything excellent so far. 
2. Logout (Intercom. client.reset() is called()
3. **Go to settings in android phone ->settings->apps-> find your app-> clear all data and cache !**
4. Login again in your app (I think I used another account, but if I try to login with the same as in step 1 it does not work either) , try to see conversation list
5. Feel sad because it is not working ( It says unable to load conversations, if I tap to load again it does not work no mather how many times I tap to load them again.)

My app is installed with android studio(debug enviroment, if I reinstall it, it will work again). Phone is galaxy s7, android version is 6.0.1. I sent today message to your team in your chat regarding this problem.

**Comment by ronocod** [comment]
Hi @imperat0r,

I'm having trouble reproducing this, what version of the SDK are you using? Can you reproduce this consistently?

**Comment by imperat0r** [comment]
I am unable to reproduce this again. This can be closed.
