### ISSUE TITLE
Intercom Version compatible with compileSdkVersion 21 Application

### ISSUE THREAD

**Issue by icsd** [intercom/intercom-android#212]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: io.intercom.android:intercom-sdk:1.+@aar
  - Android OS version: - 
  - Android Device: -

## Expected behavior
Build Gradle file

## Actual behavior
Gradle File has errors. Can not build project.

I am getting the following error:
All com.google.android.gms libraries must use the exact same version specification
(mixing versions can lead to runtime crashes).
Found versions 8.4.0, 8.1.0. Examples include com.google.android.gms:play-services-measurement:8.4.0 and com.google.android.gms:play-services-analytics:8.1.0.

## Steps to reproduce
 1.  - 
 2.  -
 3.   -
## Logs
In my project I use `compileSdkVersion 21` and  `play-services-analytics:8.1.0`. I do not want to  change neither of these properties because I use the `AndroidHttpClient`  which was deprecated from API level 22 and removed in API Level 23. Is there an Intercom Version compatible with `compileSdkVersion 21` and `play-services-analytics:8.1.0`?

Thank you

**Comment by ronocod** [comment]
Can you try using version `1.1.12`? It's the latest version that uses Play Services `8.1.0`.

Having said that there have been a lot of fixes and improvements since that version, and we really recommend that you update your `compileSdkVersion` and use an alternative HTTP client.

**Comment by icsd** [comment]
I have it in mind..
Its ok with 1.1.12 version. 
Thank you very much!
