### ISSUE TITLE
support for GCM 9.2.0?

### ISSUE THREAD

**Issue by snkashis** [intercom/intercom-android#217]
Are there any issues running this with `compile "com.google.android.gms:play-services-gcm:9.2.0"`? as a dependency?

I would assume I want the unbundled version? like

```
dependencies {
    compile project(':intercom-sdk-base') // Intercom base library
    compile project(':intercom-sdk-gcm') // Intercom messaging services that uses Google cloud messaging
}
```

**Comment by DaleCantwell** [comment]
Hi @snkashis,
We have updated to GCM 9.2.1 in version 3.0.0 of our SDK https://github.com/intercom/intercom-android/releases/tag/3.0.0
Thanks,
Dale
