### ISSUE TITLE
Add repackaged library versions to release notes

### ISSUE THREAD

**Issue by trevjonez** [intercom/intercom-android#222]
## Version info
  - Intercom for Android version: 3.0
  - Android OS version: Any
  - Android Device: Any

## Expected behavior
Repackaged dependency version should be publicly listed

## Actual behavior
Developers that prefer to not double package libraries are forced to play a trial and error game to discover the repackaged library versions

## Steps to reproduce
 1. Rename `intercom-sdk-base-3.0.0.aar` file to `intercom-sdk-base-3.0.0.zip`
 2. unzip resulting file
 3. browse to `intercom-sdk-base-3.0.0/libs` directory
 4. unzip `repackaged_dependencies.jar`
 5. view resulting directory to discover repackaged dependencies

`com.github.bumptech.glide:glide`
`com.facebook.rebound:rebound`
`com.google.code.gson:gson`
`com.squareup:otto`
`com.squareup.okhttp3:okhttp`
`com.squareup.retrofit2:retrofit`
`com.squareup.okio:okio`

and some bit of `android.sdk`

The issue of the fatAAR has been kicked to death and we have found other ways to deal with the situation. Can those of us who actively manage our dependencies get some tiny sliver of transparency from the intercom team in this regard?

#50 #126 #154 #182

**Comment by DaleCantwell** [comment]
Hi @trevjonez,
Thanks for contacting us. We'll start listing our dependancy tree on our readme and call out version updates in our changelog. For now I hope this helps:

```
+--- project :intercom-sdk-base
|    +--- com.android.support:design:24.1.0
|    |    +--- com.android.support:appcompat-v7:24.1.0
|    |    |    +--- com.android.support:animated-vector-drawable:24.1.0
|    |    |    |    \--- com.android.support:support-vector-drawable:24.1.0
|    |    |    |         \--- com.android.support:support-v4:24.1.0
|    |    |    |              \--- com.android.support:support-annotations:24.1.0
|    |    |    +--- com.android.support:support-v4:24.1.0 (*)
|    |    |    \--- com.android.support:support-vector-drawable:24.1.0 (*)
|    |    +--- com.android.support:support-v4:24.1.0 (*)
|    |    \--- com.android.support:recyclerview-v7:24.1.0
|    |         +--- com.android.support:support-v4:24.1.0 (*)
|    |         \--- com.android.support:support-annotations:24.1.0
|    +--- com.facebook.rebound:rebound:0.3.8
|    +--- com.squareup:otto:1.3.8
|    +--- com.github.bumptech.glide:glide-intercom:3.7.0
|    +--- com.squareup.retrofit2:retrofit:2.1.0
|    |    \--- com.squareup.okhttp3:okhttp:3.3.0 -> 3.4.1
|    |         \--- com.squareup.okio:okio:1.9.0
|    +--- com.squareup.retrofit2:converter-gson:2.1.0
|    |    +--- com.squareup.retrofit2:retrofit:2.1.0 (*)
|    |    \--- com.google.code.gson:gson:2.7
|    +--- com.google.code.gson:gson:2.7
|    +--- com.squareup.okhttp3:okhttp:3.4.1 (*)
|    \--- com.squareup.okhttp3:okhttp-ws:3.4.1
|         \--- com.squareup.okhttp3:okhttp:3.4.1 (*)
\--- project :intercom-sdk-gcm
     \--- com.google.android.gms:play-services-gcm:9.2.1
          +--- com.google.android.gms:play-services-base:9.2.1
          |    +--- com.google.android.gms:play-services-basement:9.2.1
          |    |    \--- com.android.support:support-v4:23.0.0 -> 24.1.0 (*)
          |    \--- com.google.android.gms:play-services-tasks:9.2.1
          |         \--- com.google.android.gms:play-services-basement:9.2.1 (*)
          +--- com.google.android.gms:play-services-basement:9.2.1 (*)
          \--- com.google.android.gms:play-services-iid:9.2.1
               +--- com.google.android.gms:play-services-base:9.2.1 (*)
               \--- com.google.android.gms:play-services-basement:9.2.1 (*)
```
Thanks,
Dale
