### ISSUE TITLE
Android Support library version 24.1.0

### ISSUE THREAD

**Issue by mtiidla** [intercom/intercom-android#225]
## Version info
  - Intercom for Android version: 3.0.1
  - Android OS version: Any
  - Android Device: Any

Please don't forget to update the support library version to **24.1.1** before releasing 3.0.2 as it is not possible to build the App with 3.0.1 that bundles 24.1.0 due to resource issues with the support library.
[https://developer.android.com/topic/libraries/support-library/revisions.html](url)

**Comment by harkin** [comment]
Your timing is impeccable 😄 3.0.2 has updated the support library, it's coming soon

**Comment by mtiidla** [comment]
Great to hear that! :)

**Comment by harkin** [comment]
3.0.2 available here https://github.com/intercom/intercom-android/releases/tag/3.0.2 and on bintray :)
