### ISSUE TITLE
Failed to resolve:

### ISSUE THREAD

**Issue by tomlobato** [intercom/intercom-android#226]
## Version info
  - Intercom for Android version:  'io.intercom.android:intercom-sdk:3.+'
  - Android OS version: 4.4.4 api 19
  - Android Device: Genymotion motorola MotoX

## Expected behavior
To Add "compile 'io.intercom.android:intercom-sdk:3.+'" successfuly.

## Actual behavior

Cannot add "compile 'io.intercom.android:intercom-sdk:3.+'" to build.gradle.
When trying to sync it gives several errors about libraries failed to resolve.

<img width="1440" alt="captura de tela 2016-07-28 as 9 15 03 am" src="https://cloud.githubusercontent.com/assets/1187704/17204232/a7a0f892-54a4-11e6-8841-2044ffec9748.png">

## Steps to reproduce
 1. Follow the installation of intercom-android with GCM
 2. 
 3. 

## Logs

Messages Gradle Sync:

/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle
    Error:Error:Failed to resolve: com.android.support:design:24.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.android.support:support-vector-drawable:24.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.android.support:support-v4:24.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.android.support:appcompat-v7:24.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.android.support:animated-vector-drawable:24.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.android.support:support-annotations:24.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.android.support:recyclerview-v7:24.1.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
    Error:Error:Failed to resolve: com.google.android.gms:play-services-gcm:9.2.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/Users/tom/consultoria/clientes/casare/casare_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by ronocod** [comment]
Can you check if you have any updates available in SDK Manager?

**Comment by tomlobato** [comment]
I was using sdk 23. Now it is 24, but have this error:

<img width="732" alt="captura de tela 2016-07-29 as 6 48 47 pm" src="https://cloud.githubusercontent.com/assets/1187704/17256277/1d6b3312-55bd-11e6-9bad-f469eebbce31.png">

**Comment by ronocod** [comment]
That's another update you need in SDK Manager. Have you installed all available updates?

**Comment by tomlobato** [comment]
Thanks, ronocod,
it was a matter of upgrade the environment.

**Comment by ronocod** [comment]
No problem :)
