### ISSUE TITLE
Should use FCM instead of GCM

### ISSUE THREAD

**Issue by bryant1410** [intercom/intercom-android#228]
This library should use now Firebase Cloud Messaging (FCM) instead of GCM. This allows for instance to define a sender id that is different depending on the package id being used (something like "23354655465-kjladlñkfjasdñfjskdñlafjkñldsa.apps.googleusercontent.com" instead of "23354655465), which allows using the same sender id for different Gradle flavors.

## Version info
  - Intercom for Android version: 3.0.2

/cc @matir91

**Comment by ronocod** [comment]
This is something we're working on, we just don't want to integrate it in a way that prevents people from using GCM instead. When we have an update we'll let you know.

**Comment by DaleCantwell** [comment]
Hi @bryant1410 we have just added FCM support in version [3.0.3](https://github.com/intercom/intercom-android/releases/tag/3.0.3)

To include it you will need to change your build.gradle to replace:
`compile 'io.intercom.android:intercom-sdk:3.+'`
With
```
compile 'io.intercom.android:intercom-sdk-base:3.+'
compile 'io.intercom.android:intercom-sdk-fcm:3.+'
```
Let us know if you run into any issues getting it set up.
Thanks,
Dale

**Comment by levibostian** [comment]
@DaleCantwell is the FCM dependency added to the Maven repo yet? 

<img width="949" alt="screenshot 2016-08-16 15 22 07" src="https://cloud.githubusercontent.com/assets/2041082/17714393/3ce25cdc-63c5-11e6-8aa5-dc4175609204.png">

**Comment by ronocod** [comment]
We've uploaded the dependency to [Bintray](https://bintray.com/intercom/intercom-maven/intercom-android-sdk-fcm) and we've requested that it be added to JCenter but it hasn't become available there yet. Hopefully it won't take long :)

**Comment by DaleCantwell** [comment]
@levibostian you can use it now if you add

```
repositories {
    maven {
        url 'https://dl.bintray.com/intercom/intercom-maven'
    }
}

dependencies {
    compile 'io.intercom.android:intercom-sdk-base:3.0.3'
    compile 'io.intercom.android:intercom-sdk-fcm:3.0.3'
}
```

Here is a sample integration
https://github.com/intercom/intercom-android/blob/master/samples/intercom-sample-fcm/app/build.gradle#L24

Once we are on jcenter you won't need the repositories block anymore.

**Comment by levibostian** [comment]
Yup, that would explain it. Added Bintray for now, thanks!

**Comment by jackcsk** [comment]
I found this nowhere in the doc / Google, so I just share it here:

Suggest to update the documentation, should anyone implements FirebaseMessagingService in their app and use that along with Intercom:

To allow Intercom showing Notification, yet processing other FCM messages, just extend `IntercomFcmMessengerService` for the messaging service, instead of `FirebaseMessagingService`

Now, I look for key-value-pair of "receiver=intercom_sdk" in the received message, and classify the message as Intercom message if the pair exists. (Am I right?)

**Comment by subzthanabalan** [comment]
Can the documentation be updated to mention adding the repository for now?

**Comment by ronocod** [comment]
The `repositories` block is no longer needed, the library is now available through JCenter.
