### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by aminelaadhari** [intercom/intercom-android#229]
Why do you copy the dependencies inside your sdk?
Adding your sdk has a cost of 10k in method count: 1/6 of the dex limit. 

        intercom: 10584
            android: 3815
                sdk: 3815
                    activities: 158
                    api: 204
                    attachments: 88
                    blocks: 406
                        blockInterfaces: 15
                        function: 7
                        models: 90
                        views: 25
                    commons: 32
                        utilities: 31
                    conversation: 364
                        events: 20
                    fragments: 27
                    identity: 86
                    imageloader: 59
                    inbox: 92
                    lightbox: 42
                    logger: 15
                    metrics: 111
                    models: 726
                        events: 62
                            failure: 20
                            realtime: 8
                    nexus: 179
                    preview: 287
                    profile: 105
                    spans: 6
                    store: 37
                    transforms: 9
                    user: 8
                    utilities: 205
                    views: 387
                        decoration: 6
                        holder: 56
            com: 4037
                bumptech: 2636
                    glide: 2636
                        disklrucache: 85
                        gifdecoder: 51
                        gifencoder: 43
                        load: 1273
                            data: 99
                            engine: 454
                                bitmap_recycle: 155
                                cache: 100
                                executor: 27
                                prefill: 40
                            model: 206
                                file_descriptor: 26
                                stream: 59
                            resource: 491
                                bitmap: 199
                                bytes: 5
                                drawable: 36
                                file: 26
                                gif: 123
                                gifbitmap: 42
                                transcode: 34
                        manager: 121
                        module: 9
                        provider: 53
                        request: 307
                            animation: 70
                            target: 130
                        signature: 22
                        util: 101
                facebook: 275
                    rebound: 275
                        ui: 60
                google: 1049
                    gson: 1049
                        annotations: 14
                        internal: 618
                            bind: 341
                                util: 10
                        reflect: 24
                        stream: 87
                squareup: 77
                    otto: 77
            okhttp3: 1801
                internal: 1010
                    cache: 139
                    connection: 64
                    framed: 427
                    http: 144
                    io: 18
                    platform: 53
                    tls: 33
                    ws: 79
                ws: 22
            okio: 568
            retrofit2: 363
                converter: 13
                    gson: 13
                http: 46

**Comment by ronocod** [comment]
We ran into a lot of reliability issues when we included all of our dependencies transitively, due to conflicting library versions between apps and our SDK. You can find more discussion in https://github.com/intercom/intercom-android/issues/50 (for our approach) and https://github.com/intercom/intercom-android/issues/126 (against our approach), especially [this comment](https://github.com/intercom/intercom-android/issues/126#issuecomment-135748670) which gives a more detailed explanation of our approach.

Closing this for now as we're aware of the feedback and we plan to continue repackaging for the foreseeable future.

**Comment by ronocod** [comment]
We now offer a build of the SDK which brings in most of its dependencies transitively. You can find a guide to integrating it [here](https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/using-transitive-dependencies-with-intercom-for-android). If you use this version then we highly recommend you make sure to use the same library versions as the SDK does.
