### ISSUE TITLE
Timezone should be taken into account in Date objects in user attributes

### ISSUE THREAD

**Issue by bryant1410** [intercom/intercom-android#230]
When identifying a user with a map of user attributes which contains a `Date`, the server has time zone problems. The date that appears on the web has an offset with respect to the device's time zone.

## Version info
  - Intercom for Android version: 3.0.2

**Comment by ronocod** [comment]
Date attributes need to be sent up as a UNIX timestamp and the attribute name should end in `_at`. This is mentioned in our custom attributes documentation [here](https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/send-custom-user-attributes-to-intercom).

**Comment by bryant1410** [comment]
Yeah, but wouldn't it be nice if the API converts the Date objects into a UNIX timestamp for you?

**Comment by ronocod** [comment]
That could be useful, we'll take a look at that.
