### ISSUE TITLE
Intercom FAB is sitting on top of existing FAB, can this be changed?

### ISSUE THREAD

**Issue by MiralDesai** [intercom/intercom-android#231]
## Version info
- Intercom for Android version: 3.0.2
- Android OS version: 6.0.1
- Android Device: Nexus 5
## Expected behaviour

To be able to move the FAB (Floating action button) to position on the screen or at least be able to play with it a little.
## Actual behavior

Currently the intercom FAB sits on top of a FAB I already have on the screen. When I scroll dwon my activity, I have customised my FAB to hide, to not block information the screen. When the user scrolls back up, I show my FAB again. Can this be implemented on Intercom? Currently the intercom FAB is blocking content on the screen.

This and the position of the FAB are necessary to get maximum use out of the intercom library without annoying the user and disrupting the developers existing code.

I would like to have two FABs on my activity, or at least integrate them both into one so it would work like this: http://i.stack.imgur.com/X9vzn.png

---

Let me know what you guys think of this. it seems like a must have to me since Android has FABs already, and intercom should support both.

**Comment by ronocod** [comment]
That's understandable yeah, if you want a different launcher UI then the easiest thing to do would be to add a custom launcher yourself. There's some documentation on how to do this [here](https://docs.intercom.io/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/configuring-intercom-for-android#customize-the-intercom-messenger).

Basically you can call `Intercom.client().setLauncherVisibility(Visibility.GONE);` to hide our launcher, and then make some other UI element call `Intercom.client().displayMessenger();` when tapped. Our icon drawable is `R.drawable.intercom_launcher_icon` / `@drawable/intercom_launcher_icon` if you want to use that for a second FAB. Make sure you only show the launcher after you've registered a user too.

I think having multiple FABs like in that image would work great 😄

**Comment by MiralDesai** [comment]
I don't think a custom launcher is sufficient, it's a good option to have but there are a lot of things I will miss out on if I go down that route, like an unread notifications badge. It seems like a lot of work to just move an icon.

I notice on your iOS SDK you allow padding to be added to the button, can I do this on android?

This is not only an issue when having more than one FAB button, but also an issue when there is any content on the screen in the same area. Like I said, with my FAB I had it hide during scrolling, so content is not hidden.

The biggest issue for me is simply not being able to control where that button sits. It's position currently does not conform to the material design guidelines, and  throws everything off.

I feel like this should take high priority because it's clearly a design flaw with the intercom button.

**Comment by ronocod** [comment]
We'll take a look at adding bottom padding support to Android. Hiding the button when scrolling can be done by calling `Intercom.client().setLauncherVisibility()`. 

We're also going to be investigating customisation options soon, so we'll take your feedback onboard.

**Comment by MiralDesai** [comment]
Thanks, that's good to hear. The reason I think this is a big deal is because the floating button is part of the stock android so it's unfair to expect developers to manage something different that is extremely restrictive.

I look forward to the next few updates!

**Comment by waqqas-imena** [comment]
+1. Suggesting that developers simply build the view from scratch is a very bad idea:
1. Why go from writing one line to change the position of the chat launcher to creating a new View and the associated xml files and whatnot.
2. There is no means in the API to detect whether the chat window is open or not. This means that it's now the developer's responsibility to store and maintain its state which I'm not comfortable doing.
3. Supposing that an in-app message is sent from the dashboard, How do we handle this event using the custom launcher view.

**Comment by alexblack** [comment]
+1

**Comment by DaleCantwell** [comment]
In our next release we will provide the ability to shift the Intercom FAB position, as well as the in app notifications up. I will update this issue when it is released.

**Comment by DaleCantwell** [comment]
In the current version https://github.com/intercom/intercom-android/releases/tag/3.0.18 you can update the position by adding the line below to your dimens.xml with the value you want to move up by:
``` <dimen name="intercom_bottom_padding">74dp</dimen>```
