### ISSUE TITLE
Initialize library multiple times? Switch between test and live?

### ISSUE THREAD

**Issue by MiralDesai** [intercom/intercom-android#232]
## Version info
  - Intercom for Android version: 3.0.2
  - Android OS version: 6.0.1
  - Android Device: Nexus 5

## Expected behavior

I would like to switch in my app to the testing version of intercom and our live version. I currently do this for other components throughout the my application, to allow for one app to installed on a device, and for specific users to be able to see both a test version, and a live version on my app.

## Actual behavior

I have tried calling `Intercom.initialize()` right as a user signs in or logs in, check whether they wanted test or live, and then apply the api key and app id accordingly. However this caused a crash.

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
`

Is it possible for me to call `initialize()` in other places, other than my Application class? I placed it right before I register a user with intercom. Ideally I should be able to do this without restarting the app.

**Comment by ronocod** [comment]
We currently don't support calling `Intercom.initialize()` multiple times, and you do need to call it in your `Application.onCreate()` method.

Can you send on the full stack trace for that crash?

**Comment by MiralDesai** [comment]
Sorry I don't have the log anymore, I was just playing around to see if it was possible. the stacktrace didn't have much else, just the line numbers where I was calling` initialize()`.

Might be a good feature in the future, to change keys on the fly.

**Comment by ronocod** [comment]
It sounds like the `Application` object passed in was null.

Right now we don't have any plans to support switching apps at runtime. You can achieve this at compile time by using build flavours if you want. We'll note this as a feature request but I can't see this happening in the near future.

**Comment by smathson** [comment]
I know this is closed and unlikely to be implemented but in our case we don't need to switch app id's on the fly, we just need to defer the initialization until a later point to be able to support multiple environments at runtime versus compile time. This is currently possible with the iOS SDK by waiting to call `setApiKey` until after user authentication.

Just thought I'd mention this in case the requirement of needing to call `initialize()` in the `Application.onCreate()` method was easier to remove than calling `initialize()` multiple times.

**Comment by ronocod** [comment]
@smathson as of 4.1.0 you can call `initialize()` at a later point: https://github.com/intercom/intercom-android/releases/tag/4.1.0.
