### ISSUE TITLE
Error message on the conversation list for Unidentified users

### ISSUE THREAD

**Issue by bergezps** [intercom/intercom-android#235]
## Version info
  - Intercom for Android version: io.intercom.android:intercom-sdk-base:3.+
  - Android OS version: 4.1
  - Android Device: S3

## Expected behavior
Open the previous conversation list or show me the "No conversations" messages

## Actual behavior
![intercom-s3](https://cloud.githubusercontent.com/assets/1665661/17623065/8109aa48-609e-11e6-8657-423e084f5f5c.jpg)

## Steps to reproduce
 1. Register an Unidentified user
Intercom.client().registerUnidentifiedUser()
 2. Open the messages composer
Intercom.client().displayMessageComposer();
 3. Click on the back arrow (top left)

## Logs

**Comment by ronocod** [comment]
I'm having trouble reproducing this, are you seeing any errors in Logcat?

**Comment by ronocod** [comment]
Can't reproduce, this is due to a HTTP request failing which can happen for a number of reasons unrelated to the code here.
