### ISSUE TITLE
SDK throws exception when opening messaging activity on Android 4.4.2 because missing resource.

### ISSUE THREAD

**Issue by carlbenson** [intercom/intercom-android#237]
## Version info
  - Intercom for Android version: 3.0.2
  - Android OS version: 4.4.2
  - Android Device: Huawei Che2-L11

## Expected behavior
Don't crash

## Actual behavior
Throws exception when opening messaging activity.
[intercom-stacktrace.txt](https://github.com/intercom/intercom-android/files/419740/intercom-stacktrace.txt)

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs
Attached.

**Comment by DaleCantwell** [comment]
Hi @carlbenson. Thanks for reporting the issue. 

Could I ask you two questions to help us get to the bottom of this issue:
1. Can you reproduce this on other devices? 
2. Could you send me on the version of the Android support lib you are using?

Thanks

**Comment by carlbenson** [comment]
I could reproduce it on an emulator running 4.4.2

I use support library version 24.1.1

Thanks

**Comment by ronocod** [comment]
Can you try using 3.0.4? This issue should be fixed in that version.

**Comment by carlbenson** [comment]
Yes, perfect, now it works. Thanks!
