### ISSUE TITLE
Sending a message to user containing a .gif floods logcat

### ISSUE THREAD

**Issue by hanspeide** [intercom/intercom-android#239]
- Intercom for Android version: 3.0.3
  - Android OS version: 6.0.0
  - Android Device: Nexus 5X

## Expected behavior
Sending a message containing a .gif to a user does not flood logcat

## Actual behavior
Sending a message containing a .gif floods logcat with message `W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!`

## Steps to reproduce
 1. Send message to user from Intercom on the web containing a .gif (e.g. http://giphy.com/gifs/election2016-rnc-republican-national-convention-2016-l0MYxV67vke0FqBG0)
 2. As a user open the message in the Intercom app

## Logs
`W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!`

**Comment by ronocod** [comment]
This warning comes from Glide: https://github.com/bumptech/glide/issues/743.

There are no actual negative effects from this aside from the log messages. According to comments in the above issue these log messages will be removed in Android N.
