### ISSUE TITLE
Push notification doesn't come for the first time

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#24]
Steps:
1) open app (there are no messages from intercom)
2) hide app
3) send message through web app. We get it on the device I see it in logs but there are no notification

if I open app
4)  an icon with messages counter appears in the corner
5) hide app
6) send another message
7) notification appears

It seems push notification receiver is initialized after floating panel with messages count is displayed.

**Comment by DaleCantwell** [comment]
Hi @emakovsky, thank you for letting us know about this issue. It has been fixed for the new version of our SDK beta.
