### ISSUE TITLE
Messages Preview hidden behind custom ActionBar view in AppCompatActivity

### ISSUE THREAD

**Issue by waqqas-imena** [intercom/intercom-android#245]
## Version info
  - Intercom for Android version: 1.0
  - Android OS version: 5.0
  - Android Device: Samsung SM-G900H

## Expected behavior
The Messages Preview button is hidden behind the custom action bar.

## Actual behavior
The Messages Preivew button should appear over the custom action bar.

## Steps to reproduce
1. Create New Android Application
2. Integrate Intercom sdk
3. Add an AppCompatActivity named HomeActivity. In the AndroidManifest, set the theme of this activity as `android:theme="@style/AppTheme.NoActionBar"`.
4. Add another AppCompatActivity named MyActionBarActivity with a custom action bar view.
5. Launch application
5. Verify that when a message is received through Intercom on HomeActivity, the message view appears in the top right corner.
6. Notice that when the user now navigates to MyActionBarActivity, the message view is hidden under the custom action bar view. 

## Screenshots

Activity with No Action Bar:
![withoutactionbar](https://cloud.githubusercontent.com/assets/16077394/17848680/cd9ca530-6865-11e6-874c-2fb90ceac6b3.png)

Activity with Action Bar:
![withactionbar](https://cloud.githubusercontent.com/assets/16077394/17848689/d806c870-6865-11e6-9e42-fa5591fa7288.png)

**Comment by ronocod** [comment]
This UI has been replaced in the newer versions of the SDK, so if you update to 3.x you won't have this issue any more.

**Comment by ronocod** [comment]
We will also be [dropping support](https://developers.intercom.io/blog/reminder-legacy-mobile-sdk-sunsetting) for 1.0 later this year. You'll need to upgrade to a newer version or the SDK will stop functioning in your app.
