### ISSUE TITLE
Push notifications don't work with another receiver (Localytics)

### ISSUE THREAD

**Issue by cazador4** [intercom/intercom-android#246]
## Version info
  - Intercom for Android version: 'io.intercom.android:intercom-sdk:3.+'
  - Android OS version: 4.3 
  - Android Device: Samsung Galaxy S4

## Expected behavior
I can get localytics and intercom push notifications.

## Actual behavior
I can't. If I add localytics, intercom push notifications not work.

## Steps to reproduce
 1. Add intercom to the project. (https://docs.intercom.io/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/enable-push-notifications-with-intercom-for-android)
 2. Add Localytics to the project. (https://docs.localytics.com/dev/android.html#push-messaging-android)
 3. Send push with both services.

## Logs
I don't know to get some information about getting push notifications, please tell me how to get logs about it. Maybe I could help debugging.

**Comment by ronocod** [comment]
This looks like conflicts between multiple GCM receivers. Localytics have some documentation on how to support this [here](https://docs.localytics.com/dev/android.html#custom-push-configuration-android), and we're currently working on better support for this situation. I'll update this issue when we release this functionality.

**Comment by cazador4** [comment]
Ok, thanks. I will wait for that

**Comment by cazador4** [comment]
Hi, Do you have a workaround about this situation? If I add Localytics with [this](https://docs.localytics.com/dev/android.html#custom-push-configuration-gcmreceiver-gcmlistenerservice-android) do you say that two services will work?

**Comment by DaleCantwell** [comment]
As of version 3.0.5 we have a solution in place. It should work with your own custom push integration or any third party gcm or fcm receiver provided you have access to the receivers code.

In the onMessageReceived method structure the code something like:
For a GCM integration in the GcmListenerService
```JAVA
  public void onMessageReceived(String from, Bundle message) {
      if (intercomPushClient.isIntercomPush(message)) {
          intercomPushClient.handlePush(getApplication(), message);
      } else {
          //DO HOST LOGIC HERE
      }
 }
```
For an FCM integration in the FirebaseMessagingService
```JAVA
 //For an FCM integration:
  public void onMessageReceived(RemoteMessage remoteMessage) {
      Map<String, String> message = remoteMessage.getData();
      if (intercomPushClient.isIntercomPush(message)) {
          intercomPushClient.handlePush(getApplication(), message);
      } else {
          //DO HOST LOGIC HERE
     }
 }
```

**Comment by cazador4** [comment]
Hi guys, thanks for your help. I confirm that it works right now.
You might close this issue.

**Comment by ronocod** [comment]
Great, thanks for your patience with this 😄

**Comment by cazador4** [comment]
Bad news... Right now when i click on the push, nothings happen... 👎 
We have a class application extends Application and a HomeActivity.
We are calling `Intercom.client().handlePushMessage();` inside `onCreate()`.

How can I debug this?

**Comment by ronocod** [comment]
Can you contact us through Intercom so we can help solve this? GitHub isn't great for longer conversations.

**Comment by cazador4** [comment]
Done, thanks.

**Comment by DaleCantwell** [comment]
Hi @cazador4 
Is this a push message or an in-app push notification? If its a push message are you providing a URI? If not we do nothing right now. In 3.0.6 we will open your app to its launch screen.
