### ISSUE TITLE
ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by mawadi7** [intercom/intercom-android#247]
## Version info
  - Intercom for Android version: 3.0.3
  - Android OS version: android 5.1.1
  - Android Device: SM-J120G

## Actual behavior

We are getting this exception from our crash reporting tool, we don't have information about scenarios that cause this crash to be thrown  .
Please let me know if you like to know more information.

## Logs

0	java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
1	at java.util.ArrayList.get(ArrayList.java:310)
!	2	at io.intercom.android.sdk.conversation.RecyclerConversationAdapter.onPartClicked(RecyclerConversationAdapter.java:170)
3	at io.intercom.android.sdk.views.holder.PartViewHolder.onClick(PartViewHolder.java:84)
4	at android.view.View.performClick(View.java:5246)
5	at android.view.View$PerformClick.run(View.java:21256)
6	at android.os.Handler.handleCallback(Handler.java:739)
7	at android.os.Handler.dispatchMessage(Handler.java:95)
8	at android.os.Looper.loop(Looper.java:145)
9	at android.app.ActivityThread.main(ActivityThread.java:6917)
10	at java.lang.reflect.Method.invoke(Native Method)
11	at java.lang.reflect.Method.invoke(Method.java:372)
12	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
13	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by ronocod** [comment]
Thanks for reporting this, investigating it now

**Comment by ronocod** [comment]
This is fixed in 3.0.5.
