### ISSUE TITLE
Selection problems on conversation screen

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#25]
Steps:
1. Open new conversation with messages.
2. Click on the message and hold for a moment.
-> text of message is selected.
3. Click on the screen for deselecting.

-> Selecting does not  disappear. (Only when you click on the other message).

Also it's impossible to select first and second lines of the text. The first line is a template, e.g. "Hi name"

**Comment by DaleCantwell** [comment]
To allow us to handle large messages and draw components like imageviews without needing a webview we have split up all the paragraphs, images buttons into separate rows. This is why between paragraphs you can't select the two text views. I will add a feature request for an option to select an entire bubble in one go.
