### ISSUE TITLE
Attaching images does not work in 3.0.4

### ISSUE THREAD

**Issue by hanspeide** [intercom/intercom-android#250]
## Version info
  - Intercom for Android version: 3.0.4
  - Android OS version: 6.0.0
  - Android Device: Nexus 5x

## Expected behavior
Pressing the paper clip icon should open a window where user can select an image to attach

## Actual behavior
Pressing the paper clip icon does nothing

## Steps to reproduce
 1. Write a new message
 2. Press the paper clip icon

**Comment by DaleCantwell** [comment]
Hi @hanspeide 
To use attachments in the android SDK you need to add  `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>` to you android manifest.
We decided it was best not to add the permission automatically for people who don't want to use the feature.
Read more on our permissions here: https://github.com/intercom/intercom-android#permissions
Let us know if you run into any other integration issues.

**Comment by hanspeide** [comment]
Makes sense I guess. I think the paper clip icon should be removed if the permission is not added to the manifest though.

Also, if the permission is added, do you handle the runtime permissions needed on Android >= 6.0?

**Comment by DaleCantwell** [comment]
@hanspeide yes on 6.0 and above your users will get the pop up to grand permission when they tap on the button (unless they have already granted permission elsewhere in the app).

I'm going to discuss hiding the paper clip with our designer, I think that is a better experience that the button just not working like you saw.
