### ISSUE TITLE
Network traffic

### ISSUE THREAD

**Issue by fabianbergmark** [intercom/intercom-android#253]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.0.5
  - Android OS version: 6.0.1
  - Android Device: Samsung Galaxy S6 edge plus

## Actual behavior
We have received complaints that our app is draining the battery. We have reason to believe it's due to constant network traffic. When we analyze the network traffic patterns we see that the Intercom SDK performs an HTTP request every 30 seconds (sometimes more). As our app is a background application this is a serious problem for us.

## Steps to reproduce
 1. Implement the Intercom SDK and look at network traffic patterns
 2. 
 3. 

## Logs

**Comment by ronocod** [comment]
Can you show us what the traffic patterns are? Knowing which URLs are getting called will help us solve this.

Are there any Intercom methods you're calling at a regular interval or in a background process?

**Comment by fabianbergmark** [comment]
Here is a trace that might help:
[io.flic.app_2016.09.07_10.54.trace.zip](https://github.com/intercom/intercom-android/files/458773/io.flic.app_2016.09.07_10.54.trace.zip)

**Comment by ronocod** [comment]
Can you message us through Intercom about this? It looks like this issue may be specific to your integration.

**Comment by fabianbergmark** [comment]
Should I message team@intercom.io?

It seems like you have a Websocket that pings every 30 seconds

**Comment by ronocod** [comment]
Yes, team@intercom.io is fine.

**Comment by ronocod** [comment]
Or you can just go to https://www.intercom.com/ and message us through the Web messenger :)

**Comment by ronocod** [comment]
Discussed through Intercom, this was an issue with using the SDK in multiprocess apps. We made improvements around this in 3.0.7.
