### ISSUE TITLE
java.lang.RuntimeException: Failed to resolve attribute at index 0

### ISSUE THREAD

**Issue by mawadi7** [intercom/intercom-android#255]
we having many crashes from our Crash tracking reports comming from intercom SDK we cannot with the following infromation, 
## Version info
  - Intercom for Android version:3.0.3
  - Android OS version:
5.0
5.0.1
5.0.2
5.1
5.1.1
  - Android Device:
SM-J200G
GT-I9500
GT-I8506
SM-J700F
SM-J11F
Polymer 2x
Redmi Note 3
A65B
Lenovo 2020a40
Lenovo A6000
POLYTRON-R2507
1201
A33W
F1f
## Actual behavior
`0	java.lang.RuntimeException: Failed to resolve attribute at index 0
1	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:616)
2	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6845)
3	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7014)
4	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:741)
5	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:685)
6	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:62)
7	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
8	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
!	9	at android.support.v7.view.menu.ListMenuPresenter.getMenuView(ListMenuPresenter.java:101)
10	at android.support.v7.app.AppCompatDelegateImplV7$PanelFeatureState.getListMenuView(AppCompatDelegateImplV7.java:2000)
11	at android.support.v7.app.AppCompatDelegateImplV7.initializePanelContent(AppCompatDelegateImplV7.java:1290)
12	at android.support.v7.app.AppCompatDelegateImplV7.openPanel(AppCompatDelegateImplV7.java:1132)
13	at android.support.v7.app.AppCompatDelegateImplV7.onKeyUpPanel(AppCompatDelegateImplV7.java:1497)
14	at android.support.v7.app.AppCompatDelegateImplV7.onKeyUp(AppCompatDelegateImplV7.java:947)
15	at android.support.v7.app.AppCompatDelegateImplV7.dispatchKeyEvent(AppCompatDelegateImplV7.java:941)
16	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:253)
17	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2613)
18	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4918)
19	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4873)
20	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
21	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
22	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
23	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4482)
24	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
25	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4539)
26	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
27	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
28	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
29	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
30	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
31	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
32	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
33	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4515)
34	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4757)
35	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2815)
36	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2407)
37	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2398)
38	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2792)
39	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
40	at android.os.MessageQueue.nativePollOnce(Native Method)
41	at android.os.MessageQueue.next(MessageQueue.java:143)
42	at android.os.Looper.loop(Looper.java:130)
43	at android.app.ActivityThread.main(ActivityThread.java:6946)
44	at java.lang.reflect.Method.invoke(Native Method)
45	at java.lang.reflect.Method.invoke(Method.java:372)
46	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
47	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`
## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

**Comment by harkin** [comment]
@mawadi7 might be missing something here, why do you think this is coming from the Intercom SDK? There's nothing in the stacktrace to indicate that (that I see)

**Comment by ronocod** [comment]
Can you update your app to the latest version (3.0.7) and check if this still happens? It sounds similar to issues that have been fixed in recent versions.

**Comment by ronocod** [comment]
This looks like a hardware menu button bug that was fixed in a recent version. If you update to the latest version this should be fixed, if not then let us know.

**Comment by fuzhengchao** [comment]
@GavinJoyce Hello ronocod,I meet this crash in other library。
I would like to ask you how to solve this problem in your project。
