### ISSUE TITLE
Control which process the GCM receiver runs in

### ISSUE THREAD

**Issue by fabianbergmark** [intercom/intercom-android#256]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.0.5
  - Android OS version: 6.0.1
  - Android Device: Samsung Galaxy S6 Edge plus

## Expected behavior
Our app has two processes, the main process is used as a background process, and a secondary process ":ui" is used for all UI. We only want to use Intercom in the ":ui" process and thus only initialize it in that process. However, we see crashes in IntercomGcmIntentService which I assume is because it defaults to running in the main process. I think it would be better if you don't include the service in the SDK manifest so that developers can decide which process the service runs in.

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs
{IntentService[Intercom GCM Intent Service]} {NullPointerException} (@io.intercom.android.sdk.gcm.IntercomGcmIntentService:sendTokenToIntercom:60) java.lang.NullPointerException: Attempt to invoke virtual method 'io.intercom.android.sdk.api.Api io.intercom.android.sdk.Injector.getApi()' on a null object reference at io.intercom.android.sdk.gcm.IntercomGcmIntentService.sendTokenToIntercom(SourceFile:60) at io.intercom.android.sdk.gcm.IntercomGcmIntentService.onHandleIntent(SourceFile:49) at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:158) at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ronocod** [comment]
You can add attributes for the services in your manifest, and the manifest merger will apply them at build-time.

If you update to 3.0.7 (some services have been renamed) and add this to your manifest then the GCM code should run in your UI process:
```xml
<service android:name="io.intercom.android.sdk.gcm.IntercomGcmRegistrationService" android:process=":ui"/>
<service android:name="io.intercom.android.sdk.gcm.IntercomGcmListenerService" android:process=":ui"/>
<service android:name="io.intercom.android.sdk.gcm.IntercomGcmRefreshService" android:process=":ui"/>
<receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:process=":ui"/>
```
