### ISSUE TITLE
Personalized Intercom Icon always shown blue bg when notification expanded

### ISSUE THREAD

**Issue by apo1981** [intercom/intercom-android#257]
The app notification icon has been modified following https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/enable-push-notifications-with-intercom-for-android-gcm

The app icon correctly appears in the status bar of the devices when the notification arrives (GREAT!!).

However, when the user slides down from the status bar and the notifications are expanded, the app icon notification background is always blue. Why? Is it possible to change that?

It should be possible to show the real app icon (those which is used in the launcher) when the notification is expanded?

thks

**Comment by ronocod** [comment]
The blue is the default value for your app's color setting. You can change this in Intercom by going to App Settings -> Messenger Appearance. We always set the notification background to your chosen app color, and it isn't possible to customise this right now.

**Comment by apo1981** [comment]
Thks for your reply

Is it in your roadmap to provide that feature?

**Comment by ronocod** [comment]
General UI customisation is something we're looking at soon yes ✨  😄

**Comment by apo1981** [comment]
Perfect then
I will check new release notes. 
I close the ticket
Thks
