### ISSUE TITLE
Crash Could not dispatch event: class io.intercom.android.sdk.models.events.InboxEvent

### ISSUE THREAD

**Issue by samehgerges** [intercom/intercom-android#258]
We started to see this carsh in our app crash logs since we upgraded to 3.0.7

## Version info
  - Intercom for Android version: 3.0.7
  - Android OS version: 4.1.2 & 4.4.4
  - Android Device: SM-T116NU & GT-P3100

## Logs
0	java.lang.RuntimeException: Could not dispatch event: class io.intercom.android.sdk.models.events.InboxEvent to handler [EventHandler public void io.intercom.android.sdk.inbox.ConversationsListFragment.inboxSuccess(io.intercom.android.sdk.models.events.InboxEvent)]: Can not perform this action after onSaveInstanceState
!	1	at io.intercom.com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
2	at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:387)
3	at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
4	at io.intercom.com.squareup.otto.Bus.post(Bus.java:337)
5	at io.intercom.android.sdk.MainThreadBus.post(MainThreadBus.java:18)
6	at io.intercom.android.sdk.api.CallbackHolder$4.onSuccess(CallbackHolder.java:73)
7	at io.intercom.android.sdk.api.CallbackHolder$4.onSuccess(CallbackHolder.java:64)
8	at io.intercom.android.sdk.api.BaseCallback.onResponse(BaseCallback.java:31)
9	at io.intercom.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
10	at android.os.Handler.handleCallback(Handler.java:615)
11	at android.os.Handler.dispatchMessage(Handler.java:92)
12	at android.os.Looper.loop(Looper.java:137)
13	at android.app.ActivityThread.main(ActivityThread.java:4895)
14	at java.lang.reflect.Method.invokeNative(Native Method)
15	at java.lang.reflect.Method.invoke(Method.java:511)
16	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
17	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
18	at dalvik.system.NativeStart.main(Native Method)
19	Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
20	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1533)
21	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1551)
22	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
23	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
24	at io.intercom.android.sdk.activities.IntercomMessengerActivity.displayFragment(IntercomMessengerActivity.java:156)
25	at io.intercom.android.sdk.activities.IntercomMessengerActivity.loadConversation(IntercomMessengerActivity.java:194)
26	at io.intercom.android.sdk.inbox.ConversationsListFragment.displayConversationView(ConversationsListFragment.java:246)
27	at io.intercom.android.sdk.inbox.ConversationsListFragment.inboxSuccess(ConversationsListFragment.java:357)
28	at java.lang.reflect.Method.invokeNative(Native Method)
29	at java.lang.reflect.Method.invoke(Method.java:511)
30	at io.intercom.com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
31	at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:385)
32	... 16 more
33	java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
34	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1533)
35	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1551)
36	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
37	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
38	at io.intercom.android.sdk.activities.IntercomMessengerActivity.displayFragment(IntercomMessengerActivity.java:156)
39	at io.intercom.android.sdk.activities.IntercomMessengerActivity.loadConversation(IntercomMessengerActivity.java:194)
40	at io.intercom.android.sdk.inbox.ConversationsListFragment.displayConversationView(ConversationsListFragment.java:246)
41	at io.intercom.android.sdk.inbox.ConversationsListFragment.inboxSuccess(ConversationsListFragment.java:357)
42	at java.lang.reflect.Method.invokeNative(Native Method)
43	at java.lang.reflect.Method.invoke(Method.java:511)
44	at io.intercom.com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
45	at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:385)
46	at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
47	at io.intercom.com.squareup.otto.Bus.post(Bus.java:337)
48	at io.intercom.android.sdk.MainThreadBus.post(MainThreadBus.java:18)
49	at io.intercom.android.sdk.api.CallbackHolder$4.onSuccess(CallbackHolder.java:73)
50	at io.intercom.android.sdk.api.CallbackHolder$4.onSuccess(CallbackHolder.java:64)
51	at io.intercom.android.sdk.api.BaseCallback.onResponse(BaseCallback.java:31)
52	at io.intercom.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
53	at android.os.Handler.handleCallback(Handler.java:615)
54	at android.os.Handler.dispatchMessage(Handler.java:92)
55	at android.os.Looper.loop(Looper.java:137)
56	at android.app.ActivityThread.main(ActivityThread.java:4895)
57	at java.lang.reflect.Method.invokeNative(Native Method)
58	at java.lang.reflect.Method.invoke(Method.java:511)
59	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
60	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
61	at dalvik.system.NativeStart.main(Native Method)

**Comment by ronocod** [comment]
Thanks for reporting this, we'll have a fix for this in 3.0.9 when it's released.

**Comment by ronocod** [comment]
3.0.9 is now out with a fix for this.
