### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void io.intercom.android.sdk.profile.ProfileCoordinator.profileAutoOpened(int)' on a null object reference

### ISSUE THREAD

**Issue by mawadi7** [intercom/intercom-android#259]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.0.7
  - Android OS version: 5.0.2
  - Android Device:Redmi Note 3

## Expected behavior
we are getting the following NPE reported by our crash tracking systems from latest intercom version we use, we don't have exact scenario so far please let me know if you need more info 
last screen opened 
`io.intercom.android.sdk.activities.IntercomMessengerActivity `

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

`
0	java.lang.NullPointerException: Attempt to invoke virtual method 'void io.intercom.android.sdk.profile.ProfileCoordinator.profileAutoOpened(int)' on a null object reference
!	1	at io.intercom.android.sdk.conversation.ConversationFragment.sdkWindowFinishedAnimating(ConversationFragment.java:506)
2	at io.intercom.android.sdk.activities.IntercomMessengerActivity$3.onSpringAtRest(IntercomMessengerActivity.java:223)
3	at io.intercom.com.facebook.rebound.Spring.advance(Spring.java:445)
4	at io.intercom.com.facebook.rebound.BaseSpringSystem.advance(BaseSpringSystem.java:129)
5	at io.intercom.com.facebook.rebound.BaseSpringSystem.loop(BaseSpringSystem.java:143)
6	at io.intercom.com.facebook.rebound.AndroidSpringLooperFactory$ChoreographerAndroidSpringLooper$1.doFrame(AndroidSpringLooperFactory.java:118)
7	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:798)
8	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
9	at android.view.Choreographer.doFrame(Choreographer.java:571)
10	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
11	at android.os.Handler.handleCallback(Handler.java:815)
12	at android.os.Handler.dispatchMessage(Handler.java:104)
13	at android.os.Looper.loop(Looper.java:194)
14	at android.app.ActivityThread.main(ActivityThread.java:5546)
15	at java.lang.reflect.Method.invoke(Native Method)
16	at java.lang.reflect.Method.invoke(Method.java:372)
17	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
18	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
`

**Comment by ronocod** [comment]
Thanks for reporting this, we'll have a fix for it in 3.0.9.

**Comment by ronocod** [comment]
3.0.9 is now out with a fix for this.
