### ISSUE TITLE
Double push messages

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#261]
## Version info
- Intercom for Android version: **3.0.9**
- Android OS version: **6.0.1**
- Android Device: **Nexus 5**
## Expected behavior

After replying on conversation mobile client should receive push notification about reply.
## Actual behavior

Sometimes android devices duplicates information in push
![screenshot](https://bytebucket.org/AlexeyDanilov/static/raw/abbe92b184840cc1d50331ab270f9e2a0f4bdfff/github/intercom-issue-261.png)
## Steps to reproduce
1. Move app to background. 
2. Reply on conversation.
3. Wait for push.

**Comment by danikula** [comment]
@ronocod Any news?

**Comment by ronocod** [comment]
Haven't been able to reproduce this yet. Can you reproduce it consistently or is this something you saw once?

**Comment by danikula** [comment]
@ronocod I see this issue in ~50% cases.

**Comment by ronocod** [comment]
Can you contact us about this through Intercom? This sounds like it could be a server-side issue.

**Comment by ronocod** [comment]
This should be fixed in 3.0.13, the client will now ignore duplicate push notifications. We're working to solve this issue server-side too.
