### ISSUE TITLE
Please support vector drawables for intercom_push_icon

### ISSUE THREAD

**Issue by jahunt1** [intercom/intercom-android#264]
Almost all of my drawables in the application are vector drawable files. It would be nice if I didn't have to include more PNGs in the application.

## Version info
  - Intercom for Android version: intercom-sdk-base-transitive-3.0.9, intercom-sdk-gcm:3.0.9
  - Android OS version: 7.0, API 24
  - Android Device: Nexus 5x (LG H790)

## Expected behavior
I expect the push notification to use my vector drawable titled intercom_push_icon.xml
## Actual behavior
The push notification uses the default intercom_push_icon.png from the packaged SDK.
## Steps to reproduce
 1. Add an Android vector file in the res/drawable directory with the title intercom_push_icon.xml
 2. Build and launch the application
 3. Log in to the application
 4. Send a message to the logged in mobile user from the Intercom web dashboard.
 5. Observe that the Android notification uses the default icon.

**Comment by jahunt1** [comment]
Better yet, allow using a resource alias. This would be preferable since I already have a drawable that is used for the notification logo.
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools = "http://schemas.android.com/tools">
    <item name="intercom_push_icon" type="drawable" tools:override="true">@drawable/ic_notification_logo</item>
</resources>
```

**Comment by ronocod** [comment]
Notifications don't have the same level of support for vectors as ImageViews have through the Support Library, but I'll take a look at this tomorrow to see if there's anything we can do.

**Comment by ronocod** [comment]
I looked into this a bit, I don't think there are any changes to our code we can make to support this better.

What you can do is place your vector drawable in a `res/drawable-anydpi-v15` folder which should make it work. Note that (as far as I can tell) this will only work if you are using the default vector build mode where AAPT generates PNG files for devices below API 21.  We also haven't tested this thoroughly so I'm not sure how stable it would be. Make sure that your fill color in your vector is white if you do this, as older devices won't tint the icon automatically.

I haven't been able to get resource aliasing working with vector drawables for push icons in any situation.

**Comment by jahunt1** [comment]
Thanks for looking into this. I think you are right, until we get better Android system support the best option is to use PNGs. I will close this issue for now.
