### ISSUE TITLE
Main changelog missing info on newer versions

### ISSUE THREAD

**Issue by tnewcomb0** [intercom/intercom-android#265]
Changelog (https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md) is missing multiple versions (I'd been looking for 1.1.21), they are just not mentioned. You can find them directly like so: https://github.com/intercom/intercom-android/tree/1.1.21

**Comment by jtreanor** [comment]
Thanks for pointing this out @tnewcomb0.

I've added the missing versions now.

James
