### ISSUE TITLE
App crash on call to       Intercom.initialize(this, YOUR_API_KEY, YOUR_APP_ID) for androi api level 9

### ISSUE THREAD

**Issue by swats1010** [intercom/intercom-android#268]
## Version info
  - Intercom for Android version:  1 (intercom version
  - Android OS version: 2.3.1 (api level 9)
  - Android Device: emulator nexus 4 with api level 9

## Actual behavior: crash for api level 9 at the call of   Intercom.initialize(this, YOUR_API_KEY, YOUR_APP_ID);
--Works fine on api level 19(tested)
## Steps to reproduce
 1. On emulator run with api level 9 android 

## LogsFATAL EXCEPTION: main
java.lang.NoClassDefFoundError: io.intercom.android.sdk.IntercomLifecycleTracker
at io.intercom.android.sdk.Injector.getLifecycleTracker(Injector.java:192)
at io.intercom.android.sdk.Injector.initWithAppCredentials(Injector.java:65)
at io.intercom.android.sdk.RealIntercom.(RealIntercom.java:63)
at io.intercom.android.sdk.Intercom.initialize(Intercom.java:43)
at se.wifog.activity.AppController.onCreate(AppController.java:28)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3236)
at android.app.ActivityThread.access$2200(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:966)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3647)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)

Product flavour added in build.gradle 

     defaultFlavor {
            minSdkVersion 9
           
            signingConfig signingConfigs.key
            multiDexEnabled true
            dependencies
                    {
                        compile 'io.intercom.android:intercom-sdk-base:1.+'

                    }

        }
        example {
            applicationId 'se.com.example'
            minSdkVersion 15
          
            signingConfig signingConfigs.key
            multiDexEnabled true
            dependencies
                    {
                        compile 'io.intercom.android:intercom-sdk-base:3.+'

                    }
        }

Android manifest entry : 
 <uses-sdk tools:overrideLibrary="io.intercom.android.sdk"/>

i have multidex enabled and added in dependencies too

**Comment by ronocod** [comment]
Has this happened after a full clean build? `RealIntercom` and `Injector` are classes from version 3 of the SDK, so they shouldn't be appearing in your build which uses version 1 of the SDK.

**Comment by swats1010** [comment]
Yes I did a complete clean build .

 And since this is not in level 1 sdk the. may be the flavor for example part did not compile the ask for level 1 and instead compiled level 3 sdk.

Regards,
Swati Agarwal

**Comment by ronocod** [comment]
Can you try removing those 2 `dependencies` blocks and adding the following to your main `dependencies` block?
```groovy
defaultFlavourCompile 'io.intercom.android:intercom-sdk-base:1.+'
exampleCompile 'io.intercom.android:intercom-sdk-base:3.+'
```

**Comment by swats1010** [comment]
i require to build two flavours of them for generating two apks .. But i
had tested with sdk level 1 and it worked fine earlier.

Thanks & Regards

Swati Agarwal

Ph No. : +918588836180

**Comment by harkin** [comment]
@swats1010 you're declaring your dependencies incorrectly.

When you set up your dependencies blocks like:
![image](https://cloud.githubusercontent.com/assets/3344901/19107473/53e62742-8ae4-11e6-9985-a0cfbe474e63.png)

The two blocks get consumed for every build. Both are declared as dependencies for every build. You can verify this yourself by running `./gradlew dependencies` and checking out the `compile` task, eg
![image](https://cloud.githubusercontent.com/assets/3344901/19107526/9b957066-8ae4-11e6-8af0-df88065ee571.png)

To fix this you need to do as @ronocod suggested and only compile the dependencies for the specific flavours you want, more info [here](https://developer.android.com/studio/build/build-variants.html#configure-dependencies)

**Comment by swats1010** [comment]
plz tell me how to properly declare multiple dependencies for different flavours of app

**Comment by ronocod** [comment]
Here's a guide to adding dependencies for specific flavours :) https://futurestud.io/tutorials/android-how-to-implement-productflavor-dependent-dependencies-with-gradle
