### ISSUE TITLE
Google Play Dependencies (Question)

### ISSUE THREAD

**Issue by ahaverty** [intercom/intercom-android#269]
By any chance, is there an alternative to the google play dependencies for including push messages? I imagine there is not. _(I'm using sdk base, but would like to have push messaging functionality if possible)_

**My situation:**
I'm developing for third-party android devices which cannot use google play services.

**Comment by ronocod** [comment]
No, our two ways of including push message functionality are through GCM and FCM and both of these require Play Services.
