### ISSUE TITLE
Can send an empty message on the conversation screen

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#27]
Steps:
1. Open any conversation.
2. Enter space (newline) and send message.

-> Empty message appear in the list marked "Tap to retry". This message will not be send for a long time. Add notification that message can not be blank.

Comment: Enter symbols "<>" and send. -> Empty message appear in the list marked "Tap to retry".

**Comment by danikula** [comment]
@DaleCantwell bug is still reproduced with message `<>` in 0.9.3

**Comment by DaleCantwell** [comment]
@danikula well spotted, I have opened an internal issue about this.

**Comment by danikula** [comment]
@DaleCantwell [issue](on 6 Apr 2015) not fixed in 1.1.15

**Comment by harkin** [comment]
@danikula there's some server side validation on replies that's causing this. A very terse explanation is that it's treating that reply as HTML and that leaves 'nothing' as the content of the message. We're looking into this, I'll close this issue as soon as it's fixed

**Comment by danikula** [comment]
@harkin any news about this issue?

**Comment by DaleCantwell** [comment]
@danikula this has been fixed in version 3.0.0, you can grab it from here: https://github.com/intercom/intercom-android/releases/tag/3.0.0
