### ISSUE TITLE
Intercom uses an outdated version of the Google Play services.

### ISSUE THREAD

**Issue by makovkastar** [intercom/intercom-android#272]
Including the Intercom dependency (io.intercom.android:intercom-sdk:3+) fails a build because of the following lint error:

```
GradleCompatible: Incompatible Gradle Versions
All com.google.android.gms libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 9.6.1, 9.4.0. Examples include com.google.android.gms:play-services-base:9.6.1 and com.google.android.gms:play-services-gcm:9.4.0
```

Which means that Intercom uses an outdated version of the Google Play services library (9.4.0). Please update it to the latest version (9.6.1).

**Comment by sachins** [comment]
It is now [v9.8.0](https://developers.google.com/android/guides/releases)

**Comment by sachins** [comment]
Current workaround to fix the error is add following line in your build.gradle

`compile 'com.google.android.gms:play-services-gcm:9.8.0'`

**Comment by ronocod** [comment]
We'll update Play Services to the latest version in our next release, and we'll post an update here when it's available.

**Comment by ronocod** [comment]
3.0.11 is out now and it uses version 9.8.0 of Play Services.
