### ISSUE TITLE
Using transitive dependencies with FCM integration

### ISSUE THREAD

**Issue by subzthanabalan** [intercom/intercom-android#273]
## Version info
  - Intercom for Android version: 3.0.10
  - Android OS version: 6.0
  - Android Device: Nexus 5X AVD

## Expected behavior
Based on the current [documentation](https://docs.intercom.com/using-transitive-dependencies-with-intercom-for-android), switching the FCM dependency with this should work:

```
compile ('io.intercom.android:intercom-sdk-fcm:3.+') {
    exclude group 'io.intercom.android', module: 'intercom-sdk-base'
}
```

## Actual behavior
The above snippet throws this error:
```
Error:(174, 0) Cause: startup failed:
build file '/app/build.gradle': 174: expecting '}', found ',' @ line 174, column 40.
       exclude group 'io.intercom.android', module: 'intercom-sdk-base'
```

Is this the correct syntax? I am on Android Studio 2.2.1 and gradle 2.2.1.

**Comment by subzthanabalan** [comment]
I was able to get this working by updating the syntax to this:
```
compile ('io.intercom.android:intercom-sdk-fcm:3.0.10') {
    exclude(group: 'io.intercom.android', module: 'intercom-sdk-base')
  }
```

**Comment by ronocod** [comment]
Thanks for letting us know about this, I've updated the docs to use the following snippet which also works:
```groovy
compile('io.intercom.android:intercom-sdk-fcm:3.+') {
    exclude group: 'io.intercom.android', module: 'intercom-sdk-base'
}
```
