### ISSUE TITLE
Unable to receive push messages

### ISSUE THREAD

**Issue by fabianbergmark** [intercom/intercom-android#274]
## Version info
- Intercom for Android version: 3.0.10
- Android OS version: 6.0.1
- Android Device: Samsung Galaxy S6 Edge +
## Expected behavior

Push notifications sent from Intercom should display an Android notification
## Actual behavior

com.google.android.gms.gcm.GcmReceiver receives an intent but IntercomGcmListenerService.onMessageReceived is never called. I have double checked that the intercom_sender_id is correct. I can see that IntercomGcmRegistrationService.onHandleIntent is called.
## Steps to reproduce

I have made some modifications to Intercoms receivers/services in my manifest:

<service
            android:name="io.intercom.android.sdk.gcm.IntercomGcmRegistrationService"
            android:process=":ui" />
        <service
            android:name="io.intercom.android.sdk.gcm.IntercomGcmListenerService"
            android:process=":ui" />
        <service
            android:name="io.intercom.android.sdk.gcm.IntercomGcmRefreshService"
            android:process=":ui" />

```
    <receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:process=":ui" >
```

That might be the root of the issue. I also have another GCMReceiver from MixPanel

```
<receiver
        android:name="com.mixpanel.android.mpmetrics.GCMReceiver"
        android:permission="com.google.android.c2dm.permission.SEND">
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

            <category android:name="io.flic.app" />
        </intent-filter>
    </receiver>
```

But that should not be an issue?

**Comment by DaleCantwell** [comment]
Its very possible that mix panel has a listener service which is consuming our push. Is it possible to subclass their GcmListenerService and then pass the intent on as described in our push setup doc:
https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/enable-push-notifications-with-intercom-for-android-gcm

**Step 7. Using Intercom with other GCM setups (Optional)**

This only applies to applications that also use GCM for their own content, or use a third party service for GCM. You’ll need to update the your GcmListenerService and the class where you generate your device token.

You should have a class that generates a push device token and sends it to your backend. In addition to sending the token to your backend you will need to forward it to Intercom, like this:
```JAVA
private final IntercomPushClient intercomPushClient = new IntercomPushClient();

public void onHandleIntent(Intent intent) {     
    InstanceID instanceId = InstanceID.getInstance(this);
    String senderId = "YOUR_SENDER_ID";
    String token = instanceId.getToken(senderId,
        GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
    pushClient.sendTokenToIntercom(getApplication(), token);
}
```

You should have a class that extends GcmListenerService. That service will consume pushes intended for Intercom. To allow us to draw the Intercom push set up your GcmListenerService, like this:
```JAVA
private final IntercomPushClient intercomPushClient = new IntercomPushClient();

public void onMessageReceived(String from, Bundle message) {
    if (intercomPushClient.isIntercomPush(message)) {
        intercomPushClient.handlePush(getApplication(), message);
    } else {
        //DO HOST LOGIC HERE
    }
}
```

**Comment by ronocod** [comment]
@fabianbergmark did you manage to get this resolved?

**Comment by fabianbergmark** [comment]
Sorry for the late reply: Yes I set up my own GCM listeners and route messages to the correct handler. Works great

**Comment by ronocod** [comment]
Great! 😄
