### ISSUE TITLE
New message bubble appears below WebView using cordova-intercom plugin

### ISSUE THREAD

**Issue by chris-armstrong** [intercom/intercom-android#275]
## Version info
- Intercom for Android version: 3.0.10 (cordova-intercom 3.0.12)
- Android OS version: 6
- Android Device: S7
## Expected behavior

Intercom messaging bubble on new messages shows on top of view hierarchy.
## Actual behavior

We're seeing the Intercom messaging bubble appear below our WebView on Cordova (using the intercom-cordova plugin). We use the cordova-plugin-googlemaps plugin to render a map, so our WebView is actually transparent (which might be triggering this behaviour).

Is there a way to control where the messaging bubble is inserted into the hierarchy?

**Comment by ronocod** [comment]
There is no way to control the position of the bubble in the hierarchy right now.

We have an issue in the Cordova repo for this, you might find some useful information there: https://github.com/intercom/intercom-cordova/issues/46

**Comment by chris-armstrong** [comment]
Thanks 

Is there any information on how it is added to the view hierarchy? My assumption would have been that is always would be positioned on top.

**Comment by ronocod** [comment]
It's positioned in the front level of the active `Activity` in Android, but it's possible that Cordova is adding the WebView in front of the bubble there.

**Comment by ronocod** [comment]
Are you still experiencing this issue? If so it'd be great if you could file this as a bug on the [intercom-cordova](https://github.com/intercom/intercom-cordova) repo.

**Comment by ronocod** [comment]
This should be reopened on the [intercom-cordova](https://github.com/intercom/intercom-cordova) repo if it's still an issue.
