### ISSUE TITLE
android.os.DeadObjectException

### ISSUE THREAD

**Issue by Digisha** [intercom/intercom-android#279]
We are getting following crash in our app:

## Version info
  - Intercom for Android version: 3.0.8
  - Android OS version: 6.0, 6.0.1, 5.1
  - Android Device: LGUS375, SM-G920R4, XT1093

## Logs
[crash.txt](https://github.com/intercom/intercom-android/files/578317/crash.txt)

**Comment by ronocod** [comment]
We've implemented a fix for this, I'll post an update here when it's released.

**Comment by ronocod** [comment]
Fixed in 3.0.12 🎉
