### ISSUE TITLE
java.lang.NullPointerException: SystemSettings.java

### ISSUE THREAD

**Issue by Digisha** [intercom/intercom-android#280]
We are getting following crash in our app

## Version info
  - Intercom for Android version: 3.0.8
  - Android OS version: 6.0.1, 5.1
  - Android Device: SM-G930R4, SM-G920R4, XT1093

## Actual behavior
App crashes

## Logs
[NPE_crash.txt](https://github.com/intercom/intercom-android/files/578336/NPE_crash.txt)

**Comment by ronocod** [comment]
We've implemented a fix for this, I'll post an update here when it's released.

**Comment by ronocod** [comment]
Fixed in 3.0.12 🎉
