### ISSUE TITLE
InboxFragment NullPointerException

### ISSUE THREAD

**Issue by oiramcro** [intercom/intercom-android#282]
App crashes after we call Intercom.client().displayMessenger(), seems like something is null inside displayEmptyView method of InboxFragment.

  - Intercom for Android version:
  - Android OS version: 4.4.2
  - Android Device: Galaxy S4 Mini 

**crashlytics link:**
http://crashes.to/s/d351800573b

**Comment by ronocod** [comment]
We have a fix implemented for this, will release it today.

**Comment by ronocod** [comment]
Fixed in 3.0.12 🎉

**Comment by shaibar** [comment]
@ronocod still happens in 3.0.17

**Comment by ronocod** [comment]
@shaibar can you post your full stacktrace please?
