### ISSUE TITLE
Unable to integrate into a project with targetSdkVersion=22

### ISSUE THREAD

**Issue by alexblack** [intercom/intercom-android#286]
Snippet from `build.gradle`

```
android {
    compileSdkVersion 22
    buildToolsVersion 25.0.0

   defaultConfig {
        minSdkVersion 15
        targetSdkVersion 22
    }
}

dependencies {
  compile 'io.intercom.android:intercom-sdk:3.+'
}
```

Gives me error on compile:

```
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
```

on

```
/Users/alex/dev/is/android-app/android-app/app/build/intermediates/res/merged/freeX86/debugCustom/values-v23/values-v23.xml
```

This seems to be this issue: http://stackoverflow.com/questions/8590521/error-retrieving-parent-for-item-no-resource-found-that-matches-the-given-name

**Comment by alexblack** [comment]
If I change `minSdkVersion` to `15` from `9` the problem persists.

**Comment by alexblack** [comment]
It looks like bumping `compileSdkVersion` to `23` solves the issue with what looks like minimal impact

**Comment by ronocod** [comment]
Your `compileSdkVersion` should usually be the newest possible version, you can keep your `targetSdkVersion` lower if you want. There's a good article that explains the two [here](https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd#.w85gkijod).
