### ISSUE TITLE
"Unable to load conversations" displayed on the screen for a few minutes when you open app for the first time.

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#29]
"Unable to load conversations" displayed on the screen for a some minutes when you open app for the first time.

![](http://content.screencast.com/users/Vika_Kalikh/folders/Snagit/media/07c6fa41-cc94-46de-a47c-9e38dc7217ad/12.23.2014-15.15.png)

**Comment by DaleCantwell** [comment]
@emakovsky this is typically experienced if the API is experiencing some slow down. We have since changed our behavior so we now display a progress wheel while this is loading.

**Comment by ambermore** [comment]
Hi, 

I am facing same issue, is anyone have any solution for this?
