### ISSUE TITLE
Proguard Error -  io.intercom.android.sdk.utilities.HtmlCompat: can't find referenced method

### ISSUE THREAD

**Issue by sriram-kakarala** [intercom/intercom-android#291]
## Version info
  - Intercom for Android version: io.intercom.android:intercom-sdk-base:3.+
  - Android OS version: All
  - Android Device: All
  - ProGuard, version 5.2.1

## Expected behavior
Issue while compiling.
Proguard throws up the following warning,
Warning: io.intercom.android.sdk.utilities.HtmlCompat: can't find referenced method 'android.text.Spanned fromHtml(java.lang.String,int)' in library class android.text.Html

## Steps to reproduce
1.  Use compileSdkVersion 23 & buildToolsVersion '23.0.2'

**Comment by ronocod** [comment]
Can you try this using `compileSdkVersion 24`? We recommend not using older versions.

**Comment by RKSharma89** [comment]
Not even working with compileSdkVersion 24

**Comment by alexblack** [comment]
I have this problem too, using compileSdkVersion 23 and buildToolsVersion 25.0.0, worked around it with

`-dontwarn io.intercom.android.sdk.utilities.**`

**Comment by sriram-kakarala** [comment]
Yes agree to alexblack , I finally had to add the proguard.

**Comment by ronocod** [comment]
Thanks, we'll include this Proguard rule in our next version and I'll update here when that's released.

**Comment by ronocod** [comment]
This rule is included in 3.0.15.
