### ISSUE TITLE
Sample code - set avatar image_url, company custom attributes

### ISSUE THREAD

**Issue by alexblack** [intercom/intercom-android#293]
Hi, I can't find any sample code for:

1. Setting the avatar `image_url`
2. Updating an existing company with custom attributes

I've tried the obvious, and although my user custom parameters are working, and the company gets created, the avatar does not show up, nor do my company custom attributes.

```
final Map<String, Object> avatar = new HashMap<>();
avatar.put("image_url", logo.getUrl());
avatar.put("type", "avatar");
user.put("avatar", avatar);
Intercom.client().updateUser(user);
```

```
final Map<String, Object> company = new HashMap<>();
final Map<String, Object> companyCustom = new HashMap<>();
company.put("id", account.getObjectId());
company.put("custom_attributes", companyCustom);
companyCustom.put("currency", settings.getLocaleCurrency().getCode());
companyCustom.put("lang", settings.getLocaleLanguage().getCode());
final List<Map<String, Object>> companies = new ArrayList<>();
companies.add(company);
user.put("companies", companies);
Intercom.client().updateUser(user);
```

**Comment by ronocod** [comment]
Can you check the Account Info tab for that company in Intercom? Sometimes new custom attributes can take a short while to appear.

Are you using a HTTPS URL for your avatar image? This is a requirement as noted here: https://developers.intercom.com/reference#section-avatar-object. We'll do some work to improve the documentation around user attributes updating.

**Comment by alexblack** [comment]
Thanks for responding. The company custom attributes have not shown up.  Could you guys post some sample code on how to set company attributes?

Yes, the avatar url was HTTPS.  It has since shown up, after a long delay.

**Comment by ronocod** [comment]
We tested the code you posted above, it seems to be correct as we saw the custom attributes appear on the company after a few minutes. This sounds like it could be a server-side issue, so you'd probably be better off contacting our support team through Intercom.

**Comment by alexblack** [comment]
Some sample code would still be helpful, I had to guess on how to do it, and intercom support team wasn't sure either.

I've been talking to intercom support for 2 days now.

**Comment by DaleCantwell** [comment]
@alexblack while it is possible to update the avatar it is currently unsupported which is why we don't have it in our docs. This model https://developers.intercom.com/reference#section-attributes lists all the fully supported fields that can be updated. You will still be able to update the avatar but the behaviour may change, if there are any major changes coming such as officially supporting updatable avatars I'll update this issue.

Regarding custom attributes, it is confusing that they an be added in two places. We are looking into a solution to make this much easier to work with. As it currently stands I recommend using the following approach for company custom attributes:

```JAVA
Map<String, Object> userMap = new HashMap<>();

Map<String, Object> companyData = new HashMap<>();
List<Map<String, Object>> companies = new ArrayList<>();
Map<String, Object> customCompanyData = new HashMap<>();

companyData.put("name", "My Company");
companyData.put("id", "abcd1234");

customCompanyData.put("team_mates", 8);
customCompanyData.put("monthly_spend", 155.98);
companyData.put("custom_attributes", customCompanyData);

companies.add(companyData);
userMap.put("companies", companies);
Intercom.client().updateUser(userMap);
```
I have added the above snippet to our Javadoc and it will be released with the next update.
Thanks

**Comment by alexblack** [comment]
Thanks!  

Also, your docs don't mention `user.remote_created_at`, is that also unsupported? That was the only way I could find to set the user created date.

**Comment by DaleCantwell** [comment]
created_at should work for that. There are actually a couple differences between the model I linked and the mobile set. I will look to publish a definitive mobile set of attributes soon.

**Comment by alexblack** [comment]
I wasn't able to get `created_at` to work

**Comment by DaleCantwell** [comment]
@alexblack could you send on the code you are using to update the created_at.

**Comment by DaleCantwell** [comment]
Sample code is now included, I'm going to close this issue. @alexblack could you open a new issue if you are still unable to update created_at and we will look into that.
