### ISSUE TITLE
Received Intercom notification from different user after account change

### ISSUE THREAD

**Issue by Nutomic** [intercom/intercom-android#294]
## Version info
  - Intercom for Android version: 3.0.14
  - Android OS version: Android 6.0.1
  - Android Device: SM-G930L

## Expected behavior
After logout and call to `Intercom.client().reset()`, there should be no more messages received for that user.

## Actual behavior
After logging out of the first account, logging into a second, and back into the first, you can receive messages for the second account.

We use `Intercom.client().registerIdentifiedUser(Registration.create().withEmail(user.email));` for login, and ``Intercom.client().reset()` for logout.

## Steps to reproduce
1. log in with my id
2. logout and login with other peoples id
3. logout and login with my id
4. now I can see other peoples intercom notifications

## Logs

**Comment by ronocod** [comment]
Are you talking about in-app notifications or push notifications?

**Comment by Nutomic** [comment]
It was an in-app notification.

**Comment by ronocod** [comment]
Can you contact our support team about this through Intercom? This sounds like an integration issue.
