### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alashow** [intercom/intercom-android#297]
I was testing Intercom and randomly I got memory leak notification.

LeakCanary info: https://gist.github.com/alashow/969acee443f8be940737638030e4b6a0

My device info is included in there and I'm using intercom-android 3.0.17.

**Comment by alashow** [comment]
I don't know what I'm doing wrong, but I got more different leaks now.

https://imgur.com/gallery/Wv8kw

**Comment by ronocod** [comment]
The first leak there looks like there's a Runnable in the queue that hasn't been executed yet, we'll investigate just to be sure.

The second one looks you're adding an UnreadConversationCountListener but not removing it then, are you calling `removeUnreadConversationCountListener()` anywhere?

**Comment by alashow** [comment]
oh, then that's my bad. I remember it from the tutorial but forgot to implement.

Thank you

**Comment by alashow** [comment]
@ronocod I have one activity (`MainActivity`) with fragments (with bottombar). I register my listener in `MainActivity` but leak happens inside even if I don't open any other activities. 

Currently, I register a listener on `onCreate` but I don't know where to unregister it. What is the recommended approach?

**Comment by alashow** [comment]
I tried adding listener on `onResume` and removing it on `onDestroy`. Didn't work, it's still leaking.

**Comment by ronocod** [comment]
Can you try adding it in `onResume` and removing it in `onPause`?

**Comment by FranciscoE-Hudl** [comment]
Can confirm:

![device-2017-01-17-160301](https://cloud.githubusercontent.com/assets/11388931/22028251/862ab11e-dcce-11e6-8461-8253ef939a04.png)

**Comment by ronocod** [comment]
The memory leak from the `MessageQueue` is fixed in 3.0.19.
