### ISSUE TITLE
initialize off the main thread

### ISSUE THREAD

**Issue by andrei-egeniq** [intercom/intercom-android#299]
Your injector/gson/API is taking too long, so in previous versions I did Intercom.initialize on another thread. 

You have added ResetManager that breaks my first hacks by using a Handler.

Please use new Handler(Looper.getMainLooper()) so it does not matter what thread is used to start Intercom.

If you fix the startup time, that would be better.

## Version info
  - Intercom for Android version: 3.0.17
  - Android OS version: All
  - Android Device: All

## Expected behavior

Intercom.initialize works on new thread

## Actual behavior

Intercom.initialize fails on a new thread

**Comment by DaleCantwell** [comment]
@andrei-egeniq thank you for reporting the issue. We will release an updated version of the SDK with the fix to allow initialization off the main thread again.

**Comment by alexblack** [comment]
+1

**Comment by DaleCantwell** [comment]
The release https://github.com/intercom/intercom-android/releases/tag/3.0.18 has this fix.
