### ISSUE TITLE
No "add conversation" button in the header

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#30]
There is no "adding conversation" button on the header some times.

Unfortunatily it happens randomly and I can't provide any details.

![](http://content.screencast.com/users/Vika_Kalikh/folders/Snagit/media/06e06b13-2bc9-42ac-a6f8-9bd86d6886a6/12.23.2014-15.29.png)

**Comment by DaleCantwell** [comment]
@emakovsky thanks for reporting this issue. It was caused by an issue with the order of the configuration call. This has been fixed and we will be available in the beta update which we will release ASAP.
