### ISSUE TITLE
Sharp edges in texts and circles in the UI

### ISSUE THREAD

**Issue by nikolaevmaks** [intercom/intercom-android#303]
Looks very awful :( 

<img width="416" alt="1" src="https://cloud.githubusercontent.com/assets/2562836/21913050/ed0980aa-d93a-11e6-9319-d51c4a313b70.png">
<img width="428" alt="2" src="https://cloud.githubusercontent.com/assets/2562836/21913052/ef863fda-d93a-11e6-9516-a1ef1cbd3361.png">
<img width="416" alt="3" src="https://cloud.githubusercontent.com/assets/2562836/21913054/f16d8394-d93a-11e6-8744-e09c0d97cc40.png">
<img width="420" alt="4" src="https://cloud.githubusercontent.com/assets/2562836/21913057/f386ce06-d93a-11e6-9830-2365fbfa67f9.png">

Please use antialiasing.

## Version info
  - Intercom for Android version: 3.0.18
  - Android OS version: 7.1.1
  - Android Device: Nexus 5X

**Comment by ronocod** [comment]
This will be fixed in our next update, we'll let you know when it's released.

**Comment by ronocod** [comment]
Fixed in 3.0.19.
