### ISSUE TITLE
What integer should I set for Intercom.setLogLevel()?

### ISSUE THREAD

**Issue by KeithYokoma** [intercom/intercom-android#306]
`IntercomLogger` is removed in 3.0.19 but Javadoc of `Intercom.setLogLevel()` still says that integer should be defined in `IntercomLogger`.

Could you give me some upgrade instructions?

## Version info
  - Intercom for Android version: 3.0.19

**Comment by DaleCantwell** [comment]
Hi @KeithYokoma 
The docs will be updated in 3.0.20. Sorry for any inconvenience. You can use the standard Android Log levels. For example:

```
        Intercom.setLogLevel(VERBOSE);
```
Where VERBOSE is

```
import static android.util.Log.VERBOSE;
```

3.0.20 will reintroduce IntercomLogger but marking it as deprecated with the replacement being described in the docs.

**Comment by ronocod** [comment]
These constants have been reintroduced in 3.0.20, but are now deprecated in favour of the constants in the `Intercom.LogLevel` class.

**Comment by KeithYokoma** [comment]
I see. Thanks for quick replying!
