### ISSUE TITLE
Crash when receiving push notification for new FCM integration

### ISSUE THREAD

**Issue by mikewadhera** [intercom/intercom-android#307]
Add push notifications to an existing android app thats using Google Play Services, Firebase and Intercom. We wish to enable push notifications so our customers can see new replies without having the app running.

## Version info
  - Intercom for Android version: io.intercom.android:intercom-sdk-base:3.+
  - Android OS version: 6.0.1
  - Android Device: Samsung Galaxy S7

## Expected behavior

Receive push notification

## Actual behavior

Crash

java.lang.AbstractMethodError: abstract method "android.content.Intent com.google.firebase.iid.zzb.zzF(android.content.Intent)"
  at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4063)

## Steps to reproduce
 1. Integrate FCM push notifications following setup guide
 2. Reply to thread from Resolve web UI

## build.gradle

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:cardview-v7:25.+'
    testCompile 'junit:junit:4.12'
    compile project(':standOut')
    compile 'com.google.android.gms:play-services-vision:10.0.1'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-polly:2.3.4'
    compile 'org.apache.commons:commons-collections4:4.1'
    compile 'com.github.tony19:timber-loggly:1.0.1'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.google.firebase:firebase-crash:10.0.1'
    compile 'uk.co.chrisjenx:calligraphy:2.2.0'
    compile 'io.intercom.android:intercom-sdk-base:3.+'
    compile 'io.intercom.android:intercom-sdk-fcm:3.+'
}

apply plugin: 'com.google.gms.google-services'

**Comment by skylerwshaw** [comment]
@mikewadhera Have you ensured that Intercom is receiving the Intercom push notifications first per?: https://developers.intercom.com/docs/android-fcm-push-notifications#section-step-7-using-intercom-with-other-fcm-setups-optional

If you are using multiple push providers, it's necessary to extend `FirebaseMessagingService` class, conditionally checking for Intercom push at the top level:
```
private final IntercomPushClient intercomPushClient = new IntercomPushClient();

public void onMessageReceived(RemoteMessage remoteMessage) {
    Map message = remoteMessage.getData();
    if (intercomPushClient.isIntercomPush(message)) {
        intercomPushClient.handlePush(getApplication(), message);
    } else {
        //DO HOST LOGIC HERE
    }
}
```

The above will ensure that Intercom push is appropriately handled by the SDK, and the rest fall through to your other integrations without interference.

**Comment by mikewadhera** [comment]
Thanks @skylerwshaw - I will look into this. This is the first time we're integrating any time of push notifications into the app so we're not using any other push providers. But we do use Firebase Core SDK for managing content. Assuming that means we need to follow step 7?

**Comment by ronocod** [comment]
Yes, you'll probably need to follow step 7. If you're still seeing crashes after that then it might be that you're using a newer version of the Firebase libraries than us (we're using 9.8). I'll take a look at updating our SDK to use the latest version.

**Comment by ronocod** [comment]
Version 3.1.0 uses the latest version of the Firebase library (10.2.0), can you try upgrading to that?

**Comment by mikewadhera** [comment]
Confirm fixed. Thanks. It's unfortunate of the codependence but I guess needed for FCM. For our future releases, is there a way to upgrade Firebase without upgrading Intercom?

**Comment by mikewadhera** [comment]
Also FYI we *did not* need to extend FirebaseMessagingService as instructed in Step 7

**Comment by ronocod** [comment]
It's hard to predict how well newer Firebase dependencies will work when used with other older ones. We try to keep our versions up to date, but we also try not to update our versions too soon after a release as that can cause problems too.

Generally the safest method is to use the same Firebase version across all Firebase dependencies, and file an issue here if we're taking too long to update 🙂

**Comment by MattyK14** [comment]
@mikewadhera what did you do?
