### ISSUE TITLE
Message will not be send after disconnecting and connecting to Internet.

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#31]
Steps:
1. Open any conversation.
2. Disconnect the Internet connection.
3. Send any message.
-> Message appear in the list marked "Tap to retry". 

4. Connect the Internet connection.

-> The message do not sent. When you close this conversation and open again this message do not displayed in the list.

Comment: No possibility to view conversations and add messages without the Internet connection.

**Comment by GavinRooney** [comment]
The fix for the second part of this will require offline mode to be finished. This is one of the features being worked on this month. https://github.com/intercom/intercom-android/issues/34
I will update this when we have a version with offline mode ready for you

**Comment by adamkmccarthy** [comment]
We're tracking this on the product roadmap internally at #23723
