### ISSUE TITLE
intercom_bottom_padding for multiple messages

### ISSUE THREAD

**Issue by Belozerow** [intercom/intercom-android#311]
## Version info
  - Intercom for Android version: 3.0.21
  - Android OS version: 7.0
  - Android Device: Samsung galaxy s7

## Expected behavior
From release notes:
Added an xml public padding field to allow users to alter the position of the Intercom FAB and in-apps if it is blocking host app FABs #231 To update the position simply add this to your dimens.xml with the value you want to move up using:
`<dimen name="intercom_bottom_padding">74dp</dimen>`

## Actual behavior
1. When user receives multiple messages from intercom, first message appears as expected. But the second in app message has bottom padding = `2*intercom_bottom_padding.`
The third one has bottom padding = `3*intercom_bottom_padding`
etc.

2. When you send note messages after chat messages. App shows chat messages in the expected area and note messages below them in the default position in the bottom of the screen.

## Steps to reproduce
 1. Override intercom_bottom_padding in dimens.xml with 132dp
 2. Send multiple messages to user from https://app.intercom.io
 3. To reproduce second part, you could send note message after chat message.

**Comment by WarmongeR1** [comment]
+1

**Comment by DaleCantwell** [comment]
Thanks for reporting the issue, I have fixed this and it will be part of our release next week. I will update and close the issue once that is shipped.

**Comment by ronocod** [comment]
Fixed in 3.1.1.
