### ISSUE TITLE
Cannot add dependencies on gradle

### ISSUE THREAD

**Issue by luisreja** [intercom/intercom-android#312]
## Version info
  - Intercom for Android version: 3.0.21
  - Android OS version: compileSdkVersion 23
  - Android Device: not relevant

## Expected behavior
When added dependencies to gradle the sync may be correct.

## Actual behavior
Cannot sync with gradle after add dependencies. They show multiple errors like p.e:

Error:(17, 22) No resource found that matches the given name (at 'src' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

All the errors are from drawable resources, Its is like cannot finish sync and do not generate R class.

## Steps to reproduce
 1. Add dependencies in gradle:
compile 'io.intercom.android:intercom-sdk-base:3.+'
compile 'io.intercom.android:intercom-sdk-fcm:3.+'
 2. Sync project with gradle files
 3. Show errors.

My gradle file:

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

apply plugin: 'android-apt'

def AAVersion = '3.3.1'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "es.medianet.lolamarket"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 17
        versionName "1.4.6"
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
    }
    signingConfigs {
        debug {
        }

        release {
            storeFile file("../lolaProduction.jks")
            keyAlias "lolaproduction"
            storePassword System.getenv("keystore_pass")
            keyPassword System.getenv("keystore_pass")
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.debug
            debuggable true
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'io.intercom.android:intercom-sdk-base:3.0.21'
    compile 'io.intercom.android:intercom-sdk-fcm:3.0.21'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    compile 'com.facebook.android:facebook-android-sdk:4.8.1'

    compile project(':common')
    compile project(':logger')
    compile project(':domain')
    compile project(':data')
    compile project(':dialogfragments')
    compile project(':viewPagerIndicator')
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.10.19'
    testCompile 'org.robolectric:robolectric:3.0'
    /*FOR TABLET DESIGN*/
    //compile 'com.nineoldandroids:library:2.4.0+'
    compile('com.github.florent37:materialviewpager:1.1.0@aar') {
        transitive = true
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.5.2@aar') {
        transitive = true;
    }

}

apt {
    arguments {
        //noinspection GroovyAssignabilityCheck
        androidManifestFile variant.outputs[0].processResources.manifestFile
    }
}

**Comment by ronocod** [comment]
Can you update your `compileSdkVersion` to 25 and your `buildToolsVersion` to 25.0.2?

**Comment by luisreja** [comment]
I'm afraid it is not working, I had excluded the compile lines from gradle in the test (my fault, so sorry). 
@ronocod  can you give me any additional tips?

**Comment by ronocod** [comment]
Once you're using `compileSdkVersion 25` and `buildToolsVersion "25.0.2"` can you try updating your support library version to 25.0.1?

**Comment by luisreja** [comment]
Same result, when i sync with gradle files, show errors.
I had tried also with the transitive versions: compile 'io.intercom.android:intercom-sdk-base-transitive:3.+'
    compile('io.intercom.android:intercom-sdk-fcm:3.+') {
        exclude group: 'io.intercom.android', module: 'intercom-sdk-base'
    }

but no results

**Comment by ronocod** [comment]
Based on [this](http://stackoverflow.com/a/35720612) it looks like you're referencing `@drawable/abc_ic_ab_back_mtrl_am_alpha` somewhere in your code and you need to change the reference to `@drawable/abc_ic_ab_back_material`

**Comment by luisreja** [comment]
Dear @ronocod,sorry for the delay, after a hard work to update my app to sdk 25, and all versions of tools and support libraries, is finally working. Thank you for your attention.
