### ISSUE TITLE
Unable to swipe multiple unread messages

### ISSUE THREAD

**Issue by guyga** [intercom/intercom-android#313]
Hey,
When i'm sending multiple messages and open the app, i'm only able to swipe the top message.
After that the rest of the unread messages stays on the screen without the ability to swipe.
Is it a known issue? do you know if it's a side effect of something i might be doing wrong?
Thanks.

## Version info
  - Intercom for Android version: 3.0.21
  - Android OS version: 6.0.1
  - Android Device: Galaxy Note 4

## Expected behavior
being able to swipe all the unread messages

## Actual behavior
able to swipe the first unread message, the rest are still visible on the screen but can't be swiped

## Steps to reproduce
 1. Send from the dashboard 2-3 messages
 2. Open the app
 3. all 3 messages are one on top of the other, after swiping the first one, the rest are still appear on  the screen without the ability to swipe

**Comment by skylerwshaw** [comment]
@guyga This is not a known issue and we've tested across multiple devices and builds and sending a minimum of 3 messages each time to a build of our test app in this repo. Each time we're able to swipe the messages off individually. This appears to be something local to your app. Are you manipulating views in any way?

You may want to download our [sample app](https://github.com/intercom/intercom-android/tree/master/samples), embed your Intercom app_id and API key, load, and send yourself messages to see the correct behavior and structure of our app. Let us know if you find anything, as we're more than willing to help out. Have you tried this in another app, a different screen, etc?

**Comment by guyga** [comment]
Hey,
I'm not manipulating views, and i've tried on different fragments/activities.
I also tried on a new app and the issue remains.
Moreover - I tried on the sample app: intercom-sample-fcm and the issue remains...
And i've tried on multiple devices - LG G3, Galaxy Note 4, OnePlus One
and all devices experiencing this issue.

Since it happens also in the sample app i really don't know what causes it and how i'm the only one experiencing it

**Comment by ronocod** [comment]
@guyga are you still experiencing this issue? If so can you try and reproduce it with no cable plugged in to the device, and can you enable [Show Touches](https://medium.theuxblog.com/enabling-show-touches-in-android-screen-recordings-for-user-research-cc968563fcb9) when recording the video?

**Comment by ronocod** [comment]
Closing this as we haven't been able to reproduce it, will re-open if it can be reproduced.
