### ISSUE TITLE
Force closing and reopening app causes app to no longer receive push notifications

### ISSUE THREAD

**Issue by jasonblood** [intercom/intercom-android#317]
## Version info
  - Intercom for Android version: 3.0.21 (I also tried updating to 3.1.0 but issue still remains)
  - Android OS version: 5.0.1
  - Android Device: Samsung Galaxy S4 (Model number: GT-I9506)

## Expected behavior
When user is registered and device token is sent to intercom we should receive notifications. Then if app is fully closed down (e.g not backgrounded) and user then launches app again user should still keep receiving push notifications.

## Actual behavior
When user logs into app the notifications are working as expected. But when app is force closed and then reopened we never receive any more notifications.

## Steps to reproduce
Note we are still using GCM to send push notifications at the minute.
1. So when user logs into our app we register with Intercom and then also we send their device token to Intercom via the SDK. 
2. So then if I background the app and send myself a message via Intercom I receive a push notification and this displays and works as expected. If I then force close the app (not background) and send myself another message I still get the push notification. 
3. But then when the app is launched again after being closed I no longer receive push notifications while the app is in the background.

Note when we relaunch the app the user is still in a logged in state from their previous session (in terms of my sites login) so when app is then launched  and user is logged in we use Intercom SDK to register user with id again.  I have tried multiple things when the app is launching with a user logged in to see if I can start receiving the push notifications again. E.g  enable / disable the intercom registration call when app is launched. Send push device token each time app is launched. But I still do not get any push notifications when app is launched. The only way to restore the notifications working again is to log out in our app and log in again. When we log out we call `Intercom.client().reset()` and then when we log back in we register the logged in user with Intercom using their user id again. We also send the device token again to Intercom. 

If I use the FCM diagnostics console to view messages sent to the device token, I can see that messages that I had received on the device appear here. But after I close and reopen the app I can see that no further messages have been sent to GCM.

**Comment by jasonblood** [comment]
Any updates on this ? Was hoping to send some of our users some push notifications this week. But are holding off too see what the deal is with this issue.

**Comment by ronocod** [comment]
Sorry for the delay here, are there any errors in the device logs related to this?

Also does your app receive its own push notifications through GCM too?

**Comment by jasonblood** [comment]
Hi, So I don't see anything in the logs regarding any errors. Also yes we handle our own notifications too. Although we are not using any third party service for this.

**Comment by ronocod** [comment]
Small update, still investigating this and trying to reproduce it. The issue may be related to the integration with your own push implementation. Will post any updates here.

**Comment by jasonblood** [comment]
Cool just another update on this. So I decided to try close the app and then comment out all of the intercom SDK calls regarding initialising the SDK. And then relaunched the app. When I did this I was still getting the push notifications to the device.  So then I re added the call to `Intercom.initialize(Application application, String apiKey, String appId) ` closed and relaunched the app. Once I call this method I no longer receive pushes.

**Comment by ronocod** [comment]
Are you always calling `initialize()` with the same API key and App ID or are they changing between builds?

It may also help to call `Intercom.setLogLevel(Intercom.LogLevel.DEBUG)` as early as possible in your app to get more detailed logs.

**Comment by jasonblood** [comment]
Here is the log that we get when relaunching an app. Also the API key / app ID change if its a production vs debug builds. But in this case I am always running on a debug build and using our Intercom Sandbox.

```03-22 11:40:29.973 4567-4567/com.distilledmedia.adverts I/Intercom: Intercom has already been initialized
03-22 11:40:30.253 4567-4567/com.distilledmedia.adverts I/Intercom: Enabling GCM for cloud messaging
03-22 11:40:30.253 4567-4567/com.distilledmedia.adverts I/Intercom: Unregistering for later initialization
03-22 11:40:30.253 4567-4567/com.distilledmedia.adverts I/DebugIntercomModule: Intercom initialized
03-22 11:40:31.374 4567-4567/com.distilledmedia.adverts I/Intercom: Started observing com.distilledmedia.adverts.MainActivity@3ef45e18
03-22 11:40:31.384 4567-4567/com.distilledmedia.adverts W/Intercom realtime: No realtime endpoints present so we can't connect
03-22 11:40:31.384 4567-4567/com.distilledmedia.adverts I/Intercom: Dispatched Action: APP_ENTERED_FOREGROUND: 1490182831381
03-22 11:40:31.745 4567-4567/com.distilledmedia.adverts I/Intercom: Failed to register user. We already have a registered user. If you are attempting to register a new user, call reset() before this.
03-22 11:40:32.706 4567-4567/com.distilledmedia.adverts I/LoginManager: User id 645656 registered with Intercom
03-22 11:40:33.757 4567-4567/com.distilledmedia.adverts I/Intercom: Dispatched Action: ACTIVITY_READY_FOR_VIEW_ATTACHMENT: com.distilledmedia.adverts.MainActivity@3ef45e18
03-22 11:40:33.757 4567-4567/com.distilledmedia.adverts I/Intercom: Ready to show in-app messages in com.distilledmedia.adverts.MainActivity@3ef45e18
03-22 11:40:34.037 4567-4567/com.distilledmedia.adverts I/Intercom: Successfully registered or updated user
03-22 11:40:34.067 4567-4567/com.distilledmedia.adverts I/Intercom: Dispatched Action: BASE_RESPONSE_RECEIVED: io.intercom.android.sdk.models.UpdateUserResponse@3b1f51c7
03-22 11:40:34.157 4567-4567/com.distilledmedia.adverts I/Intercom: Dispatched Action: UNREAD_CONVERSATIONS_SUCCESS: io.intercom.android.sdk.models.UpdateUserResponse@3b1f51c7
03-22 11:40:34.157 4567-4567/com.distilledmedia.adverts I/Intercom: Dispatched Action: TEAM_PRESENCE_UPDATED: io.intercom.android.sdk.models.TeamPresence@87f219d2
03-22 11:40:35.068 4567-5266/com.distilledmedia.adverts I/Intercom realtime: adding socket
03-22 11:40:35.078 4567-5266/com.distilledmedia.adverts D/Intercom realtime: connecting to a socket...
03-22 11:40:35.078 4567-5266/com.distilledmedia.adverts I/Intercom realtime: adding socket
03-22 11:40:35.078 4567-5266/com.distilledmedia.adverts D/Intercom realtime: connecting to a socket...
03-22 11:40:35.939 4567-5294/com.distilledmedia.adverts D/Intercom realtime: notifying listeners that a connection opened
03-22 11:41:24.646 4567-5293/com.distilledmedia.adverts D/Intercom realtime: notifying listeners that a connection opened ```

**Comment by skylerwshaw** [comment]
Resolved in Intercom. Was a mismatched declaration of `intercom_gcm_sender_id` in the res/values/strings.xml file.
