### ISSUE TITLE
Sometimes conversations with messages do not saved after closing for the first time.

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#32]
Steps:
1. Open new conversation.
2. Send any message.
-> Message was sent successfully.
3. Close this conversation.

-> There is no conversations in the list. (some times for the first time)

**Comment by DaleCantwell** [comment]
@emakovsky this looks like a problem with us maintaining state between a conversation and the inbox. We will look into this issue and prepare a fix for the next update.

**Comment by DaleCantwell** [comment]
@emakovsky this issue has been fixed in version 0.9.0. I would recommend updating as soon as possible. Thanks again for reporting it.
