### ISSUE TITLE
Unable to scroll articles

### ISSUE THREAD

**Issue by jlmcdonnell** [intercom/intercom-android#321]
## Version info
  - Intercom for Android version:
  - Android OS version:
7, 6, 5
  - Android Device:
Pixel, S7 Edge, Galaxy Note 4

## Expected behavior
Articles should easily scroll

## Actual behavior
Articles do not scroll correctly, sometimes taking 4/5 attempts.

## Steps to reproduce
 1. Send a user an article that does not fit the screen (so that they will need to scroll down when opening it in the messenger
 2. Attempt to scroll the article.

**Please see attached video demonstrating issue:**

[intercom-scroll-issue.zip](https://github.com/intercom/intercom-android/files/847833/intercom-scroll-issue.zip)

**Comment by ronocod** [comment]
Are you doing anything in your app which might be interfering with the view hierarchy? We haven't been able to reproduce this at all.

**Comment by jlmcdonnell** [comment]
@ronocod Weirdly enough, we can't reproduce this either on any of those devices. I don't currently have the time to go through the changes that caused it to work again, but it's probably fair to say it's something on our end.
