### ISSUE TITLE
Intercom new message UI under the System Bars

### ISSUE THREAD

**Issue by bmoliveira** [intercom/intercom-android#322]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.1.0
  - Android OS version: 7.1
  - Android Device: Pixel C

## Expected behavior

The UI from intercom should appear above the system bars when the App supports fullscreen experience

## Actual behavior

The UI is under the System bars

## Steps to reproduce
 1. Open the app
 2. Send intercom message to show in-app

## Logs

![intercom under system ui](https://cloud.githubusercontent.com/assets/1921410/24111927/ed547068-0d8f-11e7-965e-0939649377c3.png)

**Comment by DaleCantwell** [comment]
Hi @bmoliveira, in your `dimens.xml` you can add `intercom_bottom_padding` with whatever padding you want to move the in apps above the translucent bar eg.
`<dimen name="intercom_bottom_padding">48dp</dimen>`
Let us know if that is not solving the issue for you.
Thanks

**Comment by bmoliveira** [comment]
Thanks, I didn't saw that option. Will fix this with the padding. But for Android versions that don't have software Keyboard, the view will appear with 48dp+ of bottom padding. 

Is there any other way to add the padding programmatically?

**Comment by DaleCantwell** [comment]
Hi @bmoliveira 
We have just added in 3.2.2 a method setBottomPadding()
I think that will provide a better solution than the xml attribute as it can be changed during the apps lifecycle

**Comment by bmoliveira** [comment]
Nice add! This way is a lot more customizable. Thank you @DaleCantwell
