### ISSUE TITLE
"No resource found" compile errors

### ISSUE THREAD

**Issue by astichternath** [intercom/intercom-android#327]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.1.2
  - Android OS version:
  - Android Device:

## Expected behavior

Compiles without errors

## Actual behavior

Compiles with resource errors

## Steps to reproduce
 1. Embbed intercom-sdk-base-3.1.2.aar
 2. Compile app

## Logs

No resource found that matches the given name (at 'layout_marginBottom' with value '@dimen/intercom_composer_activity_margin').
No resource found that matches the given name (at 'layout_marginEnd' with value '@dimen/intercom_composer_activity_margin').
No resource found that matches the given name (at 'layout_marginRight' with value '@dimen/intercom_composer_activity_margin').
No resource found that matches the given name (at 'background' with value '@drawable/intercom_composer_circular_ripple').
No resource found that matches the given name (at 'layout_height' with value '@dimen/intercom_composer_toolbar_with_status_bar_height').
No resource found that matches the given name (at 'background' with value '@color/intercom_composer_full_screen_toolbar').
No resource found that matches the given name (at 'fitsSystemWindows' with value '@bool/intercom_composer_fits_system_windows').
No resource found that matches the given name (at 'paddingTop' with value '@dimen/intercom_composer_toolbar_content_offset').
No resource found that matches the given name (at 'layout_height' with value '@dimen/intercom_composer_toolbar_with_status_bar_height').
No resource found that matches the given name (at 'background' with value '@color/intercom_composer_full_screen_toolbar').
No resource found that matches the given name (at 'fitsSystemWindows' with value '@bool/intercom_composer_fits_system_windows').
No resource found that matches the given name (at 'paddingTop' with value '@dimen/intercom_composer_toolbar_content_offset').

**Comment by ronocod** [comment]
What `compileSdkVersion` and Android Build Tools version are you using?

**Comment by astichternath** [comment]
compileSdkVersion: 23
Android Build Tools: 23.0.3

**Comment by skylerwshaw** [comment]
@astichternath, You should use be using version 25 for both of these. Can you please ensure you're using an updated Android Studio environment and that your project is set for `compileSdkVersion` and Build Tools of 25? Updating your Android Studio software and opening your project should automatically prompt you to update this.

**Comment by astichternath** [comment]
No, that fix not the problem.
I embbed the Lib with the local downloaded aar file:
compile(name: 'intercom-sdk-base-3.1.2', ext: 'aar')

With compile 'io.intercom.android:intercom-sdk:3.+' it works.
But in this Project, I must embbed it with the local file.

If you decompile the arr with JD-GUI, there is no resouce in the values.xml for example for
@dimen/intercom_composer_activity_margin.

**Comment by ronocod** [comment]
Can you also download the .aar files from [here](https://bintray.com/intercom/intercom-maven/download_file?file_path=com%2Fintercom%2Fandroid-composer%2F1.0.2%2Fandroid-composer-1.0.2.aar) and [here](https://bintray.com/intercom/intercom-maven/download_file?file_path=com%2Fintercom%2Fandroid-composer-gallery%2F1.0.2%2Fandroid-composer-gallery-1.0.2.aar) we'll look into a better way to support this in future.

**Comment by astichternath** [comment]
Now it work's! Thanks!
