### ISSUE TITLE
 Ask questions、Help、Help

### ISSUE THREAD

**Issue by fuzhengchao** [intercom/intercom-android#328]
@ronocod In Last year, there is a crash in your project, https://github.com/intercom/intercom-android/issues/255。now i meet this crash in my app , I wish to chat with you about this crash，and hope get a help。

**Comment by jtreanor** [comment]
Hi @fuzhengchao,

Our support team would be happy to help you with any issues you are having (contact them via the Messenger on [https://intercom.com](intercom.com).

If you believe the crash you are seeing is being caused by Intercom, please provide a crash log so we can help you with the issue.

**Comment by fuzhengchao** [comment]
Thanks very much。I meet this crash is not caused by Intercom。This is a crash in my own app and has the same crash log with that crash ，but I cannot find the reason。so I hope ask for some help to resolve this crash 。
