### ISSUE TITLE
Google Play Services 6.5 Dependency

### ISSUE THREAD

**Issue by marcoRS** [intercom/intercom-android#33]
I noticed you now require Google Play Services as a dependency. The way the README explains to include it is by adding:

        compile 'com.google.android.gms:play-services:6.5.87'

I'd imagine this includes all Apis however in version 6.5 Google introduced selective dependencies where you can choose specific Apis rather than everything. This helps avoid 65K method limit and makes the apk slimmer. Are all the Apis needed for Intercom or can we be more selective about the dependencies? 

Individual dependencies now have the form: 

       com.google.android.gms:play-services-plus:6.5.+      // Google+
       com.google.android.gms:play-services-identity:6.5.+  // Google Account Login
etc... 

The rest can be seen here: http://developer.android.com/google/play-services/setup.html

**Comment by brianmuse** [comment]
I think only the base lib is needed for push notifications:
`compile 'com.google.android.gms:play-services-base:6.5.87'`

**Comment by DaleCantwell** [comment]
Thank you for the feedback. We have made the change to use play-services-base in our new version which we will be shipping ASAP. This will also decrease our impact on the dex limit.
