### ISSUE TITLE
Cannot Build Package With 3.1.2

### ISSUE THREAD

**Issue by brandonfuller** [intercom/intercom-android#330]
I am attempting to use your AAR inside an Appcelerator/Titanium project.  They currently do not have support but it should be coming in a future release.  This would enable anyone building on this platform to hopefully be able to use Intercom, once a module is developed.

https://jira.appcelerator.org/browse/TIMOB-18565

I have been trying to build such a module but I am running into an issue trying package up your resources with AAPT.  This is what Appcelerator will be doing via that pull request/branch I gave you above so I was getting a head start.

The problem is that AAPT fails because of a bunch of missing resource definitions.  I have grepped your code a bunch of times but I just cannot find a definitions for these.  Things like:

+ intercom_composer_toolbar_content_offset
+ intercom_composer_fits_system_windows
+ intercom_composer_full_screen_toolbar

I see them in the R.txt file.  I see them in the XML files.  But I do not seem them defined in values.xml or elsewhere.  Which is why the build error is happening.

So bottom line...can you help guide me as to why you have definitions with no values in your resources for this package?

## Logs

Brandons-Mac-Pro:res Brandon$ /Users/Brandon/Documents/LocalCounsel/android-sdk-macosx/build-tools/25.0.2/aapt "package" "-f" "-m" "-J" "/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/gen" "-M" "/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/AndroidManifest.xml" "-A" "/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/bin/assets" "-S" "/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res" "-I" "/Users/Brandon/Documents/LocalCounsel/android-sdk-macosx/platforms/android-23/android.jar" "-F" "/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/bin/app.ap_" "--output-text-symbols" "/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/intermediates/bundles" "--auto-add-overlay" "--extra-packages" "ti.modules.titanium.ui:android.support.v7.appcompat:android.support.v7.cardview"
/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:4: error: No resource identifier found for attribute 'expanded' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:6: error: No resource identifier found for attribute 'layout_scrollFlags' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:8: error: No resource identifier found for attribute 'layout_collapseMode' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:10: error: No resource identifier found for attribute 'layout_collapseMode' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:14: error: No resource identifier found for attribute 'layout_behavior' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:18: error: No resource identifier found for attribute 'layout_behavior' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:23: error: No resource identifier found for attribute 'layout_behavior' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:25: error: No resource identifier found for attribute 'layout_behavior' in package 'com.localcounselcollective.mobile.iphone.localcounsel'

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:14: error: Error: No resource found that matches the given name (at 'layout_behavior' with value '@string/appbar_scrolling_view_behavior').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:18: error: Error: No resource found that matches the given name (at 'layout_behavior' with value '@string/appbar_scrolling_view_behavior').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:23: error: Error: No resource found that matches the given name (at 'layout_behavior' with value '@string/appbar_scrolling_view_behavior').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_conversation_coordinator.xml:25: error: Error: No resource found that matches the given name (at 'layout_behavior' with value '@string/appbar_scrolling_view_behavior').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_expander_button.xml:2: error: Error: No resource found that matches the given name (at 'layout_marginBottom' with value '@dimen/intercom_composer_activity_margin').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_expander_button.xml:2: error: Error: No resource found that matches the given name (at 'layout_marginEnd' with value '@dimen/intercom_composer_activity_margin').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_expander_button.xml:2: error: Error: No resource found that matches the given name (at 'layout_marginRight' with value '@dimen/intercom_composer_activity_margin').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_expander_button.xml:2: error: Error: No resource found that matches the given name (at 'background' with value '@drawable/intercom_composer_circular_ripple').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gallery_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'layout_height' with value '@dimen/intercom_composer_toolbar_with_status_bar_height').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gallery_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'background' with value '@color/intercom_composer_full_screen_toolbar').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gallery_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'fitsSystemWindows' with value '@bool/intercom_composer_fits_system_windows').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gallery_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'paddingTop' with value '@dimen/intercom_composer_toolbar_content_offset').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gif_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'layout_height' with value '@dimen/intercom_composer_toolbar_with_status_bar_height').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gif_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'background' with value '@color/intercom_composer_full_screen_toolbar').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gif_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'fitsSystemWindows' with value '@bool/intercom_composer_fits_system_windows').

/Users/Brandon/Documents/Appcelerator_Studio_Workspace/Attorney/build/android/res/layout/intercom_gif_input_toolbar.xml:2: error: Error: No resource found that matches the given name (at 'paddingTop' with value '@dimen/intercom_composer_toolbar_content_offset').

**Comment by ronocod** [comment]
You'll need the AAR files from [here](https://bintray.com/intercom/intercom-maven/android-composer/1.0.2) and [here](https://bintray.com/intercom/intercom-maven/android-composer-gallery/1.0.2) as well. I'll add these to this repo now.

**Comment by brandonfuller** [comment]
Thanks.  Those helped remove 1/2 the errors.

The rest seem to be because the Intercom libraries use some of the most recent com.android.support libraries and Titanium has locked down to much earlier versions.  If anyone else is in this situation, more over there:

https://jira.appcelerator.org/browse/TIMOB-18565

**Comment by twustep** [comment]
I've been experiencing the same issues you have been trying to get Titanium/Android to work with latest Intercom. With the help of @minhnc and Joel from Intercom I've gotten past the 'No resource found that matches' errors but now have these type of errors:

> Attribute "[ATTRIBUTE NAME]" already defined with incompatible format.

This is where I am running the test application:

https://bitbucket.org/boatyard/boatyardhyperloop

Take a look at the app/platform/android and all the aars that I've included. That seemed to help with the original 'No resource found that matches' errors. 

I think now it is a matter of one of those libraries including same attribute names and causing it to fail. I can provide more details if you need.

**Comment by brandonfuller** [comment]
Thanks for writing.  Glad to hear there are more people in my boat.  

I am not using Hyperloop so my stuff is a bit different.

I actually added all those AARs last night and that got me much further.  But my problem now is that Appcelerator is locked to version 23 of the Android Support Library (where all those AARs come from) and Intercom is using version 25.  So the two don't mix.  I get duplicate resource exceptions and stuff.

There is an Appcelerator bug on this but it has no progress yet.  This might be exactly what you need as well to get it working:
https://jira.appcelerator.org/browse/TIMOB-24446

But there is no solution today.  Let me know if you find one.

**Comment by twustep** [comment]
Thanks for all the details. It looks like indeed we are stuck until Titanium includes version 25. And from what you are mentioning, it is not a Hyperloop specific problem. Even if we tried the old fashion module way, it wont work. I knew something was not right when I could not find a fork of someone adapting Intercom's 3.1.2 SKD into a module. Now we know the reason why. 

I'll see if I can keep hacking away, but as you mention, I think the best bet is to wait for higher Android support.
