### ISSUE TITLE
Duplicated session on first registration of a user (identified or not)

### ISSUE THREAD

**Issue by Nescafemix** [intercom/intercom-android#337]
## Version info
  - Intercom for Android version: 3.1.5
  - Android OS version: 7.0
  - Android Device: s7Edge

## Expected behavior
The first time the user open the app and login on it, we initialize an intercom tracker and register the user. From the intercom website, we should see the number of android sessions is increased in 1. 
## Actual behavior
The number of android sessions is increased in 2.
## Steps to reproduce
 1. with the app closed and no user logged on the ap, open the app. 
 2. After the login process, register for intercom with:
````
Intercom.initialize((Application)context, androidApiKey, appId);
Intercom.setLogLevel(Intercom.LogLevel.VERBOSE);
Intercom.client().setLauncherVisibility(Intercom.Visibility.GONE);
Registration registration = Registration.create().withUserId(userId).withEmail(email);
Intercom.client().registerIdentifiedUser(registration);
````
## Considerations
1. The call to initialize Intercom is not being duplicated (single call).
2. The call to register user is not being duplicated (single call).
3. Once the user is registered, if the app is killed and opened again, a single session is increased so, it is working properly. The problem is detected the first time a user is registered in a just opened app without session opened previously.

## Update!
I did some tests registering for intercom in the onCreate of Application even if the user is not logged (with registerUnidentifiedUser), and the same behaviour happens. The first time is executed the call to initialize intercom and register user(identified or not) after install the app (clean install)) the number of sessions is increased in 2 instead of in 1. The next time the app is opened, the number of sessions is increased in 1 (as it should be), even if it was killed from the system.
It seems that a duplicated registration of the user is done if there is no internal data about the user. With an UnidentifiedUser, it happens only the first time the app is opened, but with IdentifiedUser happens always if you don't register for unidentifiedUsers and you perform an Intercom.client().reset() with the logout process. I hope that helps

## Logs
````
12:53:40.478 6817-6817/****I/Intercom: Dispatched Action: SET_LAUNCHER_VISIBILITY: GONE
12:53:40.662 6817-6817/****I/Intercom: Dispatched Action: ACTIVITY_PAUSED: ****.presentation.startup.UpdateActivity@5ba3afc
12:53:40.663 6817-6817/****I/Intercom: ****.presentation.startup.UpdateActivity@5ba3afc was paused
12:53:40.797 6817-6817/****I/Intercom: Started observing ****.presentation.dashboard.DashboardActivity@c0fa4b
12:53:40.797 6817-6817/****W/Intercom realtime: No realtime endpoints present so we can't connect
12:53:40.891 6817-6817/****I/Intercom: Dispatched Action: APP_ENTERED_FOREGROUND: 1492685620797
12:53:41.928 6817-6817/****I/Intercom: Successfully registered or updated user
12:53:41.930 6817-6817/****I/Intercom: Dispatched Action: BASE_RESPONSE_RECEIVED: io.intercom.android.sdk.models.UpdateUserResponse@54f4fea
12:53:41.931 6817-6817/****I/Intercom: Dispatched Action: UNREAD_CONVERSATIONS_SUCCESS: io.intercom.android.sdk.models.UpdateUserResponse@54f4fea
12:53:41.931 6817-6817/****I/Intercom: Dispatched Action: TEAM_PRESENCE_UPDATED: io.intercom.android.sdk.models.TeamPresence@3e4959ae
12:53:41.947 6817-6817/****I/Intercom: Dispatched Action: ACTIVITY_READY_FOR_VIEW_ATTACHMENT: ****.presentation.dashboard.DashboardActivity@c0fa4b
12:53:41.948 6817-6817/****I/Intercom: Ready to show in-app messages in ****.presentation.dashboard.DashboardActivity@c0fa4b
12:53:42.073 6817-6817/****I/Intercom: Stopped observing ****.presentation.startup.UpdateActivity@5ba3afc
12:53:42.085 6817-6817/****I/Intercom: Dispatched Action: ACTIVITY_STOPPED: ****.presentation.startup.UpdateActivity@5ba3afc
12:53:42.215 6817-6817/****I/Intercom: Successfully registered or updated user
12:53:42.216 6817-6817/****I/Intercom: Dispatched Action: BASE_RESPONSE_RECEIVED: io.intercom.android.sdk.models.UpdateUserResponse@c9996d
12:53:42.217 6817-6817/****I/Intercom: Dispatched Action: UNREAD_CONVERSATIONS_SUCCESS: io.intercom.android.sdk.models.UpdateUserResponse@c9996d
12:53:42.217 6817-6817/****I/Intercom: Dispatched Action: TEAM_PRESENCE_UPDATED: io.intercom.android.sdk.models.TeamPresence@b3a6fbc7
12:53:43.217 6817-11996/****I/Intercom realtime: Adding socket
12:53:43.222 6817-11996/****D/Intercom realtime: connecting to a socket...
12:53:43.233 6817-11996/****I/Intercom realtime: Adding socket
12:53:43.233 6817-11996/****D/Intercom realtime: connecting to a socket...
12:53:43.742 6817-12082/****D/Intercom realtime: notifying listeners that a connection opened
12:53:43.770 6817-12080/****D/Intercom realtime: notifying listeners that a connection opened

````

**Comment by skylerwshaw** [comment]
Hey @Nescafemix, thank you for the report. We're taking a look at this and will get back to you shortly!

**Comment by DaleCantwell** [comment]
@Nescafemix thank you for the details in the issue. We were able to reproduce it and we have a fix in place. The next release of the Android SDK will ship this fix. I'll update this issue once it's live.

**Comment by DaleCantwell** [comment]
3.2.1 just shipped with a fix for this issue. Let me know if you have issues with it.
