### ISSUE TITLE
Auto messages being sent twice

### ISSUE THREAD

**Issue by JaerenMoneyBox** [intercom/intercom-android#352]
## Version info
  - Intercom for Android version: 3.2.2
  - Android OS version: 7.1.1 (but isn't version specific)
  - Android Device: Android emulator Nexus 5x

## Expected behavior

We have an intercom user auto message to be sent after a user sets up a pin lock on their account for the first time, using the event submitted_pin, immediately after this the user is sent to another screen where we send another event called account_viewed that has no auto messages attached to it.  

What we would like to happen is for the message to only be shown once after the user submits their pin and when they land on the next screen.

## Actual behavior

After we send both these events and the user lands on the second screen the user is shown two auto messages.  After the user dismisses the first one, they are still shown the same message and have to dismiss the second one.

However we do not see this behaviour if we remove the "account_viewed" event, or if we set the auto message to be fired on the "account_viewed" event (i.e. the second event).

## Steps to reproduce
 1. Identify anonymous user - Intercom.client().registerUnidentifiedUser();
 2. User logs in - Intercom.client().registerIdentifiedUser(Registration.create().withUserId(userId));
 3. Go to first screen (create pin)
 4. Create pin - Intercom.client().logEvent("submitted_pin");
 5. Go to second screen - Intercom.client().logEvent("account_viewed");
 6. While still on the second screen we are shown two auto messages.

## Logs

**Comment by ronocod** [comment]
Looking into a fix for this now.

**Comment by chuen-mb** [comment]
+1

**Comment by ronocod** [comment]
Fixed in 3.2.4.
