### ISSUE TITLE
Is we need to add SYSTEM_ALERT_WINDOW runtime permission for Android M and above versions while using Intercom ?

### ISSUE THREAD

**Issue by peddiraju211** [intercom/intercom-android#353]
## Version info
  - Intercom for Android version: 3.2.0
  - Android OS version: 6.0.1
  - Android Device: SM-T580

**Comment by ronocod** [comment]
No, there is no need to use that permission to use Intercom.

**Comment by peddiraju211** [comment]
Is there any suggestion, for by default enable this permission without user prompt while installing app first time ?

**Comment by ronocod** [comment]
You should be able to find more information on how to do that here: https://stackoverflow.com/questions/36016369/system-alert-window-how-to-get-this-permission-automatically-on-android-6-0-an

**Comment by peddiraju211** [comment]
@ronocod Thank you
