### ISSUE TITLE
pre populate message composer with attachement

### ISSUE THREAD

**Issue by pandorgithub** [intercom/intercom-android#356]
Is it possible to open the message composer with pre populated attachement?

This could be handly in cases we want the customer to contact us with something specific that happens in the app.

**Comment by DaleCantwell** [comment]
Hi @pandorgithub 
This is not currently possible. What sort of attachments are you thinking about here?

**Comment by DaleCantwell** [comment]
If you are looking to pre populate the composer with text you can do that with the following method
```
Intercom.client().displayMessageComposer(message);
```

It is available the following release: since https://github.com/intercom/intercom-android/releases/tag/3.0.9

**Comment by pandorgithub** [comment]
in my case, its a picture. But could be any other type of file that could be useful for customer support.

**Comment by ronocod** [comment]
Are you hoping to prepopulate with the picture using a Bitmap or a Uri for a file?

**Comment by DaleCantwell** [comment]
@pandorgithub I'm going to close out this issue and track it internally as a feature request. Thanks for getting in touch with us.
