### ISSUE TITLE
v3.2.4 build failed: String types not allowed (at 'configChanges' with value 'orientation|screenLayout|density|screenSize').

### ISSUE THREAD

**Issue by enginebai** [intercom/intercom-android#357]
## Version info
  - Intercom for Android version: 3.2.4
  - Android OS version: any
  - Android Device: any

## Expected behavior
Gradle build successfully

## Actual behavior
Gradle build failed

## Steps to reproduce
 1. Use v3.2.4
 2. Build or run app in Android Studio

## Logs
Gradle build log
```
.../app/build/intermediates/manifests/full/prod/debug/AndroidManifest.xml
Error:(399, 36) String types not allowed (at 'configChanges' with value 'orientation|screenLayout|density|screenSize').
```

* `debug/AndroidManifest.xml` error line
<img width="1121" alt="2017-06-01 4 55 12" src="https://cloud.githubusercontent.com/assets/3387462/26672281/31d62206-46eb-11e7-96a2-d982eeecdd0f.png">

**Comment by ronocod** [comment]
Can you tell us what values you are using for:
* `compileSdkVersion`
* `targetSdkVersion`
* `buildToolsVersion`
* `minSdkVersion`
* Your `com.android.tools.build:gradle` version

**Comment by enginebai** [comment]
* compileSdkVersion 23
* buildToolsVersion "23.0.3"
* minSdkVersion 16
* targetSdkVersion 23
* com.android.tools.build:gradle 2.2.3

**Comment by enginebai** [comment]
We downgrade to 3.2.3 and everything works as usual.

**Comment by ronocod** [comment]
Can you update your `compileSdkVersion` to 25 and your `buildToolsVersion` to 25.0.2? Your `compileSdkVersion` should [always be set to the latest released version](https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd).

**Comment by ronocod** [comment]
Closing this, if the problem persists with the latest versions I mentioned above we can reopen.
