### ISSUE TITLE
New setUserHash() leads to hmac_mismatch error for some users

### ISSUE THREAD

**Issue by ivacf** [intercom/intercom-android#358]
We are using Identity Verification in our app. We were previously using the `setSecureMode(token userID)` method to send the user hash to Intercom. This was working without problems. After updating the Intercom SDK to the to the latest version, I noticed this method was deprecated so I replaced it with `setUserHash()`. This was working fine for most user. However, once we released the new version of our Android app, we started seeing reports of some user not being able to access Intercom anymore.

After some investigation, this is what I found:
* A small percentage of users get the following error log `{"code":"hmac_mismatch","message":"Failed Identity Verification check"}`, even though we are calling `setUserHash()` with a valid hash. Therefore they are not able to access Intercom.
* If we replace `setUserHash()` with the deprecated method `.setSecureMode(token, userId)` this error disappear and they are able to access Intercom again.
 

## Version info
  - Intercom for Android version: 3.2.0+
  - Android OS version: Any
  - Android Device: Any

## Expected behavior
Calling `registerIdentifiedUser(Registration.create().withUserId(userId))` and `setUserHash(hash)` would allow **all** users to access the previous Intercom conversations and send new messages. 

## Actual behavior
After calling the two methods above, a percentage of our users cannot access Intercom anymore and see an error screen when trying to load the list of conversations.  

## Logs
This is the log I can see for those users that are experiencing the problem 
```
Failed to register or update user: {"type":"error.list","request_id":"{id_here}","errors":[{"code":"hmac_mismatch","message":"Failed Identity Verification check"}]}
```

We will continue using `setSecureMode()` until we find out the cause of this issue.

**Comment by DaleCantwell** [comment]
Hi @ivacf 
Is the data you are hashing **user_id** or **email**? We now require the data being hashed to be one of those two fields.
Is it possible that `setSecureMode(token, userId)` was ever not sending us the same userId as provided to Intercom?

**Comment by ivacf** [comment]
We are hashing the user ID. 

I can confirm that the user ID we send to `setSecureMode(token, userId)` is always the same that we pass to `registerIdentifiedUser(Registration.create().withUserId(userId))`

We always call `registerIdentifiedUser()` first, and then `setSecureMode()`/`seUserHash()`. Is that the correct order or it doesn't matter?

**Comment by jtreanor** [comment]
Hi @ivacf,

I have had a quick look at what is happening here and it looks like there may be an issue with how user ID is set on your users. Rather than discussing your user data publicly I will send you a message through Intercom so we can help resolve this.

James

**Comment by ronocod** [comment]
Closing, this is an issue with this particular integration, not an issue with the Messenger.
