### ISSUE TITLE
Automatic filling of user model....

### ISSUE THREAD

**Issue by sirvon** [intercom/intercom-android#36]
is any data automatically added to the user model ?
or 
Does ALL data have to be supplied?

For instance all the data thats easily obtained from the android device
such as advertisingId, os version, country, stuff like that most libraries add that stuff.

Intercom's model is intensive, I just want to make sure I dont go ham and supply all
that data when/if the system is already supplying some from the device.

**Comment by DaleCantwell** [comment]
We add the following automatically
Build.CPU_ABI
Build.MODEL
Locale.getDefault().getDisplayLanguage()

We also send up the version and name of the host application and the version of the Intercom Android SDK.
