### ISSUE TITLE
Support for Android O notification channels?

### ISSUE THREAD

**Issue by MiralDesai** [intercom/intercom-android#363]
## Version info
  - Intercom for Android version: 3.1.5
  - Android OS version: N/A
  - Android Device: N/A

I'm currently working on getting our app supported for Android O that is due to be released in August. One feature is [notification channels](https://developer.android.com/preview/features/notification-channels.html) which allow users to block specific types of push notifications.

Due to way the intercom handles push notifications in the SDK (taking my GCM sender ID and controlling everything related to the notification) I really have no control over supporting this feature with regards to intercom.

So my question, are you guys going to support it? I feel like it needs to happen. It will avoid user's blocking all notifications if they are annoyed with messages coming via intercom. It's also becoming a standard Android feature going forward.

**Comment by DaleCantwell** [comment]
Hi @MiralDesai 
Thanks for contacting us. We are investigating notification channels and other Android O features in our SDK. We will definitely call out any notification channels support in our change log and make sure any changes to push functionality are updated in our docs.
I'm going to close out this issue and move to our internal feature requests.
