### ISSUE TITLE
Memory leak in IntercomMessengerActivity

### ISSUE THREAD

**Issue by Amagi82** [intercom/intercom-android#368]
## Version info
  - Intercom for Android version: 3.2.4
  - Android OS version: 7.1.1
  - Android Device: Nexus 6

## Actual behavior
LeakCanary found a memory leak

## Steps to reproduce
I navigated to Intercom using Intercom.client().displayMessenger() and then quickly returned. I got this to happen twice and then couldn't repeat it after that. Network connection was weak at the time.

## Logs

> D/LeakCanary: * io.intercom.android.sdk.activities.IntercomMessengerActivity has leaked:
D/LeakCanary: * GC ROOT thread java.lang.Thread.<Java Local> (named 'AsyncTask #10')
D/LeakCanary: * references android.os.AsyncTask$SerialExecutor$1.this$1 (anonymous implementation of java.lang.Runnable)
D/LeakCanary: * references android.os.AsyncTask$SerialExecutor.mTasks
D/LeakCanary: * references java.util.ArrayDeque.elements
D/LeakCanary: * references array java.lang.Object[].[8]
D/LeakCanary: * references android.os.AsyncTask$SerialExecutor$1.val$r (anonymous implementation of java.lang.Runnable)
D/LeakCanary: * references android.widget.TextView$3.this$0 (anonymous implementation of java.lang.Runnable)
D/LeakCanary: * references android.support.v7.widget.AppCompatEditText.mContext
D/LeakCanary: * leaks io.intercom.android.sdk.activities.IntercomMessengerActivity instance
D/LeakCanary: * Retaining: 6.0 KB.
D/LeakCanary: * Reference Key: 961b84b6-bd33-4579-a815-0017b7cbb66b
D/LeakCanary: * Device: motorola google Nexus 6 shamu
D/LeakCanary: * Android Version: 7.1.1 API: 25 LeakCanary: 1.5.1 1be44b3
D/LeakCanary: * Durations: watch=159666ms, gc=190ms, heap dump=8893ms, analysis=97905ms
D/LeakCanary: * Details:
D/LeakCanary: * Instance of java.lang.Thread
D/LeakCanary: |   static MAX_PRIORITY = 10
D/LeakCanary: |   static MIN_PRIORITY = 1
D/LeakCanary: |   static threadInitNumber = 41
D/LeakCanary: |   static NORM_PRIORITY = 5
D/LeakCanary: |   static $classOverhead = byte[224]@1883715401 (0x70473749)
D/LeakCanary: |   static NANOS_PER_MILLI = 1000000
D/LeakCanary: |   static SUBCLASS_IMPLEMENTATION_PERMISSION = java.lang.RuntimePermission@1883713552 (0x70473010)
D/LeakCanary: |   static threadSeqNumber = 34888
D/LeakCanary: |   static defaultUncaughtExceptionHandler = com.google.firebase.crash.FirebaseCrash$zzc@314930048 (0x12c57380)
D/LeakCanary: |   static EMPTY_STACK_TRACE = java.lang.StackTraceElement[0]@1883713536 (0x70473000)
D/LeakCanary: |   blocker = null
D/LeakCanary: |   blockerLock = java.lang.Object@314578408 (0x12c015e8)
D/LeakCanary: |   contextClassLoader = dalvik.system.PathClassLoader@314665424 (0x12c169d0)
D/LeakCanary: |   daemon = false
D/LeakCanary: |   eetop = 0
D/LeakCanary: |   group = java.lang.ThreadGroup@1883713368 (0x70472f58)
D/LeakCanary: |   inheritableThreadLocals = null
D/LeakCanary: |   inheritedAccessControlContext = java.security.AccessControlContext@314578400 (0x12c015e0)
D/LeakCanary: |   lock = java.lang.Object@314578416 (0x12c015f0)
D/LeakCanary: |   name = java.lang.String@317627840 (0x12ee9dc0)
D/LeakCanary: |   nativeParkEventPointer = 0
D/LeakCanary: |   nativePeer = 2249049856
D/LeakCanary: |   parkBlocker = null
D/LeakCanary: |   parkState = 1
D/LeakCanary: |   priority = 5
D/LeakCanary: |   single_step = false
D/LeakCanary: |   stackSize = 0
D/LeakCanary: |   started = true
D/LeakCanary: |   stillborn = false
D/LeakCanary: |   target = java.util.concurrent.ThreadPoolExecutor$Worker@317627936 (0x12ee9e20)
D/LeakCanary: |   threadLocalRandomProbe = 0
D/LeakCanary: |   threadLocalRandomSecondarySeed = 0
D/LeakCanary: |   threadLocalRandomSeed = 0
D/LeakCanary: |   threadLocals = java.lang.ThreadLocal$ThreadLocalMap@317326336 (0x12ea0400)
D/LeakCanary: |   threadQ = null
D/LeakCanary: |   threadStatus = 0
D/LeakCanary: |   tid = 34830
D/LeakCanary: |   uncaughtExceptionHandler = null
D/LeakCanary: |   shadow$_klass_ = java.lang.Thread
D/LeakCanary: |   shadow$_monitor_ = 0
D/LeakCanary: * Instance of android.os.AsyncTask$SerialExecutor$1
D/LeakCanary: |   static $classOverhead = byte[56]@1888555497 (0x709111e9)
D/LeakCanary: |   this$1 = android.os.AsyncTask$SerialExecutor@315471792 (0x12cdb7b0)
D/LeakCanary: |   val$r = android.os.AsyncTask$3@317034464 (0x12e58fe0)
D/LeakCanary: |   shadow$_klass_ = android.os.AsyncTask$SerialExecutor$1
D/LeakCanary: |   shadow$_monitor_ = 0
D/LeakCanary: * Instance of android.os.AsyncTask$SerialExecutor
D/LeakCanary: |   static $classOverhead = byte[60]@1888057329 (0x708977f1)
D/LeakCanary: |   mActive = android.os.AsyncTask$SerialExecutor$1@317260944 (0x12e90490)
D/LeakCanary: |   mTasks = java.util.ArrayDeque@315481896 (0x12cddf28)
D/LeakCanary: |   shadow$_klass_ = android.os.AsyncTask$SerialExecutor
D/LeakCanary: |   shadow$_monitor_ = 0
D/LeakCanary: * Instance of java.util.ArrayDeque
D/LeakCanary: |   static serialVersionUID = 2340985798034038923
D/LeakCanary: |   static $classOverhead = byte[233]@1883917505 (0x704a4cc1)
D/LeakCanary: |   static MIN_INITIAL_CAPACITY = 8
D/LeakCanary: |   static -assertionsDisabled = true
D/LeakCanary: |   elements = java.lang.Object[16]@315708928 (0x12d15600)
D/LeakCanary: |   head = 14
D/LeakCanary: |   tail = 10
D/LeakCanary: |   shadow$_klass_ = java.util.ArrayDeque
D/LeakCanary: |   shadow$_monitor_ = 0
D/LeakCanary: * Array of java.lang.Object[]
D/LeakCanary: |   [0] = android.os.AsyncTask$SerialExecutor$1@315442016 (0x12cd4360)
D/LeakCanary: |   [1] = android.os.AsyncTask$SerialExecutor$1@315441744 (0x12cd4250)
D/LeakCanary: |   [2] = android.os.AsyncTask$SerialExecutor$1@315441408 (0x12cd4100)
D/LeakCanary: |   [3] = android.os.AsyncTask$SerialExecutor$1@315473024 (0x12cdbc80)
D/LeakCanary: |   [4] = android.os.AsyncTask$SerialExecutor$1@315472368 (0x12cdb9f0)
D/LeakCanary: |   [5] = android.os.AsyncTask$SerialExecutor$1@317998736 (0x12f44690)
D/LeakCanary: |   [6] = android.os.AsyncTask$SerialExecutor$1@315944032 (0x12d4ec60)
D/LeakCanary: |   [7] = android.os.AsyncTask$SerialExecutor$1@315943984 (0x12d4ec30)
D/LeakCanary: |   [8] = android.os.AsyncTask$SerialExecutor$1@317764608 (0x12f0b400)
D/LeakCanary: |   [9] = android.os.AsyncTask$SerialExecutor$1@317764576 (0x12f0b3e0)
D/LeakCanary: |   [10] = null
D/LeakCanary: |   [11] = null
D/LeakCanary: |   [12] = null
D/LeakCanary: |   [13] = null
D/LeakCanary: |   [14] = android.os.AsyncTask$SerialExecutor$1@317352256 (0x12ea6940)
D/LeakCanary: |   [15] = android.os.AsyncTask$SerialExecutor$1@317352224 (0x12ea6920)
D/LeakCanary: * Instance of android.os.AsyncTask$SerialExecutor$1
D/LeakCanary: |   static $classOverhead = byte[56]@1888555497 (0x709111e9)
D/LeakCanary: |   this$1 = android.os.AsyncTask$SerialExecutor@315471792 (0x12cdb7b0)
D/LeakCanary: |   val$r = android.widget.TextView$3@317764624 (0x12f0b410)
D/LeakCanary: |   shadow$_klass_ = android.os.AsyncTask$SerialExecutor$1
D/LeakCanary: |   shadow$_monitor_ = 0
D/LeakCanary: * Instance of android.widget.TextView$3
D/LeakCanary: |   static $classOverhead = byte[56]@320965697 (0x13218c41)
D/LeakCanary: |   this$0 = android.support.v7.widget.AppCompatEditText@321468416 (0x13293800)
D/LeakCanary: |   shadow$_klass_ = android.widget.TextView$3
D/LeakCanary: |   shadow$_monitor_ = 0
D/LeakCanary: * Instance of android.support.v7.widget.AppCompatEditText
D/LeakCanary: |   static $classOverhead = byte[3956]@321007617 (0x13223001)
D/LeakCanary: |   mBackgroundTintHelper = android.support.v7.widget.AppCompatBackgroundHelper@318818592 (0x1300c920)
D/LeakCanary: |   mTextHelper = android.support.v7.widget.AppCompatTextHelperV17@319376728 (0x13094d58)
D/LeakCanary: |   mAllowTransformationLengthChange = false
D/LeakCanary: |   mAutoLinkMask = 0
D/LeakCanary: |   mBoring = null
D/LeakCanary: |   mBreakStrategy = 0
D/LeakCanary: |   mBufferType = android.widget.TextView$BufferType@1887922400 (0x708768e0)
D/LeakCanary: |   mChangeWatcher = android.widget.TextView$ChangeWatcher@317608256 (0x12ee5140)
D/LeakCanary: |   mCharWrapper = null
D/LeakCanary: |   mCurHintTextColor = -4868675
D/LeakCanary: |   mCurTextColor = -12434878
D/LeakCanary: |   mCurrentSpellCheckerLocaleCache = null
D/LeakCanary: |   mCursorDrawableRes = 17303421
D/LeakCanary: |   mDeferScroll = 40
D/LeakCanary: |   mDesiredHeightAtMeasure = 208
D/LeakCanary: |   mDeviceProvisionedState = 0
D/LeakCanary: |   mDrawables = null
D/LeakCanary: |   mEditableFactory = android.text.Editable$Factory@1887857432 (0x70866b18)
D/LeakCanary: |   mEditor = android.widget.Editor@321776992 (0x132ded60)
D/LeakCanary: |   mEllipsize = null
D/LeakCanary: |   mFilters = android.text.InputFilter[0]@1887985568 (0x70885fa0)
D/LeakCanary: |   mFreezesText = false
D/LeakCanary: |   mGravity = 8388627
D/LeakCanary: |   mHighlightColor = 1711314568
D/LeakCanary: |   mHighlightPaint = android.graphics.Paint@320332176 (0x1317e190)
D/LeakCanary: |   mHighlightPath = android.graphics.Path@319508960 (0x130b51e0)
D/LeakCanary: |   mHighlightPathBogus = false
D/LeakCanary: |   mHint = java.lang.String@316179968 (0x12d88600)
D/LeakCanary: |   mHintBoring = android.text.BoringLayout$Metrics@319245600 (0x13074d20)
D/LeakCanary: |   mHintLayout = android.text.BoringLayout@320982248 (0x1321cce8)
D/LeakCanary: |   mHintTextColor = android.content.res.ColorStateList@316399536 (0x12dbdfb0)
D/LeakCanary: |   mHorizontallyScrolling = false
D/LeakCanary: |   mHyphenationFrequency = 1
D/LeakCanary: |   mIncludePad = true
D/LeakCanary: |   mLastLayoutDirection = -1
D/LeakCanary: |   mLastScroll = 0
D/LeakCanary: |   mLayout = android.text.DynamicLayout@328020736 (0x138d3300)
D/LeakCanary: |   mLinkTextColor = android.content.res.ColorStateList@315513920 (0x12ce5c40)
D/LeakCanary: |   mLinksClickable = true
D/LeakCanary: |   mListeners = java.util.ArrayList@319748968 (0x130efb68)
D/LeakCanary: |   mLocalesChanged = false
D/LeakCanary: |   mMarquee = null
D/LeakCanary: |   mMarqueeFadeMode = 0
D/LeakCanary: |   mMarqueeRepeatLimit = 3
D/LeakCanary: |   mMaxMode = 1
D/LeakCanary: |   mMaxWidth = 2147483647
D/LeakCanary: |   mMaxWidthMode = 2
D/LeakCanary: |   mMaximum = 8
D/LeakCanary: |   mMinMode = 2
D/LeakCanary: |   mMinWidth = 0
D/LeakCanary: |   mMinWidthMode = 2
D/LeakCanary: |   mMinimum = 196
D/LeakCanary: |   mMovement = android.text.method.ArrowKeyMovementMethod@314580960 (0x12c01fe0)
D/LeakCanary: |   mOldMaxMode = 1
D/LeakCanary: |   mOldMaximum = 8
D/LeakCanary: |   mPreDrawListenerDetached = false
D/LeakCanary: |   mPreDrawRegistered = false
D/LeakCanary: |   mPreventDefaultMovement = false
D/LeakCanary: |   mRestartMarquee = false
D/LeakCanary: |   mSavedHintLayout = android.text.BoringLayout@320982248 (0x1321cce8)
D/LeakCanary: |   mSavedLayout = null
D/LeakCanary: |   mSavedMarqueeModeLayout = null
D/LeakCanary: |   mScroller = null
D/LeakCanary: |   mShadowColor = 0
D/LeakCanary: |   mShadowDx = 0.0
D/LeakCanary: |   mShadowDy = 0.0
D/LeakCanary: |   mShadowRadius = 0.0
D/LeakCanary: |   mSingleLine = false
D/LeakCanary: |   mSpacingAdd = 0.0
D/LeakCanary: |   mSpacingMult = 1.0
D/LeakCanary: |   mSpannableFactory = android.text.Spannable$Factory@1887928216 (0x70877f98)
D/LeakCanary: |   mTempRect = android.graphics.Rect@321075160 (0x132337d8)
D/LeakCanary: |   mText = android.text.SpannableStringBuilder@318655312 (0x12fe4b50)
D/LeakCanary: |   mTextColor = android.content.res.ColorStateList@316399576 (0x12dbdfd8)
D/LeakCanary: |   mTextDir = android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@1887865352 (0x70868a08)
D/LeakCanary: |   mTextEditSuggestionContainerLayout = 17367285
D/LeakCanary: |   mTextEditSuggestionHighlightStyle = 16974926
D/LeakCanary: |   mTextEditSuggestionItemLayout = 17367287
D/LeakCanary: |   mTextPaint = android.text.TextPaint@320075024 (0x1313f510)
D/LeakCanary: |   mTextSelectHandleLeftRes = 17303425
D/LeakCanary: |   mTextSelectHandleRes = 17303427
D/LeakCanary: |   mTextSelectHandleRightRes = 17303429
D/LeakCanary: |   mTransformation = null
D/LeakCanary: |   mTransformed = android.text.SpannableStringBuilder@318655312 (0x12fe4b50)
D/LeakCanary: |   mUserSetTextScaleX = false
D/LeakCanary: |   mAccessibilityCursorPosition = -1
D/LeakCanary: |   mAccessibilityDelegate = null
D/LeakCanary: |   mAccessibilityTraversalAfterId = -1
D/LeakCanary: |   mAccessibilityTraversalBeforeId = -1
D/LeakCanary: |   mAccessibilityViewId = -1
D/LeakCanary: |   mAnimator = null
D/LeakCanary: |   mAttachInfo = null
D/LeakCanary: |   mAttributes = null
D/LeakCanary: |   mBackground = android.graphics.drawable.ColorDrawable@318013344 (0x12f47fa0)
D/LeakCanary: |   mBackgroundRenderNode = android.view.RenderNode@321074248 (0x13233448)
D/LeakCanary: |   mBackgroundResource = 0
D/LeakCanary: |   mBackgroundSizeChanged = false
D/LeakCanary: |   mBackgroundTint = null
D/LeakCanary: |   mBottom = 208
D/LeakCanary: |   mCachingFailed = false
D/LeakCanary: |   mClipBounds = null
D/LeakCanary: |   mContentDescription = null
D/LeakCanary: |   mContext = io.intercom.android.sdk.activities.IntercomMessengerActivity@320943584 (0x132135e0)
D/LeakCanary: |   mCurrentAnimation = null
D/LeakCanary: |   mDrawableState = int[3]@321849712 (0x132f0970)
D/LeakCanary: |   mDrawingCache = null
D/LeakCanary: |   mDrawingCacheBackgroundColor = 0
D/LeakCanary: |   mFloatingTreeObserver = null
D/LeakCanary: |   mForegroundInfo = null
D/LeakCanary: |   mFrameMetricsObservers = null
D/LeakCanary: |   mGhostView = null
D/LeakCanary: |   mHasPerformedLongPress = false
D/LeakCanary: |   mID = 2131296688
D/LeakCanary: |   mIgnoreNextUpEvent = false
D/LeakCanary: |   mInContextButtonPress = false
D/LeakCanary: |   mInputEventConsistencyVerifier = null
D/LeakCanary: |   mKeyedTags = null
D/LeakCanary: |   mLabelForId = -1
D/LeakCanary: |   mLastIsOpaque = false
D/LeakCanary: |   mLayerPaint = null
D/LeakCanary: |   mLayerType = 0
D/LeakCanary: |   mLayoutInsets = null
D/LeakCanary: |   mLayoutParams = android.widget.LinearLayout$LayoutParams@321572808 (0x132acfc8)
D/LeakCanary: |   mLeft = 0
D/LeakCanary: |   mLeftPaddingDefined = true
D/LeakCanary: |   mListenerInfo = null
D/LeakCanary: |   mLongClickX = NaN
D/LeakCanary: |   mLongClickY = NaN
D/LeakCanary: |   mMatchIdPredicate = null
D/LeakCanary: |   mMatchLabelForPredicate = null
D/LeakCanary: |   mMeasureCache = android.util.LongSparseLongArray@320654760 (0x131ccda8)
D/LeakCanary: |   mMeasuredHeight = 208
D/LeakCanary: |   mMeasuredWidth = 1440
D/LeakCanary: |   mMinHeight = 196
D/LeakCanary: |   mMinWidth = 0
D/LeakCanary: |   mNestedScrollingParent = null
D/LeakCanary: |   mNextFocusDownId = -1
D/LeakCanary: |   mNextFocusForwardId = -1
D/LeakCanary: |   mNextFocusLeftId = -1
D/LeakCanary: |   mNextFocusRightId = -1
D/LeakCanary: |   mNextFocusUpId = -1
D/LeakCanary: |   mOldHeightMeasureSpec = -2147481342
D/LeakCanary: |   mOldWidthMeasureSpec = 1073743264
D/LeakCanary: |   mOutlineProvider = android.view.ViewOutlineProvider$1@1887872312 (0x7086a538)
D/LeakCanary: |   mOverScrollMode = 1
D/LeakCanary: |   mOverlay = null
D/LeakCanary: |   mPaddingBottom = 0
D/LeakCanary: |   mPaddingLeft = 56
D/LeakCanary: |   mPaddingRight = 0
D/LeakCanary: |   mPaddingTop = 0
D/LeakCanary: |   mParent = android.widget.LinearLayout@321480704 (0x13296800)
D/LeakCanary: |   mPendingCheckForLongPress = null
D/LeakCanary: |   mPendingCheckForTap = null
D/LeakCanary: |   mPerformClick = null
D/LeakCanary: |   mPointerIcon = null
D/LeakCanary: |   mPrivateFlags = -2128607216
D/LeakCanary: |   mPrivateFlags2 = 538125864
D/LeakCanary: |   mPrivateFlags3 = 0
D/LeakCanary: |   mRecreateDisplayList = false
D/LeakCanary: |   mRenderNode = android.view.RenderNode@319736224 (0x130ec9a0)
D/LeakCanary: |   mResources = android.content.res.Resources@318891520 (0x1301e600)
D/LeakCanary: |   mRight = 1440
D/LeakCanary: |   mRightPaddingDefined = false
D/LeakCanary: |   mRoundScrollbarRenderer = null
D/LeakCanary: |   mRunQueue = android.view.HandlerActionQueue@317764560 (0x12f0b3d0)
D/LeakCanary: |   mScrollCache = null
D/LeakCanary: |   mScrollIndicatorDrawable = null
D/LeakCanary: |   mScrollX = 0
D/LeakCanary: |   mScrollY = 0
D/LeakCanary: |   mSendViewScrolledAccessibilityEvent = null
D/LeakCanary: |   mSendViewStateChangedAccessibilityEvent = null
D/LeakCanary: |   mSendingHoverAccessibilityEvents = false
D/LeakCanary: |   mStartActivityRequestWho = null
D/LeakCanary: |   mStateListAnimator = null
D/LeakCanary: |   mSystemUiVisibility = 0
D/LeakCanary: |   mTag = null
D/LeakCanary: |   mTempNestedScrollConsumed = null
D/LeakCanary: |   mTop = 0
D/LeakCanary: |   mTouchDelegate = null
D/LeakCanary: |   mTouchSlop = 28
D/LeakCanary: |   mTransformationInfo = android.view.View$TransformationInfo@321000952 (0x132215f8)
D/LeakCanary: |   mTransientStateCount = 0
D/LeakCanary: |   mTransitionName = null
D/LeakCanary: |   mUnscaledDrawingCache = null
D/LeakCanary: |   mUnsetPressedState = null
D/LeakCanary: |   mUserPaddingBottom = 0
D/LeakCanary: |   mUserPaddingEnd = -2147483648
D/LeakCanary: |   mUserPaddingLeft = 56
D/LeakCanary: |   mUserPaddingLeftInitial = 56
D/LeakCanary: |   mUserPaddingRight = 0
D/LeakCanary: |   mUserPaddingRightInitial = 0
D/LeakCanary: |   mUserPaddingStart = -2147483648
D/LeakCanary: |   mVerticalScrollFactor = 0.0
D/LeakCanary: |   mVerticalScrollbarPosition = 0
D/LeakCanary: |   mViewFlags = 405028865
D/LeakCanary: |   mWindowAttachCount = 1
D/LeakCanary: |   shadow$_klass_ = android.support.v7.widget.AppCompatEditText
D/LeakCanary: |   shadow$_monitor_ = 0
D/LeakCanary: * Instance of io.intercom.android.sdk.activities.IntercomMessengerActivity
D/LeakCanary: |   static SHOW_INBOX = java.lang.String@318675672 (0x12fe9ad8)
D/LeakCanary: |   static LAST_PARTICIPANT = java.lang.String@319471872 (0x130ac100)
D/LeakCanary: |   static $classOverhead = byte[2028]@315650049 (0x12d07001)
D/LeakCanary: |   static PARCEL_INITIAL_MESSAGE = java.lang.String@317615872 (0x12ee6f00)
D/LeakCanary: |   static PARCEL_CONVERSATION_ID = java.lang.String@317615936 (0x12ee6f40)
D/LeakCanary: |   activityFinisher = io.intercom.android.sdk.utilities.ActivityFinisher@315472432 (0x12cdba30)
D/LeakCanary: |   background = com.android.internal.policy.DecorView@320237568 (0x13167000)
D/LeakCanary: |   colorAnimation = android.animation.ValueAnimator@320194592 (0x1315c820)
D/LeakCanary: |   containerView = android.widget.FrameLayout@320890880 (0x13206800)
D/LeakCanary: |   inboxFragment = io.intercom.android.sdk.inbox.InboxFragment@320000256 (0x1312d100)
D/LeakCanary: |   isTwoPane = false
D/LeakCanary: |   metricTracker = io.intercom.android.sdk.metrics.MetricTracker@316106112 (0x12d76580)
D/LeakCanary: |   twig = io.intercom.android.sdk.twig.Twig@315482088 (0x12cddfe8)
D/LeakCanary: |   mDelegate = android.support.v7.app.AppCompatDelegateImplN@317317760 (0x12e9e280)
D/LeakCanary: |   mEatKeyUpEvent = false
D/LeakCanary: |   mResources = null
D/LeakCanary: |   mThemeId = 2131820742
D/LeakCanary: |   mCreated = true
D/LeakCanary: |   mFragments = android.support.v4.app.FragmentController@317478928 (0x12ec5810)
D/LeakCanary: |   mHandler = android.support.v4.app.FragmentActivity$1@318428256 (0x12fad460)
D/LeakCanary: |   mNextCandidateRequestIndex = 0
D/LeakCanary: |   mOptionsMenuInvalidated = false
D/LeakCanary: |   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@319164552 (0x13061088)
D/LeakCanary: |   mReallyStopped = true
D/LeakCanary: |   mRequestedPermissionsFromFragment = false
D/LeakCanary: |   mResumed = false
D/LeakCanary: |   mRetaining = false
D/LeakCanary: |   mStopped = true
D/LeakCanary: |   mStartedActivityFromFragment = false
D/LeakCanary: |   mStartedIntentSenderFromFragment = false
D/LeakCanary: |   mExtraDataMap = android.support.v4.util.SimpleArrayMap@319165824 (0x13061580)
D/LeakCanary: |   mActionBar = null
D/LeakCanary: |   mActionModeTypeStarting = 0
D/LeakCanary: |   mActivityInfo = android.content.pm.ActivityInfo@317319056 (0x12e9e790)
D/LeakCanary: |   mActivityTransitionState = android.app.ActivityTransitionState@320419872 (0x13193820)
D/LeakCanary: |   mApplication = {application id}.App@314783584 (0x12c33760)
D/LeakCanary: |   mCalled = true
D/LeakCanary: |   mChangeCanvasToTranslucent = false
D/LeakCanary: |   mChangingConfigurations = false
D/LeakCanary: |   mComponent = android.content.ComponentName@314813984 (0x12c3ae20)
D/LeakCanary: |   mConfigChangeFlags = 0
D/LeakCanary: |   mCurrentConfig = android.content.res.Configuration@320185088 (0x1315a300)
D/LeakCanary: |   mDecor = null
D/LeakCanary: |   mDefaultKeyMode = 0
D/LeakCanary: |   mDefaultKeySsb = null
D/LeakCanary: |   mDestroyed = true
D/LeakCanary: |   mDoReportFullyDrawn = false
D/LeakCanary: |   mEatKeyUpEvent = false
D/LeakCanary: |   mEmbeddedID = null
D/LeakCanary: |   mEnableDefaultActionBarUp = false
D/LeakCanary: |   mEnterTransitionListener = android.app.SharedElementCallback$1@1887798472 (0x708584c8)
D/LeakCanary: |   mExitTransitionListener = android.app.SharedElementCallback$1@1887798472 (0x708584c8)
D/LeakCanary: |   mFinished = true
D/LeakCanary: |   mFragments = android.app.FragmentController@317478992 (0x12ec5850)
D/LeakCanary: |   mHandler = android.os.Handler@318428352 (0x12fad4c0)
D/LeakCanary: |   mHasCurrentPermissionsRequest = false
D/LeakCanary: |   mIdent = 254790968
D/LeakCanary: |   mInstanceTracker = android.os.StrictMode$InstanceTracker@317478976 (0x12ec5840)
D/LeakCanary: |   mInstrumentation = android.app.Instrumentation@315396592 (0x12cc91f0)
D/LeakCanary: |   mIntent = android.content.Intent@315170648 (0x12c91f58)
D/LeakCanary: |   mLastNonConfigurationInstances = null
D/LeakCanary: |   mMainThread = android.app.ActivityThread@314691840 (0x12c1d100)
D/LeakCanary: |   mManagedCursors = java.util.ArrayList@319165848 (0x13061598)
D/LeakCanary: |   mManagedDialogs = null

**Comment by skylerwshaw** [comment]
Hey @Amagi82, thanks for the report. At first glance it look like there might be an OS level leak occurring surrounding `android.widget.TextView` but we're going to dig further to see if we're contributing in any way. Will update when we get some more information for you. Thanks! 👍

**Comment by Amagi82** [comment]
Yeah, I wasn't sure, so I figured I'd have you guys take a look. Wouldn't be the first OS-level leak I've seen.

**Comment by ronocod** [comment]
The code that was running here was from TextView:

```java
private void updateTextServicesLocaleAsync() {
    // AsyncTask.execute() uses a serial executor which means we don't have
    // to lock around updateTextServicesLocaleLocked() to prevent it from
    // being executed n times in parallel.

    // NB: THIS IS TextView$3 ⬇️ 
    AsyncTask.execute(new Runnable() {
        @Override
        public void run() {
            updateTextServicesLocaleLocked();
        }
    });
}

private void updateTextServicesLocaleLocked() {
    final TextServicesManager textServicesManager = (TextServicesManager)
            mContext.getSystemService(Context.TEXT_SERVICES_MANAGER_SERVICE);
    final SpellCheckerSubtype subtype = textServicesManager.getCurrentSpellCheckerSubtype(true);
    final Locale locale;
    if (subtype != null) {
        locale = subtype.getLocaleObject();
    } else {
        locale = null;
    }
    mCurrentSpellCheckerLocaleCache = locale;
}
```

It's not controlled by us and should finish executing after some time, at which point the memory will be freed. Thanks for reporting this, we're very strict on catching memory leaks! 😄
