### ISSUE TITLE
Cannot use Intercom with Google Analytics sdk on android version 4.4

### ISSUE THREAD

**Issue by touficSl** [intercom/intercom-android#374]
## Version info
  - Intercom for Android version: 3.2.7
  - Android OS version: 4.4 (4.4.4, 4.43, 4.4.2)
  - Android Device: Samnsung, LGE, HTC, Micromax,

## Expected behavior
GA with intercom works on all android versions

## Actual behavior
Application crash on v4.4

## Steps to reproduce
 1. Open app
 2. Crash

## Code
Dependencies {
     Compile fileTree (include: ['* .jar'], dir: 'libs')
     Compile 'com.google.android.gms: play-services-analytics: 10.2.1' // Google Analytics
     Compile 'io.intercom.android:intercom-sdk:3+' // Intercom
}

## Logs
07-01 16:05:45.653 13263-13263/? D/dalvikvm: Late-enabling CheckJNI
07-01 16:05:45.713 13263-13263/com.caspervpn.vpn D/ActivityThread: handleBindApplication:com.caspervpn.vpn
07-01 16:05:45.833 13263-13263/com.caspervpn.vpn I/dalvikvm: Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zzg.zzz
07-01 16:05:45.833 13263-13263/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve virtual method 720: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
07-01 16:05:45.833 13263-13263/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
07-01 16:05:45.843 13263-13263/com.caspervpn.vpn I/GAv4: Google Analytics 10.2.40 is starting up. To enable debug logging on a device run:
                                                           adb shell setprop log.tag.GAv4 DEBUG
                                                           adb logcat -s GAv4
07-01 16:05:45.873 13263-13263/com.caspervpn.vpn W/ApplicationPackageManager: getCSCPackageItemText()
07-01 16:05:45.893 13263-13300/com.caspervpn.vpn W/GAv4: AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
07-01 16:05:45.923 13263-13300/com.caspervpn.vpn W/GAv4: CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
07-01 16:05:45.923 13263-13263/com.caspervpn.vpn W/ApplicationPackageManager: getCSCPackageItemText()
07-01 16:05:45.983 13263-13263/com.caspervpn.vpn I/CrashlyticsCore: Initializing Crashlytics 2.3.16.dev
07-01 16:05:45.983 13263-13300/com.caspervpn.vpn W/GAv4: AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
07-01 16:05:46.013 13263-13263/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.converter.gson.GsonConverterFactory.create, referenced from method io.intercom.android.sdk.api.ApiFactory.createRetrofitClient
07-01 16:05:46.013 13263-13263/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61590: Lio/intercom/retrofit2/converter/gson/GsonConverterFactory;.create (Lio/intercom/com/google/gson/Gson;)Lio/intercom/retrofit2/converter/gson/GsonConverterFactory;
07-01 16:05:46.013 13263-13263/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x000d
07-01 16:05:46.103 13263-13323/com.caspervpn.vpn V/MediaPlayer: decode(54, 558096, 3801)
07-01 16:05:46.163 13263-13323/com.caspervpn.vpn V/MediaPlayer: decode(57, 81952, 5473)
07-01 16:05:46.233 13263-13323/com.caspervpn.vpn V/MediaPlayer: decode(58, 112908, 5055)
07-01 16:05:46.293 13263-13323/com.caspervpn.vpn V/MediaPlayer: decode(59, 1591184, 4219)
07-01 16:05:46.343 13263-13263/com.caspervpn.vpn W/ApplicationPackageManager: getCSCPackageItemText()
07-01 16:05:46.383 13263-13263/com.caspervpn.vpn D/DisplayManager: DisplayManager()
07-01 16:05:46.393 13263-13263/com.caspervpn.vpn E/CasperVPN: Application Opened
07-01 16:05:46.504 13263-13263/com.caspervpn.vpn W/Intercom realtime: No realtime endpoints present so we can't connect
07-01 16:05:46.674 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method android.content.Context.getNoBackupFilesDir, referenced from method com.google.android.gms.common.util.zzx.getNoBackupFilesDir
07-01 16:05:46.674 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve virtual method 553: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
07-01 16:05:46.674 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
07-01 16:05:46.764 13263-13263/com.caspervpn.vpn D/OpenGLRenderer: Enabling debug mode 0
07-01 16:05:46.834 13263-13263/com.caspervpn.vpn I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@41f6be28 time:161264902
07-01 16:05:46.924 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.checkNotNull, referenced from method io.intercom.retrofit2.Retrofit$Builder.addCallAdapterFactory
07-01 16:05:46.924 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61584: Lio/intercom/retrofit2/Utils;.checkNotNull (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
07-01 16:05:46.924 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0004
07-01 16:05:46.924 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.checkNotNull, referenced from method io.intercom.retrofit2.Retrofit$Builder.addConverterFactory
07-01 16:05:46.924 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61584: Lio/intercom/retrofit2/Utils;.checkNotNull (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
07-01 16:05:46.924 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0004
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.checkNotNull, referenced from method io.intercom.retrofit2.Retrofit$Builder.baseUrl
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61584: Lio/intercom/retrofit2/Utils;.checkNotNull (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.checkNotNull, referenced from method io.intercom.retrofit2.Retrofit$Builder.baseUrl
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61584: Lio/intercom/retrofit2/Utils;.checkNotNull (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.checkNotNull, referenced from method io.intercom.retrofit2.Retrofit$Builder.callFactory
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61584: Lio/intercom/retrofit2/Utils;.checkNotNull (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.checkNotNull, referenced from method io.intercom.retrofit2.Retrofit$Builder.callbackExecutor
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61584: Lio/intercom/retrofit2/Utils;.checkNotNull (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.checkNotNull, referenced from method io.intercom.retrofit2.Retrofit$Builder.client
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61584: Lio/intercom/retrofit2/Utils;.checkNotNull (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.getRawType, referenced from method io.intercom.retrofit2.BuiltInConverters.requestBodyConverter
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61587: Lio/intercom/retrofit2/Utils;.getRawType (Ljava/lang/reflect/Type;)Ljava/lang/Class;
07-01 16:05:46.934 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0002
07-01 16:05:46.944 13263-13383/com.caspervpn.vpn I/dalvikvm: Could not find method io.intercom.retrofit2.Utils.isAnnotationPresent, referenced from method io.intercom.retrofit2.BuiltInConverters.responseBodyConverter
07-01 16:05:46.944 13263-13383/com.caspervpn.vpn W/dalvikvm: VFY: unable to resolve static method 61588: Lio/intercom/retrofit2/Utils;.isAnnotationPresent ([Ljava/lang/annotation/Annotation;Ljava/lang/Class;)Z
07-01 16:05:46.944 13263-13383/com.caspervpn.vpn D/dalvikvm: VFY: replacing opcode 0x71 at 0x0006
07-01 16:05:46.954 13263-13383/com.caspervpn.vpn W/dalvikvm: threadid=32: thread exiting with uncaught exception (group=0x41904bc0)
07-01 16:05:47.284 13263-13263/com.caspervpn.vpn D/dalvikvm: Trying to load lib /data/app-lib/com.caspervpn.vpn-9/libopvpnutil.so 0x41f6f198
07-01 16:05:47.294 13263-13263/com.caspervpn.vpn D/dalvikvm: Added shared lib /data/app-lib/com.caspervpn.vpn-9/libopvpnutil.so 0x41f6f198
07-01 16:05:47.505 13263-13379/com.caspervpn.vpn I/Timeline: Timeline: Activity_launch_request id:com.caspervpn.vpn time:161265573
07-01 16:05:47.615 13263-13263/com.caspervpn.vpn D/AndroidRuntime: Shutting down VM
07-01 16:05:47.615 13263-13263/com.caspervpn.vpn W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41904bc0)
07-01 16:05:48.075 13263-13314/com.caspervpn.vpn D/dalvikvm: GC_FOR_ALLOC freed 2739K, 32% free 10156K/14756K, paused 34ms, total 34ms
07-01 16:05:49.316 13263-13307/com.caspervpn.vpn D/dalvikvm: GC_FOR_ALLOC freed 2498K, 36% free 9473K/14756K, paused 36ms, total 36ms
07-01 16:05:49.366 13263-13383/com.caspervpn.vpn E/AndroidRuntime: FATAL EXCEPTION: IntentService[Intercom GCM Registration Service]
                                                                   Process: com.caspervpn.vpn, PID: 13263
                                                                   java.lang.NoClassDefFoundError: io.intercom.retrofit2.Utils
                                                                       at io.intercom.retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:449)
                                                                       at io.intercom.android.sdk.api.ApiFactory.createRetrofitClient(ApiFactory.java:84)
                                                                       at io.intercom.android.sdk.api.ApiFactory.createWithNetworkClient(ApiFactory.java:47)
                                                                       at io.intercom.android.sdk.api.ApiFactory.create(ApiFactory.java:39)
                                                                       at io.intercom.android.sdk.Injector.getApi(Injector.java:164)
                                                                       at io.intercom.android.sdk.push.IntercomPushClient.sendTokenToIntercom(IntercomPushClient.java:88)
                                                                       at io.intercom.android.sdk.gcm.IntercomGcmRegistrationService.onHandleIntent(IntercomGcmRegistrationService.java:35)
                                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
07-01 16:05:50.437 13263-13314/com.caspervpn.vpn I/CrashlyticsCore: Crashlytics report upload complete: 59579E2A02EB-0001-3426-CDE53739B3BB
07-01 16:05:50.578 13263-13314/com.caspervpn.vpn D/dalvikvm: GC_FOR_ALLOC freed 1432K, 35% free 9631K/14756K, paused 25ms, total 25ms
07-01 16:05:50.638 13263-13263/com.caspervpn.vpn I/Process: Sending signal. PID: 13263 SIG: 9

**Comment by touficSl** [comment]
@harkin

**Comment by DaleCantwell** [comment]
Hi @touficSl 
Thanks for getting in touch. Are you multidexing your application? If so does your custom Application class extend MultiDexApplication?
The guide here may come in handy: https://developer.android.com/studio/build/multidex.html#mdex-gradle

**Comment by touficSl** [comment]
@DaleCantwell 

Thank you for your help!
It worked

Best Regards

**Comment by DaleCantwell** [comment]
Glad to hear its working now :)
