### ISSUE TITLE
Crash on calling Intercom.client().displayMessenger() or displayMessageComposer()

### ISSUE THREAD

**Issue by johnstan** [intercom/intercom-android#377]
## Version info
  - Intercom for Android version: 3.2.8
  - Android OS version: 5.0.0, 6.0.4
  - Android Device: Nexus 5, Nexus 10, Nexus 10 simulator

## Expected behavior
Composer window should open

## Actual behavior
App crash [logs below]

## Steps to reproduce
 1. Create a new empty app and call Intercom.initialize(...);
 2. Begin session Intercom.client().registerIdentifiedUser(...);
 3. Call Intercom.client().displayMessageComposer();

## Logs

E/AndroidRuntime( 3394): java.lang.NoClassDefFoundError: io.intercom.android.sdk.inbox.InboxAdapter
E/AndroidRuntime( 3394): 	at io.intercom.android.sdk.inbox.InboxFragment.onCreate(InboxFragment.java:110)
E/AndroidRuntime( 3394): 	at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:976)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
E/AndroidRuntime( 3394): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
E/AndroidRuntime( 3394): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
E/AndroidRuntime( 3394): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
E/AndroidRuntime( 3394): 	at android.app.Activity.performStart(Activity.java:5949)
E/AndroidRuntime( 3394): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
E/AndroidRuntime( 3394): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/AndroidRuntime( 3394): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 3394): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime( 3394): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3394): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3394): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 3394): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3394): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3394): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 3394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by ronocod** [comment]
Are you using multidex? If so, have you set up the multidex support library up correctly? https://developer.android.com/studio/build/multidex.html#mdex-pre-l

**Comment by johnstan** [comment]
Yes, multidex set up fine and works for other components no issue. Tried this in a clean project and same problem. Intercom is loading - in the dashboard I can see the user registration, and can push messages to the app (the messages pop up in a bubble at the bottom of the screen but app also crashes if I click on one of those to open)

**Comment by johnstan** [comment]
Resolved after I removed Android SDK and support libraries and re-added... not sure what exactly the issue was, but this fixed it up. Closing...

**Comment by harkin** [comment]
@johnstan That looks very like a dex error. Adding/removing libraries like that change the distribution of classes in the `dex` files generated so it's possible you've just moved the bug elsewhere.Just a heads up incase you do see something similar elsewhere in your app 👍

**Comment by johnstan** [comment]
Thanks - will keep an eye!
