### ISSUE TITLE
Text on app bar overlapping

### ISSUE THREAD

**Issue by faleksic** [intercom/intercom-android#378]
## Version info
  - Intercom for Android version: 3.2.8
  - Android OS version: 6.0.1
  - Android Device: Samsung Galaxy J7

## Expected behavior
Assistant's name not overlapping with status text
## Actual behavior
Status text going over assistant's name
## Steps to reproduce
 1.  Set intercom version to 3.2.8
 2.  List all conversation
 3. Open conversation with assistant that has only name written on app bar

## Logs
![device-2017-07-17-153010](https://user-images.githubusercontent.com/14061953/28270751-e2c4c178-6b06-11e7-98f8-f4a13c9afd13.png)

**Comment by DaleCantwell** [comment]
Hi @faleksic I'll look into the issue. If you tap on the profile/ swipe the conversation to the top so it expands could you let me know what other pieces of information are in the profile

eg.
Location
Bio
Social accounts

Thanks
Dale

**Comment by faleksic** [comment]
Hi @DaleCantwell,
I can't expand that user and I have noticed that it is happening with only this user. There is another one and everything is working well with him.

**Comment by ronocod** [comment]
Fixed in 3.2.9, can you update your app to that version?
