### ISSUE TITLE
duplicate entry error?

### ISSUE THREAD

**Issue by sirvon** [intercom/intercom-android#38]
Error:Execution failed for task ':app:packageAllDEMODebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: intercom/intercomsdk/R$dimen.class

**Comment by DaleCantwell** [comment]
Hi @sirvon 
This error is typically seen because we both have the same dependency in our library and your app.

As of version 0.8.5 we have the following dependencies 

    compile 'com.android.support:support-v4:21.0.2'
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.android.gms:play-services:6.5.87'

**Comment by DaleCantwell** [comment]
Here are our current dependencies:
```
compile 'com.android.support:support-v4:22.0.0'
compile 'com.google.code.gson:gson:2.3'
compile 'com.squareup:otto:1.3.6'
compile 'com.squareup.okhttp:okhttp:2.2.0'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
compile 'com.squareup.retrofit:retrofit:1.9.0'
compile 'com.squareup.picasso:picasso:2.4.0'
compile 'com.google.android.gms:play-services-base:6.5.87' 
```
Let me know if you update to version 0.9.0 and use the dependencies above and are still seeing this issue.
