### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lio/intercom/android/sdk/twig/Twig

### ISSUE THREAD

**Issue by crontab** [intercom/intercom-android#382]
The app crashes at startup specifically on a API 21 device, but works fine on other devices and newer OS versions.

```
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/intercom/android/sdk/twig/Twig;
        at io.intercom.android.sdk.logger.LumberMill.<clinit>(LumberMill.java:11)
        at io.intercom.android.sdk.logger.LumberMill.getLogger(LumberMill.java:16)
        at io.intercom.android.sdk.Intercom.<clinit>(Intercom.java:48)
        at io.intercom.android.sdk.Intercom.initialize(Intercom.java:66)
        ...
```

## Version info
  - Intercom for Android version: 3.2.8
  - Android OS version: 5.0.1
  - Android Device: Samsung GT-I9505

**Comment by skylerwshaw** [comment]
Have you set up the Multidex support library? More info on this topic can be found by checking out this useful guide:
https://developer.android.com/studio/build/multidex.html#mdex-pre-l

When implementing multidex a common mistake is to forgetting to extend the custom application with MultiDexApplication:
```
public class MyApplication extends MultiDexApplication
```

**Comment by crontab** [comment]
@skylerwshaw MultiDex is enabled in the gradle script, the main application class is not derived from MultiDexApplication.

Strange thing is, the app worked fine on this device until I added some encryption functionality. Not sure if it's related or not.

Anyway, will let you know once (and if) resolved.

**Comment by skylerwshaw** [comment]
@crontab Definitely let us know if this doesn't work but we're confident it will. It's required in this case. 👍

**Comment by crontab** [comment]
@skylerwshaw unfortunately that didn't help. I have multiDexEnabled in the gradle script, also changed  the main application class to extend MultiDexApplication. The app fails the same way and only on that one device (Samsung/API 21) but not the others.

**Comment by ronocod** [comment]
Can you post the versions you have for:

* `compileSdkVersion`
* `buildToolsVersion`
* The Multidex Support Library
* The Android Gradle plugin

**Comment by crontab** [comment]
@ronocod 

* compileSdkVersion 25
* buildToolsVersion 25.0.3
* com.android.support:multidex:1.0.1
* Gradle: 3.3

**Comment by ronocod** [comment]
Version 1.0.2 of the Multidex library is out, trying that could help.

**Comment by crontab** [comment]
@ronocod 1.0.2 doesn't seem to be available yet. Could you keep this issue open please, as it's probably not a trivial one: firstly it fails only on specific platforms and also not initializing Intercom at app startup actually fixes it (despite that we have a bunch of other 3rd party libraries)

**Comment by ronocod** [comment]
1.0.2 is out via the Google Maven Repository. You can see how to set that up here: https://developer.android.com/topic/libraries/support-library/setup.html#add-library

Are there any other devices this fails on apart from the GT-I9505 running 5.0.1?

**Comment by crontab** [comment]
@ronocod eventually solved by optimizing the play services linkage. I suppose something is still wrong somewhere, but anyway... thanks for your help!

**Comment by ronocod** [comment]
No problem 😄
