### ISSUE TITLE
The resource file is duplicated

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#385]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:3.2.6
  - Android OS version:4.4.4
  - Android Device:samsung:GT-I9508V:armeabi-v7a

## Expected behavior
Use the tool to scan out this problem
## Actual behavior
![image](https://user-images.githubusercontent.com/3073370/28349088-3e11646a-6c73-11e7-8a39-8497d57cb46d.png)    
![image](https://user-images.githubusercontent.com/3073370/28349121-6432dda4-6c73-11e7-9ea1-4baf0b46538e.png)

## Steps to reproduce
The resource file is duplicated ，Please delete duplicate files 

## Logs

**Comment by DaleCantwell** [comment]
Thanks for reporting that @noinlijin this will be fixed in the next release.

**Comment by ronocod** [comment]
Fixed in 3.2.9
