### ISSUE TITLE
Very long, UI-blocking requests happening

### ISSUE THREAD

**Issue by brianmuse** [intercom/intercom-android#39]
I noticed this while debugging an apparent freeze in my app. This was a 1st gen Moto X running 4.4.

```
 D/Volley﹕ [1467] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://mobileapi-v2.intercom.io/events 0x9a4d6052 NORMAL 6> [lifetime=34680], [size=1], [rc=202], [retryCount=1]
D/Volley﹕ [1] Request.finish: 34890 ms: [ ] https://mobileapi-v2.intercom.io/events 0x9a4d6052 NORMAL 6
```

So two things here:

- What is causing a request to take 35 seconds? Is this API slowness issue with `https://mobileapi-v2.intercom.io`?
- Why are API requests (or some other work) being done on the main thread? The UI was blocked completely by whatever this was.

**Comment by DaleCantwell** [comment]
Hi Brian,
It is very unusual for the API to take anything even close to that amount of time. It could have been that we were experiencing some down time on the API.
None of our API work is done on the UI thread. Have you been able to reproduce this or see it on any other device?
I have tried to reproduce it here but have been unsuccessful. We are moving away from volley as our networking layer but we will keep an eye out for this issue.

**Comment by DaleCantwell** [comment]
@brianmuse We have just updated the SDK to version 0.9.0. We no longer hit that endpoint and that area of the SDK has been completely reworked. We have tested our new endpoints and could not reproduce this issue. Let us know if you encounter this issue again and we will investigate it further.

**Comment by brianmuse** [comment]
We're able to plug the SDK back into the app. I'll let you know how it goes. Thanks so much for your attention on this!

**Comment by brianmuse** [comment]
Just to follow up, things seem very snappy on the latest!
