### ISSUE TITLE
Intercom: Api call failed:

### ISSUE THREAD

**Issue by peddiraju211** [intercom/intercom-android#391]
## Version info
  - Intercom for Android version: 3.2.8
  - Android OS version: 6.0.1
  - Android Device: Samsung Tab S

## Logs
E/Intercom: Api call failed: {"type":"error.list","request_id":"XXXXXXX","errors":[{"code":"hmac_mismatch","message":"Failed Identity Verification check"}]}

**Comment by skylerwshaw** [comment]
@peddiraju211 This indicates that the value you're passing into the `setUserHash` method is not correctly calculated using the Android-specific secret key and the `user_id` or `email` of the user in question.

Please ensure you're calculating a SHA256 hash using this user data and the correct secret key. You can verify your secret key here: 
https://app.intercom.com/a/apps/_/settings/identity-verification/android

Additionally, if you accidentally turned on identity verification and do not want to use it, you can disable it at the link above.

If you have any other customer support related questions, feel free to message us using the Intercom in-app messenger within your Intercom dashboard. Feel free to reference me, Skyler.
