### ISSUE TITLE
Dear intercom-android team. 

### ISSUE THREAD

**Issue by microgomi** [intercom/intercom-android#40]
Dear intercom-android team. 
I'm using an previous android system(eclipse IDE) so I need jar files to import this project to mine.
you only provide an aar file, so i've added classes.jar and AndroidBlocks.jar files as libs to my project.
It seems working well  but I'm not sure. (if you ok, could you send me a jar file?)

And I'm trying to import mixpanel data to intercom.
I can see the iOS data in the intercom page but android not. 
I called  flowing sequences in android.(I can see the anroid login data in mixpanel)
=> initialize -> setApikKey(with right key) -> beginSessionWithUserI
I don't know why, could you help me about this problem too?

I'm not friendly with english, so I know you hard to understand my question. 
but I must solve these problems as soon as possilble. 

Please help me.

**Comment by adamkmccarthy** [comment]
Hi @microgomi. Thanks for reaching out to us. The Android SDK is currently in a closed beta, which is why you don't have Android keys available in your account in Intercom. We'll be expanding this beta soon, we'll let you know when it becomes available again.

**Comment by microgomi** [comment]
Thank you very much.


2015-02-16 16:38 GMT+09:00 Adam McCarthy <notifications@github.com>:

**Comment by microgomi** [comment]
Dear McCarthy,


I just want to import the mixpanel data.
Current version dons't support that function in android ?

My App Id : jytc2mrq
API Key: 5d722f6bfc49547fc7730ff11880c9816faaecab

I have 1 user "Jin, Deoc".

Can you check it please?


2015-02-16 23:52 GMT+09:00 deoc jin <microgomi@gmail.com>:

**Comment by adamkmccarthy** [comment]
Hi there, please don't post your API key publicly here (i've deleted your previous message). Can you contact us through Intercom when you log in? Thanks!

**Comment by microgomi** [comment]
thank you :-) I will ask through Intercom.
