### ISSUE TITLE
Duplicate file exception - Duplicate files copied

### ISSUE THREAD

**Issue by ammard2u** [intercom/intercom-android#400]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.0.1
  - Android OS version: 7.1.2
  - Android Device: Pixel XL

## Expected behavior 
app able to compile and run

## Actual behavior
error message when build

## Steps to reproduce
 1.  Update intercom from 3.x to 4.x
 2. Build the project
 3. 

## Logs

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForClientDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK publicsuffixes.gz
	File1: \.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\3.8.0\5a11f020cce2d11eb71ba916700600e18c4547e7\okhttp-3.8.0.jar
	File2: \.android\build-cache\ae2ecabe73b7d9b64d54c0f4d3bb363cfea70e59\output\jars\libs\repackaged_dependencies.jar

![image](https://user-images.githubusercontent.com/25141264/29242106-1f8be1d8-7fb9-11e7-954f-c5cec1090642.png)

**Comment by stitch9108** [comment]
Hi

I had the same issue. I fixed it by adding this to the module's build.gradle

```
android {
    ...
    packagingOptions{
        exclude 'META-INF/rxjava.properties'
        exclude 'publicsuffixes.gz'
    }
}
```

I think it's a good way to fix it unless the intercom team has a better one.

**Comment by ronocod** [comment]
For now the best fix for this is to add this to the module's `build.gradle`:
```groovy
android {
    ...
    packagingOptions{
        pickFirst 'publicsuffixes.gz'
    }
}
```
Using `exclude` can cause some methods to crash the app. We're looking into a better way to manage this.

**Comment by ammard2u** [comment]
thanks. that work.  :)
