### ISSUE TITLE
Update user details creates multiple users

### ISSUE THREAD

**Issue by JaerenMoneyBox** [intercom/intercom-android#403]
## Version info
  - Intercom for Android version:
  - Android OS version: ANY
  - Android Device: Nexus 6

Hey,

We have an issue in our app where we have multiple intercom users for the same user in our app. All of these users have the same name and email address but a different intercom ID.  

We believe this is because we are calling Intercom.client().updateUser straight after we identify the user, meaning if the identify call hasn't completed we are instead updating the anonymous user's details.

## Expected behavior

updateUser should always update the identified user.

## Actual behavior

updateUser can update the anonymous user if the identify call hasn't completed yet.

## Steps to reproduce
 1. User opens the app and we call
Intercom.client.registerUnidentifiedUser()
 2. User logs in and we call identify user with OUR user ID.
Intercom.client().registerIdentifiedUser(Registration.create().withUserId(userId));
 3. Immediately after we call
UserAttributes attributes = new UserAttributes.Builder()
                .withEmail(email)
                .withName(name)
                .build();
Intercom.client().updateUser(attributes);
4. When the user leaves the app and opens the app we again call
Intercom.client.registerUnidentifiedUser()
as they have to pin login to enter the app.

My question is, can we make sure that the identify call has completed before we update the users details?  Is there a listener for when the user is identified, or is this something that could be addressed in an update?

Thanks,

Jaeren.

**Comment by DaleCantwell** [comment]
One thing that might make this neater is to perform the update with the registration.
On versions before 4 you need to pass in a HashMap: 

```JAVA
 Map<String, Object> userAttributes = new HashMap<>();
 userAttributes.put("name", "Admin name");
 
 Registration.create()
     .withUserId("12345")
     .withEmail("test@email.com")
     .withUserAttributes(userAttributes);
 Intercom.client().registerIdentifiedUser(registration);
```

Since version 4 you can use the UserAttributes model in this call

```JAVA
UserAttributes attributes = new UserAttributes.Builder()
  .withName(name)
  .build();

 Registration.create()
     .withUserId("12345")
     .withEmail("test@email.com")
     .withUserAttributes(attributes);
 Intercom.client().registerIdentifiedUser(registration);
```

Could you try that out and see if you are still getting multiple users

**Comment by bboyle18** [comment]
Hi @JaerenMoneyBox 👋 

Just wanted to check if you tried @DaleCantwell's suggestion above?
Did this fix your issue or are you still having problems?

Please let us know 👍 

Thanks
Brian

**Comment by alexblack** [comment]
We seem to be having a similar issue, any updates on a fix?

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
