### ISSUE TITLE
Icon positioning 

### ISSUE THREAD

**Issue by huntj88** [intercom/intercom-android#405]
## Version info
  - Intercom for Android version: 4.0.1   -sdk-base-transitive
  - Android OS version: 7.1
  - Android Device: Nexus 6 and every other device

## Expected behavior

I would expect to be able to move it per the solution at the bottom of this issue
[other issue](https://github.com/intercom/intercom-android/issues/231)

## Actual behavior

its moves but sometimes this happens
![screenshot_1503517198](https://user-images.githubusercontent.com/10103298/29637380-911f7964-8819-11e7-9deb-695a8a2b60ec.png)

## Steps to reproduce

unsure exactly how to reproduce because it does not happen every time. 
I suspect it has to do with me navigating to a new activity, and then immediately using a library to take a picture which opens up its own activity 

# another big issue 
another big issue is the ability to move it where I want during runtime. On certain pages, I need to be able to have it in a different spot, but until then I just have to disable intercom on those pages. For example, I would like to move it to the bottom of the page on this screen, but I need it higher almost everywhere else in the app.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
