### ISSUE TITLE
Android 8.0 Background limitations causing crash

### ISSUE THREAD

**Issue by danlegion** [intercom/intercom-android#406]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.01
  - Android OS version: 8.0
  - Android Device: Nexus 6P

## Expected behavior
The app not to crash

## Actual behavior
Intercom SDK is causing the app to crash

## Steps to reproduce
 1. Launch any app with the sdk installed and with the initialized method called
 2. Background the app 
 3. Remove the app from the the list of recently used apps
 4. App crashes due to new Background limitations on Android 8.0

## Logs

> FATAL EXCEPTION: main
>                                                                          Process: net.payload.payload.debug, PID: 7032
>                                                                          java.lang.RuntimeException: Unable to create application net.payload.payload.core.PayLoadApp: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=net.payload.payload.debug/io.intercom.android.sdk.gcm.IntercomGcmRegistrationService }: app is in background uid UidRecord{3dfc7e5 u0a127 SVC  idle procs:1 seq(0,0,0)}
>                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
>                                                                              at android.app.ActivityThread.-wrap1(Unknown Source:0)
>                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
>                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
>                                                                              at android.os.Looper.loop(Looper.java:164)
>                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
>                                                                              at java.lang.reflect.Method.invoke(Native Method)
>                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
>                                                                           Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=net.payload.payload.debug/io.intercom.android.sdk.gcm.IntercomGcmRegistrationService }: app is in background uid UidRecord{3dfc7e5 u0a127 SVC  idle procs:1 seq(0,0,0)}
>                                                                              at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
>                                                                              at android.app.ContextImpl.startService(ContextImpl.java:1461)
>                                                                              at android.content.ContextWrapper.startService(ContextWrapper.java:644)
>                                                                              at io.intercom.android.sdk.IntercomPushManager.startGcmRegistrationService(IntercomPushManager.java:29)
>                                                                              at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:116)
>                                                                              at io.intercom.android.sdk.RealIntercom.create(RealIntercom.java:79)
>                                                                              at io.intercom.android.sdk.Intercom.initialize(Intercom.java:72)
>                                                                              at net.payload.payload.core.PayLoadApp.initIntercom(PayLoadApp.java:69)
>                                                                              at net.payload.payload.core.PayLoadApp.onCreate(PayLoadApp.java:42)
>                                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
>                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
>                                                                              at android.app.ActivityThread.-wrap1(Unknown Source:0) 
>                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
>                                                                              at android.os.Handler.dispatchMessage(Handler.java:105) 
>                                                                              at android.os.Looper.loop(Looper.java:164) 
>                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541) 
>                                                                              at java.lang.reflect.Method.invoke(Native Method) 
>                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
>                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by DaleCantwell** [comment]
@danlegion thank you for getting in touch, I'm looking into this right away

**Comment by JorgeCastilloPrz** [comment]
Exactly this, we already have the same problem on GoMore, where we use Intercom SDK A LOT.

**Comment by ronocod** [comment]
We're working on a fix for this, there will be improvements in the next release.

**Comment by ronocod** [comment]
This should be fixed in version 4.0.2, can you try that version?

**Comment by Mathbl** [comment]
The use case described above doesn't crash anymore. Haven't seen a crash either during my development routine of the last hours, so seems fixed!
