### ISSUE TITLE
when you set the icon bottom padding in dimens.xml the push notification in bug out

### ISSUE THREAD

**Issue by huntj88** [intercom/intercom-android#408]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.0.1
  - Android OS version: every version
  - Android Device: every device

## Expected behavior

I would expect it to not go above the top of the screen when I set "intercom_bottom_padding" to anything other than 0. the more push notifications that are sent the higher it goes until you can't see the intercom icon anymore

## Actual behavior

![screenshot_20170824-153332](https://user-images.githubusercontent.com/10103298/29690949-b9581032-88ee-11e7-8e2a-c4c9d9bb9cc5.png)

## Steps to reproduce
 1. set "intercom_bottom_padding" to a value higher than 0. Bigger values show off the bug faster.
 2. send a bunch of push notifications

## Logs
no logs

**Comment by DaleCantwell** [comment]
Hi @huntj88 I will investigate this today

**Comment by DaleCantwell** [comment]
@huntj88 could you remove the value you are using in dimens.xml and call the method added in 3.2.2 `setBottomPadding(int bottomPadding)`
Let me know if the issue persists once switching to that

**Comment by DaleCantwell** [comment]
@huntj88 our recommended approach to this problem is to call setBottomPadding. We are phasing out using the value in dimens.xml
I'm going to close this issue for now, if you start calling setBottomPadding and encounter any issues please let us know.
Thanks,
Dale
