### ISSUE TITLE
CatchNotificationsService: Invalid notification data. 

### ISSUE THREAD

**Issue by bobongski** [intercom/intercom-android#410]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:
  - Android OS version:
  - Android Device:

## Expected behavior
Get the uri content

## Actual behavior
CatchNotificationsService: Invalid notification data

## Steps to reproduce
 1.  add uri on intercom push notification
 2. 
 3. 

## Logs

Hi guys,

I am having trouble with CatchNotificationsService: Invalid notification data
is there a sample app with this kind of setup? because It is not working for me I don't have any other reference.

**Comment by ronocod** [comment]
Can you give more detail about the error you're seeing? We don't have any classes called `CatchNotificationsService` in our code.

**Comment by bobongski** [comment]
I just add a this as my uri
crateclubApp://?type=knowledge&articleId=27945

when sending push notification on android

add this on my application

Intercom.initialize(this, "id", "id");
       Intercom.client().handlePushMessage();

and everytime I click the message on push notification i can't get my attach uri also it returns with this error. CatchNotificationsService

**Comment by ronocod** [comment]
Can you contact us through the Intercom Messenger on [our site](https://www.intercom.com/) about this?

**Comment by bboyle18** [comment]
Hi @bobongski 👋 

Just wanted to check that you contacted our support team and got this sorted?
If not, let me know and we'll do our best to help you 👍 

Thanks

Brian

**Comment by ronocod** [comment]
Closing this, it looks like an integration issue which our support team should be able to help with.
