### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError in GifDecoder.advance

### ISSUE THREAD

**Issue by littlefoxvpn** [intercom/intercom-android#415]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:4.01
  - Android OS version: Galaxy Style Duos SCH-I829
  - Android Device:4.1.2

## Expected behavior

user crash in intercom page, there is crash log

## Steps to reproduce
 user will feedback to us, who go into intercom ,and I do not know what then happen, but crash

## Logs
http://crashes.to/s/f685a818ec6

**Comment by ronocod** [comment]
Fixed in 4.0.4. We can't guarantee that image loading will never cause an OOM error as it's dealing with large objects, but they should be very rare with this version.
