### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by littlefoxvpn** [intercom/intercom-android#416]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:4.0.1
  - Android OS version:4.4.4
  - Android Device:Lenovo TAB 2 A10-70LC

## Expected behavior
user crash in intercom page, there is a crash log
## Logs

http://crashes.to/s/d5c81e26144

**Comment by ronocod** [comment]
Fixed in 4.0.3
