### ISSUE TITLE
Update the readme.md for proguard rules

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#42]
actually i'm using this 2:

```
-keep class intercom.** { *; }
-keep class io.intercom.** { *; }
```

I think I don't need more.

**Comment by DaleCantwell** [comment]
For version 0.9.0 we use `consumerProguardFiles` so you shouldn't need to add the yourself anymore.

**Comment by liorry** [comment]
That is actually not true. I'm using 1.1.8 and the project will build successfully but won't run unless you add these to your proguard file:
<pre><code>
-dontwarn intercom.**
-dontwarn io.intercom.**
</code></pre>

**Comment by harkin** [comment]
Thanks for the heads up @liorry, we'll look into this next week

**Comment by harkin** [comment]
@liorry I'm not able to reproduce that. I've made a new app, included the library and turned proguard on for debug builds and deployed it to my phone, it runs successfully. Could you give more details?

**Comment by harkin** [comment]
Gonna close this one out, will reopen if I get more details about what was giving warnings
