### ISSUE TITLE
push notification no method error 

### ISSUE THREAD

**Issue by phoenix911** [intercom/intercom-android#420]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.4

## Steps to reproduce
 1.  push notification on receive crash

## Logs
Process: com.servx.app.servx, PID: 24561
                                                                     java.lang.NoSuchMethodError: No virtual method setChannelId(Ljava/lang/String;)Landroid/support/v4/app/NotificationCompat$Builder; in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.servx.app.servx-1/split_lib_dependencies_apk.apk:classes3.dex)
                                                                         at io.intercom.android.sdk.push.SystemNotificationFactory.createSingleNotification(SystemNotificationFactory.java:59)
                                                                         at io.intercom.android.sdk.push.SystemNotificationManager.createNotification(SystemNotificationManager.java:94)
                                                                         at io.intercom.android.sdk.push.PushHandler.sendNotification(PushHandler.java:62)
                                                                         at io.intercom.android.sdk.push.PushHandler.handlePush(PushHandler.java:32)
                                                                         at io.intercom.android.sdk.push.IntercomPushClient.handlePush(IntercomPushClient.java:129)
                                                                         at io.intercom.android.sdk.push.IntercomPushClient.handlePush(IntercomPushClient.java:155)
                                                                         at com.servx.app.servx.FCM.MyFcmListnerService.onMessageReceived(MyFcmListnerService.java:35)
                                                                         at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
                                                                         at com.google.firebase.iid.zzc.run(Unknown Source)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
09-13 18:45:11.496 2267-4046/? E/ActivityManager: App crashed! Process: com.servx.app.servx

**Comment by ronocod** [comment]
Can you tell us the `compileSdkVersion` and `buildToolsVersion` you're using in your build.gradle file?

Also could you run `./gradlew dependencies` from your project folder and paste the output here please?

**Comment by phoenix911** [comment]
compileSdkVersion : 26
buildToolsVersio: 26.0.1

admin@DESKTOP-H4I5O6S MINGW64 /e/Nilesh/Servx (master)
$ ./gradlew dependencies
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --stat                                                                                                                                                                                               us for details



Download https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle                                                                                                                                                                                               -2.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.3.3/g                                                                                                                                                                                               radle-core-2.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/build/builder/2.3.3/build                                                                                                                                                                                               er-2.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/lint/lint/25.3.3/lint-25.                                                                                                                                                                                               3.3.pom
Download https://jcenter.bintray.com/com/android/tools/build/transform-api/2.0.0                                                                                                                                                                                               -deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.pom
Download https://jcenter.bintray.com/com/android/tools/build/gradle-api/2.3.3/gr                                                                                                                                                                                               adle-api-2.3.3.pom
Download https://jcenter.bintray.com/com/android/databinding/compilerCommon/2.3.                                                                                                                                                                                               3/compilerCommon-2.3.3.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm/5.0.4/asm-5.0.4.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.4/asm-parent-5.0                                                                                                                                                                                               .4.pom
Download https://jcenter.bintray.com/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-commons/5.0.4/asm-commons-5                                                                                                                                                                                               .0.4.pom
Download https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.3.2/proguard-gradle-5.3.2.pom
Download https://jcenter.bintray.com/net/sf/proguard/proguard-parent/5.3.2/proguard-parent-5.3.2.pom
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.core/0.7.5.201505241946/org.jacoco.core-0.7.5.201505241946.pom
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.build/0.7.5.201505241946/org.jacoco.build-0.7.5.201505241946.pom
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.report/0.7.5.201505241946/org.jacoco.report-0.7.5.201505241946.pom
Download https://jcenter.bintray.com/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.pom
Download https://jcenter.bintray.com/com/google/protobuf/protobuf-parent/3.0.0/protobuf-parent-3.0.0.pom
Download https://jcenter.bintray.com/com/google/google/1/google-1.pom
Download https://jcenter.bintray.com/org/antlr/antlr/3.5.2/antlr-3.5.2.pom
Download https://jcenter.bintray.com/org/antlr/antlr-master/3.5.2/antlr-master-3.5.2.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Download https://jcenter.bintray.com/com/android/tools/build/builder-model/2.3.3/builder-model-2.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/build/builder-test-api/2.3.3/builder-test-api-2.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/sdklib/25.3.3/sdklib-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/sdk-common/25.3.3/sdk-common-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/build/manifest-merger/25.3.3/manifest-merger-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/25.3.3/ddmlib-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/jack/jack-api/0.13.0/jack-api-0.13.0.pom
Download https://jcenter.bintray.com/com/android/tools/jill/jill-api/0.10.0/jill-api-0.10.0.pom
Download https://jcenter.bintray.com/com/android/tools/analytics-library/protos/25.3.3/protos-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/analytics-library/shared/25.3.3/shared-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/analytics-library/tracker/25.3.3/tracker-25.3.3.pom
Download https://jcenter.bintray.com/com/squareup/javawriter/2.5.0/javawriter-2.5.0.pom
Download https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.pom
Download https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-tree/5.0.4/asm-tree-5.0.4.pom
Download https://jcenter.bintray.com/com/android/tools/lint/lint-checks/25.3.3/lint-checks-25.3.3.pom
Download https://jcenter.bintray.com/org/eclipse/jdt/core/compiler/ecj/4.6.1/ecj-4.6.1.pom
Download https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.pom
Download https://jcenter.bintray.com/com/google/guava/guava-parent/18.0/guava-parent-18.0.pom
Download https://jcenter.bintray.com/com/android/databinding/baseLibrary/2.3.3/baseLibrary-2.3.3.pom
Download https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.pom
Download https://jcenter.bintray.com/org/antlr/antlr4-master/4.5.3/antlr4-master-4.5.3.pom
Download https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/25/commons-parent-25.pom
Download https://jcenter.bintray.com/org/apache/apache/9/apache-9.pom
Download https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.pom
Download https://jcenter.bintray.com/com/android/tools/annotations/24.5.0/annotations-24.5.0.pom
Download https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.2/proguard-base-5.3.2.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1.pom
Download https://jcenter.bintray.com/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.pom
Download https://jcenter.bintray.com/org/antlr/ST4/4.0.8/ST4-4.0.8.pom
Download https://jcenter.bintray.com/com/android/tools/layoutlib/layoutlib-api/25.3.3/layoutlib-api-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/dvlib/25.3.3/dvlib-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/repository/25.3.3/repository-25.3.3.pom
Download https://jcenter.bintray.com/com/google/code/gson/gson/2.2.4/gson-2.2.4.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/33/commons-parent-33.pom
Download https://jcenter.bintray.com/org/apache/apache/13/apache-13.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.1.1/httpcomponents-client-4.1.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/project/4.1.1/project-4.1.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.1/httpcomponents-client-4.1.pom
Download https://jcenter.bintray.com/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.pom
Download https://jcenter.bintray.com/com/android/tools/lint/lint-api/25.3.3/lint-api-25.3.3.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-analysis/5.0.4/asm-analysis-5.0.4.pom
Download https://jcenter.bintray.com/com/intellij/annotations/12.0/annotations-12.0.pom
Download https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.pom
Download https://jcenter.bintray.com/com/google/jimfs/jimfs-parent/1.1/jimfs-parent-1.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-core/4.1/httpcomponents-core-4.1.pom
Download https://jcenter.bintray.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/5/commons-parent-5.pom
Download https://jcenter.bintray.com/org/apache/apache/4/apache-4.pom
Download https://jcenter.bintray.com/commons-codec/commons-codec/1.4/commons-codec-1.4.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/11/commons-parent-11.pom
Download https://jcenter.bintray.com/com/android/tools/external/com-intellij/uast/162.2228.14/uast-162.2228.14.pom
Download https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.pom
Download https://jcenter.bintray.com/com/android/tools/annotations/25.3.3/annotations-25.3.3.pom
Download https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.3.3/gradle-core-2.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/build/builder/2.3.3/builder-2.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/lint/lint/25.3.3/lint-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api.jar
Download https://jcenter.bintray.com/com/android/tools/build/gradle-api/2.3.3/gradle-api-2.3.3.jar
Download https://jcenter.bintray.com/com/android/databinding/compilerCommon/2.3.3/compilerCommon-2.3.3.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.jar
Download https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.3.2/proguard-gradle-5.3.2.jar
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.core/0.7.5.201505241946/org.jacoco.core-0.7.5.201505241946.jar
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.report/0.7.5.201505241946/org.jacoco.report-0.7.5.201505241946.jar
Download https://jcenter.bintray.com/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9.jar
Download https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar
Download https://jcenter.bintray.com/org/antlr/antlr/3.5.2/antlr-3.5.2.jar
Download https://jcenter.bintray.com/com/android/tools/build/builder-model/2.3.3/builder-model-2.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/build/builder-test-api/2.3.3/builder-test-api-2.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/sdklib/25.3.3/sdklib-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/sdk-common/25.3.3/sdk-common-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/build/manifest-merger/25.3.3/manifest-merger-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/25.3.3/ddmlib-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/jack/jack-api/0.13.0/jack-api-0.13.0.jar
Download https://jcenter.bintray.com/com/android/tools/jill/jill-api/0.10.0/jill-api-0.10.0.jar
Download https://jcenter.bintray.com/com/android/tools/analytics-library/protos/25.3.3/protos-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/analytics-library/shared/25.3.3/shared-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/analytics-library/tracker/25.3.3/tracker-25.3.3.jar
Download https://jcenter.bintray.com/com/squareup/javawriter/2.5.0/javawriter-2.5.0.jar
Download https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar
Download https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-tree/5.0.4/asm-tree-5.0.4.jar
Download https://jcenter.bintray.com/com/android/tools/lint/lint-checks/25.3.3/lint-checks-25.3.3.jar
Download https://jcenter.bintray.com/org/eclipse/jdt/core/compiler/ecj/4.6.1/ecj-4.6.1.jar
Download https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.jar
Download https://jcenter.bintray.com/com/android/databinding/baseLibrary/2.3.3/baseLibrary-2.3.3.jar
Download https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar
Download https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar
Download https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.2/proguard-base-5.3.2.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar
Download https://jcenter.bintray.com/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
Download https://jcenter.bintray.com/org/antlr/ST4/4.0.8/ST4-4.0.8.jar
Download https://jcenter.bintray.com/com/android/tools/layoutlib/layoutlib-api/25.3.3/layoutlib-api-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/dvlib/25.3.3/dvlib-25.3.3.jar
Download https://jcenter.bintray.com/com/android/tools/repository/25.3.3/repository-25.3.3.jar
Download https://jcenter.bintray.com/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Download https://jcenter.bintray.com/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1.jar
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1.jar
Download https://jcenter.bintray.com/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.jar
Download https://jcenter.bintray.com/com/android/tools/lint/lint-api/25.3.3/lint-api-25.3.3.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-analysis/5.0.4/asm-analysis-5.0.4.jar
Download https://jcenter.bintray.com/com/intellij/annotations/12.0/annotations-12.0.jar
Download https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1.jar
Download https://jcenter.bintray.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
Download https://jcenter.bintray.com/commons-codec/commons-codec/1.4/commons-codec-1.4.jar
Download https://jcenter.bintray.com/com/android/tools/external/com-intellij/uast/162.2228.14/uast-162.2228.14.jar
Download https://jcenter.bintray.com/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.jar
Download https://jcenter.bintray.com/com/android/tools/annotations/25.3.3/annotations-25.3.3.jar
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\admin\AppData\Local\Android\Sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations

BUILD SUCCESSFUL

Total time: 3 mins 15.604 secs

admin@DESKTOP-H4I5O6S MINGW64 /e/Nilesh/Servx (master)
$

**Comment by ronocod** [comment]
Can you post the list of dependencies your app uses here? This sounds like it could be related to the version of the Firebase or Support Library versions you're running.

**Comment by DaleCantwell** [comment]
@phoenix911 are you still encountering this issue?

**Comment by DaleCantwell** [comment]
@phoenix911 I'm going to close out this issue as we have added additional protection around this. Reopen this if you run into the issue again.
Thanks,
Dale

**Comment by nguyen-vinasource** [comment]
I am using with these dependencies: 
    compile 'com.google.android.gms:play-services-plus:11.4.2'
    compile 'com.google.android.gms:play-services-auth:11.4.2'
    compile "com.google.android.gms:play-services-gcm:11.4.2"
and got the same issue. :)

**Comment by nguyen-vinasource** [comment]
I detected the issue is because some things conflict some where in my current project. My solution is switch to FCM instead of GCM.
