### ISSUE TITLE
How to get deviceToken using SDK

### ISSUE THREAD

**Issue by apo1981** [intercom/intercom-android#427]
Hi
This is not an issue, it is just a really quick question: Is it possible to get the deviceToken using your SDK? If so, which is the method to be used?
Thks in advanced

**Comment by skylerwshaw** [comment]
Hi @apo1981, here's our documentation on implementing FCM: https://developers.intercom.com/docs/android-fcm-push-notifications

We automatically send the deviceToken to be associated with your registered user on the Intercom platform. You can certainly obtain the token for your own purposes as well. There's an explanation on how to do this here:
https://developers.intercom.com/docs/android-fcm-push-notifications#section-step-7-using-intercom-with-other-fcm-setups-optional

Feel free to reach out to us with any support questions using the Intercom messenger from within your Intercom dashboard, or public pages. 😄
