### ISSUE TITLE
Empty Intercom AppLayout

### ISSUE THREAD

**Issue by 4gus71n** [intercom/intercom-android#428]
## Version info
  - Intercom for Android version: 4.+
  - Android OS version: 7.0
  - Android Device: Samsung j7

## Expected behavior
Show the AppLayout normally

## Actual behavior
The Intercom's AppLayout shows empty

## Steps to reproduce
 1.  I updated the targetSdkVersion of my project to 25 (it was on 23). I updated from `compile 'io.intercom.android:intercom-sdk-base-transitive:3.1.4'` to 4.0.3 because the old version was failing due to this bug https://github.com/intercom/intercom-android/issues/367
 2.  Updated the old HashMap custom attributes to the new UserAttributes object.
 3.  When I open the Intercom's activity through `Intercom.client().displayMessageComposer();` it shows like this https://www.youtube.com/watch?v=x6YEqqWDq_k&feature=youtu.be

Has anyone experienced the same bug? Any idea how to fix it?

**Comment by ronocod** [comment]
What `compileSdkVersion` and `buildToolsVersion` are you using in your `build.gradle`?

**Comment by 4gus71n** [comment]
Here's my build.gradle https://gist.github.com/4gus71n/75ff1b238ea2787de25dc90c58884c96

**Comment by ronocod** [comment]
Can you try the latest version (4.0.5)? I believe this was fixed in 4.0.4.

**Comment by 4gus71n** [comment]
Yeah, I can confirm that this is fixed in 4.0.5. Thanks!
