### ISSUE TITLE
Race condition calling registerIdentifiedUser too soon after registerUnidentifiedUser

### ISSUE THREAD

**Issue by alexblack** [intercom/intercom-android#432]
Our system gives users a user id before they sign up, eg they get a guest account they can later upgrade to a full account.  We're currently using SDK version 4.0.5

When our app is first installed, we call `registerUnidentifiedUser`, which lets us log early app events to intercom, then if we're successful assigning the user a userid we'll call `registerIdentifiedUser` shortly after.

We're having a problem where a small percentage of our users are assigned user ids, but, their intercom profile has an intercom user id instead of the one we assigned.

Intercom support has asked us to modify our code to avoid this by adding a two second delay:

```
      // Two second delay as proposed by Intercom support to avoid race condition
      // with registerIdentifiedUser being called too soon after registerUnidentifiedUser
      if (prevUserId == null) {
        final Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
          @Override
          public void run() {
            Intercom.client().registerIdentifiedUser(registration);
          }
        }, 2000);
```

Adding arbitrary delays in our code seems error prone and awkward, it'd be great of Intercom could fix up the SDK to avoid the need for this

```
As for the userId and adding a delay, I definitely see how this isn't ideal, but to get things working for you sooner rather than later, your best bet here would be to add that delay for now, to make sure your app is avoiding any race conditions and the correct calls are coming in in the correct order. 
```

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
