### ISSUE TITLE
Keyboard not closing on toolbar back pressed

### ISSUE THREAD

**Issue by tomrapadmi** [intercom/intercom-android#435]
## Version info
  - Intercom for Android version: 4.0.5
  - Android OS version: 8.0.0
  - Android Device: Nexus 5X

Reproducible on other devices.

## Expected behaviour
Keyboard should close when the back button is pressed.

## Actual behaviour
Keyboard stays open on the select conversation screen.

## Steps to reproduce
 1. Start app from cold.
 2. Open Intercom so it auto opens the default conversation.
 3. Open the keyboard.
 4. Press the back button in the toolbar.

## Logs
N/a

![device-2017-10-06-142103](https://user-images.githubusercontent.com/26325275/31279675-d481f394-aaa1-11e7-9af4-75c2c0f79d5b.png)

**Comment by ronocod** [comment]
We're looking into this now.

**Comment by ronocod** [comment]
This is fixed in 4.1.3.
