### ISSUE TITLE
Implement equals method for UserAttributes.

### ISSUE THREAD

**Issue by 540Grunkspin** [intercom/intercom-android#440]
So im testing my android code that are sending the actual intercom data to intercom. I want to make sure that it sends the correct UserAttributes object to identify.

So i try to see if i can get email from the user attributes object but that one is private.

I then think maybe i can construct an expected UserAttrbiutes object and check for equals but the equals implementation uses the default implementation  (reference equality).

So my suggestion is implement the equals method to check the fields. I would do this my self but i cant find where the actual code is located.

**Comment by ronocod** [comment]
Hi, we've added implementations for `equals()`, `hashCode()` and `toString()` in 4.1.1.

**Comment by 540Grunkspin** [comment]
Awesome! Thanks for the reply!
