### ISSUE TITLE
Notification channel names are not language specific

### ISSUE THREAD

**Issue by welsinga** [intercom/intercom-android#444]
## Version info
  - Intercom for Android version: 4.1.2
  - Android OS version: Android 8.0
  - Android Device: Pixel

## Expected behaviour
When I change the language of my device, the notification channel names should change to language specific values

## Actual behaviour
Notification channel names are still:
- "Chat replies"
- "New chats"
- "Actions"

**Comment by DaleCantwell** [comment]
Thanks for reporting this @welsinga. I'll have these added to our next localization batch.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
