### ISSUE TITLE
Member browser attribute being set on register via SDK

### ISSUE THREAD

**Issue by MacMcIrish** [intercom/intercom-android#448]
## Version info
  - Intercom for Android version: 3.0.10
  - Android OS version: 8.1
  - Android Device: Pixel

## Expected behavior
On member register, the browser attribute for the member should not be set, as they are using the app directly.

## Actual behavior
On member register, the browser is being set to `Dalvik`.

**Comment by skylerwshaw** [comment]
Hey @MacMcIrish 👋, happy to look into this but it's going to require details from your Intercom app instance to troubleshoot. Can you open a conversation with the Intercom support team either by starting a conversation using the Intercom messenger from the Intercom dashboard, or emailing team@intercom.io? Feel free to mention my name to get forwarded over to me. Thanks!

**Comment by skylerwshaw** [comment]
@MacMcIrish I've not seen any conversations in Intercom on this topic. In addition I'm unable to see any attributes with `/dalvik/i` being set for browser attributes. If you can provide more information I'd be happy to dig further. Cheers!
