### ISSUE TITLE
Using access token in Android client

### ISSUE THREAD

**Issue by CsabaZz** [intercom/intercom-android#450]
The Intercom website tells me that I should use access token instead of API key, but it does not tell me how.

**Comment by DaleCantwell** [comment]
Hi @CsabaZz, the access token change does not currently apply to the mobile messengers and there are currently no plans to change this. You are fine to continue using your Android API key.
Thanks,
-Dale

**Comment by CsabaZz** [comment]
I'm just asking because I see the following error in the system log: "**_Intercom realtime: No realtime endpoints present so we can't connect_**". I did the SDK installation by the manual, so I have no idea what is wrong. I don't see the events logged by **Intercom.client().logEvent(pageTitle)**.

**Comment by DaleCantwell** [comment]
@CsabaZz it might be worth going to [Intercom](www.intercom.com) and writing into us via the messenger as we will likely need to ask some details about your integration. Essentially that error is most likely a result of not having a successful integration. 
Somewhere in your code you will have called Intercom.initalize with your API key and app ID and then at some point Intercom.client().registerUnidentifiedUser or Intercom.client().registerIdentifiedUser. Some part of that setup is likely incorrect. Is there any other errors showing up in logcat?

**Comment by CsabaZz** [comment]
@DaleCantwell thank you, I'm asked you on the Messenger and copy-pasted the code parts (the initialisation method and the log event method).
