### ISSUE TITLE
How to exclude io.intercom.okhttp3.**,  io.intercom.retrofit2.**, io.intercom.com.bumptech.glide.**

### ISSUE THREAD

**Issue by b95505017** [intercom/intercom-android#455]
I found that your SDK size is huge. One of the reason is that your SDK include some of well-known libraries and change their package into your AAR.

Is it possible to provide a lite version of SDK which pull okhttp3, retrofit2 and glide from public repository to minimize the app size, because lots of app are using these libraries too.

Thanks!

**Comment by DaleCantwell** [comment]
Hi there,
We provide a transitive version of our library for cases like this. We have docs here:
https://docs.intercom.com/using-transitive-dependencies-with-intercom-for-android

Our dependancy graph is here:
https://github.com/intercom/intercom-android#intercom-sdk-base

Thanks for getting in touch
Dale
