### ISSUE TITLE
Follow up to #408

### ISSUE THREAD

**Issue by popin-peter** [intercom/intercom-android#457]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.1.6 (non-transitive)
  - Android OS version: 7.1.2
  - Android Device: Nexus 6

## Expected behavior
After calling `setBottomPadding` with a non zero value, the message popup stays in the same place even after repeated messages.

## Actual behavior
Exactly as described in #408 the message indicator rises up over the screen. Upon each new message received, the indicator rises higher.

Note this is the first time I am using the library, so I am not using the `dimen` value at all, nor has it ever been used in the application.

## Steps to reproduce
 1. Initialize Intercom, calling `setBottomPadding` with some non zero value such as 16
 2. Receive multiple messages when the app is in the foreground, but the Intercom message window is not open. 
 3. 

## Logs
No valid logs related to Intercom noticed.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
