### ISSUE TITLE
Intercom crash: attach base context crash

### ISSUE THREAD

**Issue by cnsimbe** [intercom/intercom-android#458]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.1.2
  - Android OS version: 7.0
  - Android Device: HWVTR P10, Moto G (5th Gen) (cedric)

## Expected behavior
Shouldn't crash
## Actual behavior
It crashes
## Steps to reproduce
 1. Install intercom on a cordova android project
 2. After the app starts, set up intercom and open the intercom chat list
 3. It crashes at some point. Also trying closing the app and opening it again. It might also crash then.

## Logs
![intercom-crash](https://user-images.githubusercontent.com/7696004/34123509-a7c89502-e3e4-11e7-9f2d-7111fd60c9b7.png)

**Comment by ronocod** [comment]
This sounds like it may be fixed in version 5.0.1 of the Cordova plugin. If it's still broken on that version can you open an issue on the `intercom-cordova` repo so we can track it?
