### ISSUE TITLE
Do not suggest range versions

### ISSUE THREAD

**Issue by LouisCAD** [intercom/intercom-android#459]
Hi, using range versions (as seen in the [Installation part of the REAMDE](https://github.com/intercom/intercom-android#installation) and on docs on your website) leads to non reproducible builds, which are bad when you need to verify why a version of your app had an issue. You should move to explicit versions. I'll submit a PR for this, but remember the website still has this at the moment.

**Comment by ronocod** [comment]
This is a deliberate choice. Many developers (like us) put a lot of thought and care into their dependency management and know the downsides of using range versions. We would encourage them to use a specific version, and keep it updated as we release new versions. 

However a lot of people don't want to spend time manually updating dependency versions, and just want to use the latest compatible version available in each build.

By recommending a range version as the default, we believe we provide a good experience for developers who want to always have the latest features without manual updates to their Gradle files. Developers who would rather specify a version and keep it up-to-date are free to do that instead.

**Comment by LouisCAD** [comment]
Instead of encouraging non-reproductible builds, you can just link the bintray page where we can watch the repo for email updates.
Also, Android Studio has warnings in the gradle file when libraries are updated.

**Comment by ronocod** [comment]
We're going to continue with the existing documentation for the reasons I've mentioned above. Developers are free to use whatever tools they want to keep track of updates if they want to manually manage their dependency versions.
