### ISSUE TITLE
GET_ACCOUNTS permission is unnecessary for api level >= 14

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#46]
Hi guys, it's me again! :stuck_out_tongue_winking_eye: 

In your AndroidManifest you are getting a permission called "GET_ACCOUNTS" this is mandatory if your minSdk is prior to 3.0 but we are using minSdk 15 so we are embedding a permission that is not needed

More info:
http://stackoverflow.com/questions/18444227/get-accounts-permission-while-using-gcm-why-is-this-needed

So it's better that the final user of the SDK includes this permission or not :)

**Comment by Harkin** [comment]
Feedback is always welcome! :) 

That's interesting, thanks for letting us know. We're keen to keep permissions to a minimum so that's a good suggestion. I've moved this to our internal issues but this change probably won't make it into the next release

**Comment by Harkin** [comment]
We removed this permission entirely in 0.9.4, turns out it's not necessary for any sdk version

**Comment by PaNaVTEC** [comment]
Good news, thanks :+1:
