### ISSUE TITLE
On touch of In-app message type note not working properly

### ISSUE THREAD

**Issue by TapanM** [intercom/intercom-android#464]
## Version info
  - Intercom for Android version: 4.1.6
  - Android OS version: 6.0.1
  - Android Device: Oneplus2

## Expected behavior
  - On touch of In-app message type note should open image full screen

## Actual behavior
  - On touch of In-app message type note disappear in app and not able to access app. Going to background foreground showing image full screen

## Steps to reproduce
 1. Create manual message with channel In-app message with message type note
 2. Add any image in message and set it live
 3. Once you receive In-app message in application, click on image and you will see message dialog disappear and you can't use your app.
4. Click home button of mobile and again open app you will see image is full screen now

**Comment by pranavvij** [comment]
Intercom for Android version: 4.1.6
Android OS version: 7.1.1
Android Device : One plus 5

Hi @TapanM ,
Suffering from a similar behaviour .There seems to be an overlay after the image only template provided by intercom which freezes the screen and restores the screen only on back press.

Please look into this issue @aidanlynch , @bobjflong .

Thank you

**Comment by nick0lay** [comment]
Same issue.
Intercom for Android version: 4.1.6
Android OS version: 8.1.0
Android Device : Nexus 5x

**Comment by ronocod** [comment]
Fixed in 4.1.8.
