### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method isAnnotated()Z

### ISSUE THREAD

**Issue by matheussouza97** [intercom/intercom-android#465]
Hello i'm making a binding library for Xamarin Android and everything is ok, i have a just one problem. I have a bug on send a picture on conversation.

## Version info
  - Intercom for Android version: 4.1.6
  - Android OS version: Android 6.0.1
  - Android Device: SM-J510MN

## Expected behavior
Send image.
## Actual behavior
Crash.
## Steps to reproduce
 1. Send image on conversation

## Logs

  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: No virtual method isAnnotated()Z in class Lcom/intercom/input/gallery/GalleryImage; or its super classes (declaration of 'com.intercom.input.gallery.GalleryImage' appears in /data/app/[package]/base.apk)
	at io.intercom.android.sdk.api.Api$2$1.onResponse(Api.java:485)
	at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by ronocod** [comment]
The Intercom SDK depends on version 1.3.4 of our `android-composer` library, but it looks like your app is using version 2.0.0 for some reason. Have you got an entry in your Gradle files anywhere that looks like this?
`compile 'com.intercom:android-composer:2.0.0'`
There must be something in your Gradle configuration that is making it use 2.0.0 instead of the correct 1.3.4 version.

**Comment by matheussouza97** [comment]
My application is using android-composer-1.2.2.aar from here (https://github.com/intercom/intercom-android/tree/master/aar). IDE Xamarin does not use Gadle technology, we work with .aar and .jar

**Comment by ronocod** [comment]
Ah sorry, those artifacts are out of date. I'll update them now.

**Comment by matheussouza97** [comment]
Thank you very much.

**Comment by ronocod** [comment]
The correct AAR files for the composer are there now.
