### ISSUE TITLE
Push Notification Icon (FCM)

### ISSUE THREAD

**Issue by matheussouza97** [intercom/intercom-android#467]
Hi, I have a old issue. My notifications from intercom not appear the user avatar.

## Version info
  - Intercom for Android version: 4.1.6
  - Android OS version: 7.0
  - Android Device: Moto G4 Plus

## Expected behavior
https://prntscr.com/hvli3j

## Actual behavior
https://prntscr.com/hvli3l

## Steps to reproduce
 1. Send push notification

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
