### ISSUE TITLE
Android 7.1.1 not registering User Enabled Push correctly

### ISSUE THREAD

**Issue by mutablestudio** [intercom/intercom-android#468]
## Version info
  - Intercom for Android version:
            'io.intercom.android:intercom-sdk-base:4.+',
            'io.intercom.android:intercom-sdk-fcm:4.+'
  - Android OS version: 7.1.1
  - Android Device: Moto G 5S

## Expected behavior
- IntercomPushClient method sendTokenToIntercom() should set user field `User Enabled Push` to `true` 

## Actual behavior
- User Enabled Push is set to `Unknown` and should be set to `true`

## Steps to reproduce
 1. from an Android 7.1.1 device, run this code from your Application class and use your device's notification token:

`public class ThisApplication extends Application {

    private final IntercomPushClient intercomPushClient = new IntercomPushClient();

    @Override public void onCreate() {
        super.onCreate();
        Intercom.initialize(this,
                Utils.fromBase64(Utils.INTERCOM_TEST_API_KEY),
                Utils.fromBase64(Utils.INTERCOM_TEST_APP_ID));
        Registration registration = Registration.create().withUserId("HELLOjdkskkdkdkkdk");
        Intercom.client().registerIdentifiedUser(registration);
        intercomPushClient.sendTokenToIntercom(this, YOUR_TOKEN_HERE);
    }

}`

 2. Check user with id "HELLOjdkskkdkdkkdk" in Intercom dashboard
 3. User details field User Enabled Push is set to "Unknown"

We have other users registering from Android 8 & 8.1 and this field is correctly set to `true`.

Also we are having an issue across all Android versions where Push Notifs come into the app via FCM method `onMessageReceived()` but if the app is backgrounded, the Notifications do not show in the Notification tray or on lock screen. Will open a separate issue for that.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
