### ISSUE TITLE
Android FCM push notifications not showing on lock screen or Notif tray

### ISSUE THREAD

**Issue by mutablestudio** [intercom/intercom-android#469]
## Version info
  - Intercom for Android version:
            'io.intercom.android:intercom-sdk-base:4.+',
            'io.intercom.android:intercom-sdk-fcm:4.+'
  - Android OS version: 7.1.1, 8.0 or 8.1
  - Android Device: Moto G 5S, Android Pixel, Nexus 6P

## Expected behavior
- Push Notifications should show on lock screen or in Notification tray when app is backgrounded

## Actual behavior
- Push Notifs come into the app via FCM method `onMessageReceived()` but if the app is backgrounded, the Notifications do not show in the Notification tray or on lock screen

## Steps to reproduce
1. For example, use this code

`
public class ThisApplication extends Application {

    private final IntercomPushClient intercomPushClient = new IntercomPushClient();

    @Override public void onCreate() {
        super.onCreate();
        Intercom.initialize(this,
                Utils.fromBase64(Utils.INTERCOM_TEST_API_KEY),
                Utils.fromBase64(Utils.INTERCOM_TEST_APP_ID));
        Registration registration = Registration.create().withUserId("HELLOjdkskkdkdkkdk");
        Intercom.client().registerIdentifiedUser(registration);
        intercomPushClient.sendTokenToIntercom(this, YOUR_TOKEN_HERE);
    }

}
`

2. Background the Android app on the device
3. Create an Intercom manual message of type Push/Android and send to user "HELLOjdkskkdkdkkdk"
4. Notification does not appear on device, but is received by FCM listener `onMessageReceived()`

We tested all our devices by calling the google api endpoint `https://fcm.googleapis.com/fcm/send` and all the Notifications arrive and display on lock screen/notification tray.

**Comment by cpytel** [comment]
I am having this same issue as described here. @mutablestudio did you ever resolve it?

I've also contacted Intercom support.

**Comment by mutablestudio** [comment]
@cpytel yes, in our case we were missing a line of code that is documented, but not in such a way that indicates it is required for push notifs to show. in your FirebaseMessagingService class make sure you have the `handlePush` method (on iOS Intercom says to remove this to manually handle a push so we did not include it on Android, but it seems to be what triggers push notifs to show when app is backgrounded)

`if (intercomPushClient.isIntercomPush(message)) {
            intercomPushClient.handlePush(getApplication(), message);
...
  }
`

If you already have this implemented then I would suggest double checking your google server key and testing push notifs outside of Intercom with the FCM endpoint.

**Comment by cpytel** [comment]
Thanks, this helped me track down the problem, which it turns out was that in AndroidManifest.xml we had both the Firebase messaging service and the Intercom intent service registered. This was causing the notifications to not be handled/sent to the tray properly.

**Comment by laurmurclar** [comment]
Looks like you both resolved the issue so I'm going to close this 😊
