### ISSUE TITLE
Error while building project with Intercom

### ISSUE THREAD

**Issue by karthyks** [intercom/intercom-android#474]
Does anyone else get this error while building?

##Logs

/home/.gradle/caches/transforms-1/files-1.1/intercom-sdk-base-4.1.6.aar/1d2e26d3d854ebbd0534ff43a10f8a2f/res/values/values.xml
Error:error: style attribute '@android:attr/windowEnterAnimation' not found.
Error:error: style attribute '@android:attr/windowExitAnimation' not found.

Suggestion:
I dont think there should be an '@' before android.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
