### ISSUE TITLE
No resource found error in version 4.1.6

### ISSUE THREAD

**Issue by karthyks** [intercom/intercom-android#476]
Error:(1) No resource found that matches the given name (at 'background' with value '@drawable/intercom_composer_circular_ripple').

**Comment by skylerwshaw** [comment]
This issue does not follow our required template. 

In particular, by providing a naked error without any context, you’re not giving the development team working on this repo the ability to determine the cause.

Please open an issue that provides the error, stack trace, frequency of occurrence, number of unique users affected, reproduction instructions, and any supplemental information you may have.
