### ISSUE TITLE
Overload view inside chat screen on intercome

### ISSUE THREAD

**Issue by songtoanht** [intercom/intercom-android#478]
https://drive.google.com/file/d/1eEPtW1uBdL-v-nBPtWwDVrYE2vdNadU7/view?usp=sharing

## Version info
  - Intercom for Android version: 4.+

## Expected behavior 
don't overload text

## Steps to reproduce
 1. click icon intercome
 2. click back
 3. click left corner

## Logs

**Comment by ronocod** [comment]
What device and OS version was this?

**Comment by songtoanht** [comment]
I checked on two devices. The bug occurs on both devices. 

1. Samsung S4 - 5.0.1
2. Galaxy J2 Prime - 6.0.1

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
