### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by MuhammedRefaat** [intercom/intercom-android#479]
## Version info
  - Intercom for Android version: 4.+
  - Android OS version: 7.0.0
  - Android Device: Samsung S2 tablet

## Expected behavior
implementing intercom gradle library with GCM

## Actual behavior
getting "Unable to merge dex" compilation error while trying to compile the library.

## Steps to reproduce
 1. add "compile 'io.intercom.android:intercom-sdk:4.+'" to gradle file
 2. try to build the app 
 3. build fails

## Logs

`
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex`

**Comment by ronocod** [comment]
This looks like it's probably a problem specific to your build, not a bug in our SDK. Can you try the suggestions mentioned here?: https://stackoverflow.com/questions/46267621/unable-to-merge-dex

**Comment by MuhammedRefaat** [comment]
Thank you for your response,
Actually I believe the problem is from your side, because I'm already not facing it till trying to include your GCM library, and my guess is that you are are somehow implementing GCM services into your library, and then my app find that there are two libraries for GCM with a different versions.

May be if I know the GCM services library version you are using that would be great.

**Comment by ronocod** [comment]
We use version 11.4.2 of the GCM library, we'll be upgrading to 11.8.0 this week.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
