### ISSUE TITLE
intercom openes with default blue color scheme 

### ISSUE THREAD

**Issue by mariuspena** [intercom/intercom-android#480]
## Version info
  - Intercom for Android version: 4+
  - Android OS version: 8.1.0
  - Android Device:

## Expected behavior
Intercom should open with the color scheme I have chosen in the admin every time (even the first time)

## Actual behavior
when I open intercom for the 1st time, the color scheme is the blue default one
next times I open intercom it opens correctly with the color scheme I have chosen in the admin

## Steps to reproduce
 1. open freshly installed app
 2. open intercom and observe color scheme
 3. open intercom again and observe color scheme (correct one) 

## Logs

**Comment by mariuspena** [comment]
the problem is that the call for the config is not over when I click on the button and open intercom messenger
and there is no way to know when that async call is over..

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
