### ISSUE TITLE
Service_unavailable

### ISSUE THREAD

**Issue by Almaral-Engineering** [intercom/intercom-android#485]
## Version info
  - Intercom for Android version: 4.1.7
  - Android OS version: 5.1
  - Android Device: Htc Desire

## Expected behavior

Send and receive intercom messages from the device 

## Actual behavior

The screen says "Something went wrong, couldn´t load  your conversations"

## Steps to reproduce
 1. Open intercom activity

## Logs

E/Intercom: Api call failed: {
                                                           "type": "error.list",
                                                           "errors": [
                                                               {
                                                                   "code": "service_unavailable",
                                                                   "message": "Sorry, the API service is temporarily unavailable"
                                                               }
                                                           ]
                                                       }

**Comment by lolsheeplol** [comment]
The API was having some problems it seems.  You can check for yourself at https://status.intercom.com/.

**Comment by bboyle18** [comment]
Thanks for reporting this. Our app is currently having availability issues. Please monitor http://status.intercom.com for updates
