### ISSUE TITLE
Error:Failed to resolve: :intercomsdk-0.8.5:

### ISSUE THREAD

**Issue by shailendraborse** [intercom/intercom-android#49]
I am getting always this error while syncing the gradle
Error:Failed to resolve: :intercomsdk-0.8.5:

**Comment by danikula** [comment]
```
repositories {
    maven { url 'http://dl.bintray.com/intercom/intercom-maven' }
}

dependencies {
    compile(name: 'intercomsdk-0.8.5', ext: 'aar')
}
```

Works well for me.

**Comment by DaleCantwell** [comment]
I would happy to work with you on the integration in gradle. We also have version 0.9.1 out which I would recommend updating to.
