### ISSUE TITLE
Company Update example on docs site is wrong

### ISSUE THREAD

**Issue by creativepsyco** [intercom/intercom-android#51]
Hi,

The company update example for a user model given in the [docs](http://docs.intercom.io/install-on-your-mobile-product/using-the-android-sdk) is using an `Object` instead of an `ArrayList`. However the `companies` field in a `User` model is an Array and not an object[[1]](https://doc.intercom.io/api/#companies-and--users). This might lead to some confusion. It will cause error with a 500 HTTP status code.

The corrected example should be like this
```java
Map<String, Object> userMap = new HashMap<>(); 
Map<String, Object> companyData = new HashMap<>(); 
companyData.put("name", "My Company"); 
companyData.put("id", "abcd1234"); 
List<Object> companies = new ArrayList<>();
companies.add(companyData);
userMap.put("companies", companies); 
Intercom.client().updateUser(userMap);
```

**Comment by DaleCantwell** [comment]
Thank you for reporting that issue. I have updated the docs now, we will also add some client side code to validate the data provided to us contains the desired object types.
