### ISSUE TITLE
Problem with multiple users of the application on the same device

### ISSUE THREAD

**Issue by yonatancups** [intercom/intercom-android#52]
Using the beta the user currently using my application is sent with:

    Intercom.client().registerIdentifiedUser..

which should then either update or create the user in the dashboard. However, I ran into problems sending in-app messages through the dashboard to the users who have been created in this way. Specifically, if I send an in-app message to the first user created then it will pop up in the application no matter which user is logged into the application on the device at the time. Furthermore, only in-app messages sent to the first user will be delivered at all on the device, while in-app messages sent through the dashboard to users that were later registered appear as "not seen yet" in the "conversations" panel and never pop up on the device.

**Comment by Harkin** [comment]
Hi @yonatancups 

This seems odd, are you calling `Intercom.client().reset()` between registering users?

**Comment by yonatancups** [comment]
@Harkin 

Yes, you were correct - I needed to call reset between users. I've added it and it sorts out the issue - many thanks
