### ISSUE TITLE
GET_TASKS permission?

### ISSUE THREAD

**Issue by felipebari** [intercom/intercom-android#53]
Users of my app are questioning me why a task list needs access to their running apps. It's a very legitimate question since the permission does sound suspicious to a user. 

But the permission is actually being requested by the Intercom SDK (not directly by my app). So, What exactly is it being used for, so I can reassure users?

**Comment by Harkin** [comment]
Hi @felipebari,

Are you using a 0.8.x version of the SDK? We removed the `GET_TASKS` permission in the 0.9.0 release. I'd recommend updating to [0.9.3](https://github.com/intercom/intercom-android/tree/master)! It's a lot more stable.

What we were using it for in the 0.8.x versions was a fallback in managing the notification preview's visibility. We were able to drop it entirely in 0.9.0

**Comment by felipebari** [comment]
Thank you @Harkin, I upgraded to 0.9.4 today. So far so good!
