### ISSUE TITLE
hamburger button behaviour is confusing

### ISSUE THREAD

**Issue by mderazon** [intercom/intercom-android#54]
When inside a conversation, there are two buttons in the actionbar - `X` and hamburger 
`X` closes the conversation
Hamburger goes back to the conversation list

This is confusing and non Androidish behaviour.
The hamburger button is actually a back button (it functions the same as the physical back button) and should probably be `<` caret button.

**Comment by shekmantang** [comment]
Hi @mderazon , Shek here from the product team.
Thanks for your suggestion, we're certainly aware of this confusion and are planning to change that in the future releases.
