### ISSUE TITLE
Impossible to revote conversation

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#56]
Steps:
1. Open some conversation with a replay of supports
2. Put like or dislike
3. Try to revote
-> The user can't revote in Conversation 

`version 0.9.3`

**Comment by DaleCantwell** [comment]
Hi @danikula 
Thanks for your feedback. Not being able to revote is intentional. We will add it for consideration, but for now you can't change your response to a LWR across web, ios or android.
Thanks,
Dale
