### ISSUE TITLE
Incorrect status of the first message in conversation to be sent

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#57]
Steps
1. Open page of creation new conversation
2. Send some message
-> Status of message is not changed and remains "Sending...". And now user can't send more messages
->> After reopening this conversation status of this message is correct

`version 0.9.3`

**Comment by DaleCantwell** [comment]
Hi @danikula 
We can't reproduce this one. Is there any other step to get into the always Sending state?
Thanks,
Dale

**Comment by danikula** [comment]
@DaleCantwell I haven't problem with reproducing. Every time I start a new conversation a first post has infinite status `Sending...` 
![screenshot](https://dl.dropboxusercontent.com/u/15506779/persistent/screenshots/intercom-issue-57.png)

**Comment by DaleCantwell** [comment]
@danikula thank you for the details, we have located the cause of the problem and will let you know as soon as the updated version is available.

**Comment by danikula** [comment]
@DaleCantwell Is it issue fixed in 0.9.5?

**Comment by DaleCantwell** [comment]
@danikula the issue is resolved in 0.9.5 let us know if your still seeing it in the new version
