### ISSUE TITLE
Incorrect conversation sorting

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#58]
Reproduced time to time. Version 0.9.3.
![incorrect sorting by date](http://content.screencast.com/users/vageqweqweqwe/folders/Snagit/media/6dbc61f4-eb8f-4ea0-8b2a-b750f752f128/04.07.2015-01.15.png)

**Comment by Harkin** [comment]
Hi,

Dale followed up on this though Intercom, I believe the issue was unreproducible. If you can reliably reproduce this please let me know
