### ISSUE TITLE
Useless keyboard

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#59]
Version 0.9.3.

Steps:
1. Open page of creating new conversation
2. Tap on input field 
3. Tap on some text on page

As result useless keyboard is shown. Any tap on it does nothing.

**Comment by DaleCantwell** [comment]
Thanks for reporting this issue @danikula, we have logged it internally and we will let you know when we have a solution.

**Comment by DaleCantwell** [comment]
Fixed in version 0.9.6
