### ISSUE TITLE
Offline created post duplicates 

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#60]
Steps:
1. Open page of creation conversation
2. Disconnect the Internet connection.
3. Send any message.
4. Connect the Internet connection.
5. Type few times on screen of created conversation while a connection in the connection process

After reconnecting message dispatched multiple times depending on how many times a user taped on screen
`version 0.9.3`

**Comment by DaleCantwell** [comment]
@danikula thanks for reporting this issue. The fix for this issue will be included in v0.9.4
