### ISSUE TITLE
java.lang.NoClassDefFoundError: io.intercom.android.sdk.R$color‏ Error

### ISSUE THREAD

**Issue by aku-sama** [intercom/intercom-android#61]
Hello, i try to use Intercom Android SDK in our project (intellij idea 14.0.2, API 21) 

To connect use instruction for Eclipse from this link http://docs.intercom.io/Install-on-your-mobile-product/install-the-intercom-android-sdk

When i'm adding intercom-sdk like library project and adding all dependency for it, project build operation fail with error

Error:Android Dex: [intercom-sdk-0.9.3] Unable to execute DX
Error:Android Dex: [intercom-sdk-0.9.3] com.android.dex.DexException: Multiple dex files define Lio/intercom/android/sdk/BuildConfig;

The problem is that classes.jar contains BuildConfig file with package name "io.intercom.android.sdk" and the whole module is also generating BuildConfig file with the same package name as declared in Manifest. I changed the package name in intercom AndroidManifest.xml from io.intercom.android.sdk to io.intercom.android.sdk.lib and project build success. (http://stackoverflow.com/questions/23236790/multiple-dex-files-define-lcom-amazon-ags-buildconfig-when-using-gamecirclesdk-i)

But now, when i'm try run Intercom.initialize(this, Config.INTERCOM_API_KEY_DEBUG, Config.INTERCOM_APP_ID_DEBUG); 

application crash with error:

java.lang.NoClassDefFoundError: io.intercom.android.sdk.R$color‏

I'm tried copy all resources from intercom-sdk to my project, but error not fixed.
Can you help me with my problem?

**Comment by juancarlo1220** [comment]
I have a crash in a production build:
I have used 0.9.3 version.
![error](https://cloud.githubusercontent.com/assets/10573973/7062385/022cb384-de9d-11e4-9d43-4171bd7cd886.png)

**Comment by DaleCantwell** [comment]
Hi @aku-sama @juancarlo1220 
We can only support Android Studio and Eclipse developers at the moment. Intellij developers using the gradle build system should be able to use the Android Studio integration guide. 
We will continue to help with the integration through our conversation in Intercom.

**Comment by danpe** [comment]
:+1:  I'm also having this on Android Studio with Intercom 1.3.1
