### ISSUE TITLE
Do we have checkForUnreadMessages API

### ISSUE THREAD

**Issue by ericfong** [intercom/intercom-android#62]
Hi

Do we have a method to check the number of unread message in the API ?

**Comment by adamkmccarthy** [comment]
Hi @ericfong. Apologies, this isn't something we expose through the SDK at this time. The SDK has it's own polling control built in that fetches new messages on a regular basis if you aren't on a plan with realtime. If you are on a plan with realtime, then the realtime connection takes over instead.
