### ISSUE TITLE
Application crashes on initialize method.  java.lang.NoClassDefFoundError: io.intercom.android.sdk.api.MainThreadBus

### ISSUE THREAD

**Issue by manishkungwani** [intercom/intercom-android#63]
Hi,
I'm getting an exception on v0.9.3 and v0.9.5 when Intercom is being initialized (on simulator and a device as well):

04-18 09:40:43.170    1061-1061/com.iam.nearer.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: io.intercom.android.sdk.api.MainThreadBus
            at io.intercom.android.sdk.Bridge.<init>(Bridge.java:35)
            at io.intercom.android.sdk.Bridge.init(Bridge.java:43)
            at io.intercom.android.sdk.Intercom.<init>(Intercom.java:112)
            at io.intercom.android.sdk.Intercom.initialize(Intercom.java:139)
            at com.iam.nearer.app.NearerApplication.onCreate(NearerApplication.java:52)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Harkin** [comment]
@manishkungwani That's really weird.

Could I get some details from you on if you're using eclipse or android studio and how you're including the SDK?

Could you open the jar/aar and see if you can find the MainThreadBus.class in there? If you're using an aar you can use something like Unarchiver (mac) or 7zip (windows) to open it, there will be a classes.jar in there that you'll need to open too, all the classes should be in there.

**Comment by manishkungwani** [comment]
Really weird.
I'm using AS + Gradle.
I'm using the aar as a module.

![image](https://cloud.githubusercontent.com/assets/673367/7218001/3df36734-e670-11e4-8fac-73d021ca6c21.png)

I saw it is there in the aar file.
When I started the integration, I was on support v4 21.0.0 and then moved to support v4 22.0.0 since it was a dependency.

For your reference, here is the build.gradle:

	apply plugin: 'com.android.application'
	apply plugin: 'android-apt'
	def AAVersion = '3.2'

	buildscript {
		repositories {
			mavenCentral()
		}

		dependencies {
			classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
		}
	}

	apt {
		arguments {
			androidManifestFile variant.outputs[0].processResources.manifestFile
			resourcePackageName 'com.iam.nearer.app'
		}
	}

	android {
		compileSdkVersion 21
		buildToolsVersion "21.1.2"

		defaultConfig {
			applicationId "com.iam.nearer.app"
			minSdkVersion 14
			targetSdkVersion 21
			versionCode 1
			versionName "1.0"
		}
		buildTypes {
			release {
				minifyEnabled false
				proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			}
		}
	}

	dependencies {
		compile fileTree(include: ['*.jar'], dir: 'libs')
		apt "org.androidannotations:androidannotations:$AAVersion"
		compile "org.androidannotations:androidannotations-api:$AAVersion"
		compile 'de.greenrobot:eventbus:2.4.0'
		compile 'com.android.support:appcompat-v7:21.0.3'
		compile 'com.edmodo:cropper:1.0.1'
		compile 'com.mobsandgeeks:android-saripaar:1.0.3'
		compile 'cn.pedant.sweetalert:library:1.3'
		compile 'com.github.navasmdc:MaterialDesign:1.+@aar'
		compile 'com.nineoldandroids:library:2.4.0'
		compile 'it.sephiroth.android.library.horizontallistview:hlistview:1.2.2'
		compile 'com.jpardogo.materialtabstrip:library:1.0.9'
		compile 'com.koushikdutta.ion:ion:2.+'
		compile 'com.facebook.android:facebook-android-sdk:3.21.1'
		compile 'com.google.android.gms:play-services:6.5.87'
		compile 'org.apmem.tools:layouts:1.8@aar'
		compile 'com.github.traex.rippleeffect:library:1.2.4'
		compile 'com.snappydb:snappydb-lib:0.5.0'
		compile 'com.esotericsoftware.kryo:kryo:2.24.0'
		compile 'com.rockerhieu.emojicon:library:1.0'
		compile 'com.android.support:support-v4:22.0.+'
		compile 'com.facebook.fresco:fresco:0.1.0+'
		compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
		compile project(':intercom-sdk-0.9.5')
	}

**Comment by manishkungwani** [comment]
I hadn't included all the dependencies mentioned in the documentation.
The steps on the intercom website didn't mention them.
I would request you guys to make it a bit more descriptive. On the site, its written that you need to add the aar as a module and add the dependencies in gradle as well.
Thanks
Sorry for the trouble.

**Comment by Harkin** [comment]
Glad you got it sorted, and thanks for pointing that out with the docs. We'll be iterating on them as we get feedback to make them awesome :)
