### ISSUE TITLE
0.9.6 dependency

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#68]
I have problem with using 0.9.6 by gradle dependency. It complains:
```
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find io.intercom.android:intercom-sdk:0.9.6.
     Searched in the following locations:
...
```
My `build.gradle`: 
```
repositories {
    maven { url 'http://dl.bintray.com/intercom/intercom-maven' }
}

compile 'io.intercom.android:intercom-sdk:0.9.6@aar'
```
Bintray [doesn't contain binaries](http://dl.bintray.com/intercom/intercom-maven/io/intercom/android/intercom-sdk/0.9.6/).

**Comment by Harkin** [comment]
Looking into this now

**Comment by Harkin** [comment]
Sorry about this, I uploaded it again and tested the download, it's working now. The file path must not have been correct the first time.

**Comment by danikula** [comment]
@Harkin :+1: Thanks
