### ISSUE TITLE
intercom.intercomsdk.models.App.setPlan crash

### ISSUE THREAD

**Issue by appmagnetics** [intercom/intercom-android#72]
Hi,

starting from today we experience heavy crash in our app, coming from Intercom SDK. Already 1500 crashes.  We use intercomsdk-0.8.3, integrated directly as .aar file

java.lang.NullPointerException
       at intercom.intercomsdk.models.App.setPlan(App.java:122)
       at intercom.intercomsdk.models.App.store(App.java:161)
       at intercom.intercomsdk.models.Config.store(Config.java:41)
       at intercom.intercomsdk.api.Engine$1.onResponse(Engine.java:189)
       at intercom.intercomsdk.api.Engine$1.onResponse(Engine.java:165)
       at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5731)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Harkin** [comment]
Hi, I'm looking into what might be causing that now. 

0.8.3 is a very old version and we'd recommend updating to the latest version ASAP. There have been substantial changes and improvements to stability

**Comment by appmagnetics** [comment]
Thanks for a very fast reply. Is 0.9.7 Beta good to go?

**Comment by danikula** [comment]
I've updated to 0.9.7. But 40% of my users are still use old version with intercom 0.8.3. Please, fix it ASAP.

**Comment by danikula** [comment]
I suppose your API returns unexpected result and sdk crashes. This issue happen only today. More than 200 chashes from my users!

**Comment by Harkin** [comment]
Yeah this is an issue with something in our API, we've tracked down where it is now and we're working on a fix

**Comment by Harkin** [comment]
The fix will be live in the next ~10 minutes

**Comment by appmagnetics** [comment]
I assume some troubles by deployment on your side ;)   we still getting crashes coming over Crashlytics - 1846 now

**Comment by Harkin** [comment]
A few issues, yeah :( The fix has been live with a few minutes now, could you @appmagnetics confirm that you've stopped seeing new crashes?

**Comment by appmagnetics** [comment]
I confirm - last 5 minutes not increase in crash counter. Fantastic problem solving! You guys rock!

**Comment by Harkin** [comment]
:+1:

**Comment by appmagnetics** [comment]
I have noticed increase of about 100 new crashes since my report, unfortunately ;(  
Will continue to observe now...

**Comment by appmagnetics** [comment]
Unfortunately crashes are still coming ... May be not at that rate as previously, but they still do ...

**Comment by Harkin** [comment]
Okay looking into this again now. Is it the same crash, same stack trace as above?

**Comment by appmagnetics** [comment]
Yes, same one

**Comment by appmagnetics** [comment]
Any news on this one? We continue to receive crashes. The issue is that we tried to do a hotfix by integrating your latest library but that has made the app go over Dex limit and there is no quick way to make the app multidex. So we have no ready hot-fix version now.

**Comment by Harkin** [comment]
We're investigating from our side but we essentially reverted the change that caused this so there isn't any obvious reason why you'd still be receiving crash reports.

Is the volume slowing or continuing at a steady rate? We're thinking it might be that these crashes aren't new. Most crash tracking libraries report a crash the _next_ time someone opens an app, eg it crashes at 5pm but user X doesn't open the app again until 7pm so the crash report isn't sent until 7pm.

**Comment by appmagnetics** [comment]
That may be true - we have customers scattered around the world, so they might be waking up one after another and switching on their phones. ;)  I will continue to observe it today.

**Comment by Harkin** [comment]
:+1: I'll leave this open until we're happy that it isn't still happening

**Comment by Harkin** [comment]
@appmagnetics just following up on this, have you been getting any more crash reports?

**Comment by appmagnetics** [comment]
We have received a couple more but the floold has been definitely stopped. Let's consider the issue again. We have finally prepared new version with your latest lib and will release it now.

**Comment by Harkin** [comment]
Good to hear, I'm happy to call this closed with the expectation that you'll receive the odd crash report for this over the next few days as people open the app again
