### ISSUE TITLE
Crash from intercom.

### ISSUE THREAD

**Issue by faizalzakaria** [intercom/intercom-android#77]
We are facing this crash. 

What could it be ? 
```
com.newrelic.agent.android.instrumentation.GsonInstrumentation.toJson (GsonInstrumentation.java:28)
io.intercom.android.sdk.identity.AppConfig.update (AppConfig.java:91)
io.intercom.android.sdk.identity.AppIdentity.updateAppConfig (AppIdentity.java:56)
io.intercom.android.sdk.identity.IdentityStore.setAppConfig (IdentityStore.java:55)
io.intercom.android.sdk.api.CallbackHolder.updateAppConfig (CallbackHolder.java:113)
io.intercom.android.sdk.api.CallbackHolder.updateBaseResponseObjects (CallbackHolder.java:105)
io.intercom.android.sdk.api.CallbackHolder.access$000 (CallbackHolder.java:28)
io.intercom.android.sdk.api.CallbackHolder$2.success (CallbackHolder.java:44)
io.intercom.android.sdk.api.CallbackHolder$2.success (CallbackHolder.java:41)
retrofit.CallbackRunnable$1.run (CallbackRunnable.java:45)
```

It works perfect without intercom, but crash when we add intercom. Not compatible with newrelic library ?

BR.

**Comment by Harkin** [comment]
What's the cause cause of the crash (null pointer exception, illegal argument exception etc.)?

**Comment by Harkin** [comment]
@faizalzakaria any updates here?

**Comment by faizalzakaria** [comment]
Hi @Harkin , 

I didn't had a chance to look at this yet. Will get back to you as soon as I've new info.

BR.

**Comment by Harkin** [comment]
I followed up with Cyrille through Intercom about this crash. New Relic bundle an older version of GSON in their library. It is namespaced in the latest version, are you using that version? The sdk is using the version of GSON that New Relic is supplying, no idea why if it's namespaced. Maybe it isn't in the New Relic library you're using?

**Comment by anshul90** [comment]
Hey Harkin, can you please give me Constants class of intercom GCM which has a sharedPreferences `Constants.GCM_DETAILS` ? I'm getting error in it. And tell me I need any receiver or anything else in Manifest.xml ??

**Comment by Harkin** [comment]
@anshul90 it sounds like whatever trouble you're experiencing isn't related to this issue, could you make a new issue outlining what you're doing, what's going wrong, any logs or stacktraces you have?

**Comment by anshul90** [comment]
@Harkin I'm using intercom sdk 1.0.0. I've initialized everything and now I'm integrated code for GCM in my app from http://docs.intercom.io/Install-on-your-mobile-product/using-google-cloud-messaging-gcm-with-intercom-for-android#-step-6-register-for-intercom-gcm- I have written each code from here but I don't know what to write in place of `DummyApplication`. Can you please give me a right way?

**Comment by anshul90** [comment]
@Harkin Now i'm using your code https://github.com/intercom/intercom-android/blob/master/samples/intercom-gcm-sample/gcmsample/src/main/java/io/intercom/gcmsample/MainActivity.java but I use `registerIdentifiedUser` in Login Class and using GCM code without TextViews in another class. There is no error or no crashing  but I'm not getting push notifications when my app isn't opened.

**Comment by Harkin** [comment]
@anshul90 I have created a new issue for you here https://github.com/intercom/intercom-android/issues/87, lets take the discussion to there :+1:
