### ISSUE TITLE
Unable to start receiver io.intercom.android.sdk.gcm.GcmBroadcastReceiver

### ISSUE THREAD

**Issue by Mathbl** [intercom/intercom-android#83]
Hey there. Happened to me twice today:
```
                         E  Process: com.myapp.android, PID: 7896
                         E  java.lang.RuntimeException: Unable to start receiver io.intercom.android.sdk.gcm.GcmBroadcastReceiver: java.lang.SecurityException: Neither user 10501 nor current process has android.permission.WAKE_LOCK.
                         E      at android.app.ActivityThread.handleReceiver(ActivityThread.java:2616)
                         E      at android.app.ActivityThread.access$1700(ActivityThread.java:151)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5254)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                         E  Caused by: java.lang.SecurityException: Neither user 10501 nor current process has android.permission.WAKE_LOCK.
                         E      at android.os.Parcel.readException(Parcel.java:1546)
                         E      at android.os.Parcel.readException(Parcel.java:1499)
                         E      at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:337)
                         E      at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:974)
                         E      at android.os.PowerManager$WakeLock.acquire(PowerManager.java:958)
                         E      at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:98)
                         E      at io.intercom.android.sdk.gcm.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:16)
                         E      at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609)
                         E      ... 9 more

```
When the user sign in, I do this 
```
Intercom.client().setSecureMode(session.getIntercomUserHash(), session.getUser().getId());
Intercom.client().registerIdentifiedUser(new Registration().withUserId(session.getUser().getId()));
```

I followed the tutorial from http://docs.intercom.io/Install-on-your-mobile-product/installing-intercom-for-android#how-should-i-use-intercom-in-my-app. I use gradle. Do I need to add any permissions to my manifest?

Any idea? If you need more details just ask and I'll try to help. Thanks!

**Comment by Harkin** [comment]
Hi @Mathbl 

Are you trying to use GCM through Intercom in your app (i.e. calling Intercom.client().setupGCM at some point) or have you at some point registered the device for GCM notifications? We've seen this happen if you receive a GCM notification and doesn't have the `<uses-permission android:name="android.permission.WAKE_LOCK" />` permission in your manifest

**Comment by Mathbl** [comment]
No, I don't use GCM.

**Comment by Harkin** [comment]
What version of the library are you using and does it crash directly after registration or at some later point in the app?

Also are you seeing this on a single device or multiple devices?

**Comment by Mathbl** [comment]
```
    compile ('io.intercom.android:intercom-sdk:1.0.2@aar') {
        transitive = true
    }
```

I'm not able to reproduce the crash on-demand...so that's pretty hard to pin point what is the exact issue. The two/three times it happened, i'm pretty sure it was when I hit the Sign in button (that does the registration call). If it happens again i'll try to see if I can provide more info.

**Comment by Harkin** [comment]
I've been trying to reproduce this and the only way I've managed to do so is by removing the wake lock permission from an app that has GCM already set up and then receiving a push notification. Does that sound anything like your situation @Mathbl? 

What device are you experiencing this with?

**Comment by Mathbl** [comment]
I got the crash twice on a Nexus 5 and a Lenovo Yoga 2 10. I don't have any permission related to intercom in my manifest.

Like I said, I'm not using GCM at all in my app. So that's strange. I guess i'll have to put the wake lock permission, but that doesn't sound right to put a permission I don't need.

**Comment by Harkin** [comment]
I'm a bit lost as to how this is happening. The crash occurs in our broadcast receiver which is called by the system whenever a GCM notification arrives for your app. In order for us to send a GCM notification to your devices, we have to have a GCM registration id for each device. We don't generate that in the library, it's only given to us by calling `Intercom.client().setupGCM(params...)`. 

The GCM registration id is unique per app install, so if you uninstall and reinstall the app on your device you shouldn't receive any new GCM notifications and so shouldn't ever touch the broadcast receiver.

**Comment by Harkin** [comment]
I've managed to reproduce this issue once. I can't make it happen unfortunately so it's hard to tell if my fix is actually fixing it or I'm just not encountering it. @Mathbl have you found any pattern to when it happens?

**Comment by Mathbl** [comment]
No pattern for me neither. I didn't work on the app for the past 4-5 days, but if I'm able to get the crash again, i'll tell you for sure.

**Comment by Harkin** [comment]
@Mathbl v1.0.4 should fix this issue, but I never found out why it was happening. It seems like the system would sometimes ping our gcm broadcast receiver when there wasn't a gcm message received, we expected that if it got pinged you had gcm set up etc. Let me know if you experience anything like this again
