### ISSUE TITLE
GCM setup

### ISSUE THREAD

**Issue by Harkin** [intercom/intercom-android#87]
Following on from https://github.com/intercom/intercom-android/issues/77 I've updated the GCM docs to be more clear about what certain parameters are, the short of it is that those are all constants and you need to supply your own values for them. Specifically where you mention `DummyApplication` you need to supply your GCM sender id. 

GCM shouldn't require any input from your users to work. If you download our [GCM sample app](https://github.com/intercom/intercom-android/tree/master/samples/intercom-gcm-sample) and enter your own details into the SampleApplication and MainActivity classes where prompted to, do you receive any push notifications from conversations?

**Comment by anshul90** [comment]
Thanks. Everything is fixed now. But when I'm updating avatar I get this format on intercom web like {&quot;type&quot;:&quot;avatar&quot;,&quot;image_url&quot;:&quot;https:\/\/fnfsvvi-jug.in\/images\/95\/thumbnail_1432291713.jpg&quot;}

**Comment by Harkin** [comment]
How are you trying to update the avatar?

**Comment by anshul90** [comment]
My Code looks like 
`Map userMap = new HashMap<String, String>();
		jsonAvatar = new JSONObject();
		try {
			jsonAvatar.put("type", "avatar");
			jsonAvatar.put("image_url", icon_candidate);
		} catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Map<String, String> customAttributes = new HashMap<String, String>();
		customAttributes.put("Name", name_candidate);
		customAttributes.put("Phone_Number", phone_no);
		customAttributes.put("email", email_candidate);
		customAttributes.put("avatar", jsonAvatar.toString());
		userMap.put("custom_attributes", customAttributes);
		Intercom.client().updateUser(userMap);`

**Comment by Harkin** [comment]
The avatar isn't something you can update through the library. Here's a list of all the fields you can update [link](https://doc.intercom.io/api/#create-or-update-user)

**Comment by anshul90** [comment]
Avatar is also in the list.

**Comment by Harkin** [comment]
It's returned in a response if you query for a user, but it's read only. It isn't in the list of attributes that you can update

**Comment by anshul90** [comment]
Ok thanks. One of intercom's member also told me this on Chat. I'm not gonna update it anymore. thanks  for your support @Harkin

**Comment by Harkin** [comment]
:+1:

**Comment by msodq** [comment]
I have question about Using Google Cloud Messaging (GCM) with Intercom for Android. I am following this tutorial http://docs.intercom.io/Install-on-your-mobile-product/using-google-cloud-messaging-gcm-with-intercom-for-android and https://github.com/intercom/intercom-android/tree/master/samples/intercom-gcm-sample but the notification not showing on notification bar
