### ISSUE TITLE
Crash and report java.lang.NoClassDefFoundError: io.intercom.android.sdk.api.MainThreadBus

### ISSUE THREAD

**Issue by whmsysu** [intercom/intercom-android#90]
I use gradle and maven to intergrate intercomm. When I run the app, the app crash and report:java.lang.NoClassDefFoundError: io.intercom.android.sdk.api.MainThreadBus

My build gradle file's content:
buildscript {

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'
    }
}

allprojects {
    repositories {
        mavenCentral()

    }
    repositories {

        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"

        }
    }
    repositories {
        maven {
            url 'https://dl.bintray.com/intercom/intercom-maven'
        }
    }

}

apply plugin: 'android'

android {
    compileSdkVersion 21
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.foodfanselect.android"
        minSdkVersion 14
        targetSdkVersion 21
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    compile 'io.intercom.android:intercom-sdk:1.0.4@aar'

    compile 'com.google.android.gms:play-services:+'
    compile 'com.stripe:stripe-android:+'
    compile 'com.mixpanel.android:mixpanel-android:+'
    compile 'uk.co.chrisjenx:calligraphy:+'
    compile 'com.facebook.fresco:fresco:+'
    compile 'com.loopj.android:android-async-http:+'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3'
}

**Comment by harkin** [comment]
You aren't including any of the dependencies required for Intercom to work. You can either include the dependencies transitively from Intercom like 
```
compile ('io.intercom.android:intercom-sdk:1.0.4@aar') {
    transitive true
}
```

or by including the ones you need from our listed dependencies [here](https://github.com/intercom/intercom-android#remote-dependencies)

**Comment by whmsysu** [comment]
Change the code as you mention above.
But.....
Error:Execution failed for task ':foodfanSelect:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
