### ISSUE TITLE
Can not integrate the intercom android plugin

### ISSUE THREAD

**Issue by whmsysu** [intercom/intercom-android#91]
Have a error in building stage:
Error:Execution failed for task ':foodfanSelect:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

My build gradle script is:
buildscript {

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'
    }
}

allprojects {
    repositories {
        mavenCentral()

    }
    repositories {

        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"

        }
    }
    repositories {
        maven {
            url 'https://dl.bintray.com/intercom/intercom-maven'
        }
    }

}

apply plugin: 'android'

android {
    compileSdkVersion 21
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.foodfanselect.android"
        minSdkVersion 14
        targetSdkVersion 21
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    compile ('io.intercom.android:intercom-sdk:1.0.4@aar') {
        transitive true
    }

    compile 'com.google.android.gms:play-services:+'
    compile 'com.stripe:stripe-android:+'
    compile 'com.mixpanel.android:mixpanel-android:+'
    compile 'uk.co.chrisjenx:calligraphy:+'
    compile 'com.facebook.fresco:fresco:+'
    compile 'com.loopj.android:android-async-http:+'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3'
}

**Comment by harkin** [comment]
Do you have a full log of the build process I could look at?

**Comment by whmsysu** [comment]
Information:Gradle tasks [:foodfanSelect:assembleDebug]
:foodfanSelect:preBuild UP-TO-DATE
:foodfanSelect:preDebugBuild UP-TO-DATE
:foodfanSelect:compileDebugNdk UP-TO-DATE
:foodfanSelect:checkDebugManifest
:foodfanSelect:preReleaseBuild UP-TO-DATE
:foodfanSelect:prepareComAndroidSupportAppcompatV72211Library UP-TO-DATE
:foodfanSelect:prepareComAndroidSupportMediarouterV72200Library UP-TO-DATE
:foodfanSelect:prepareComAndroidSupportSupportV42220Library UP-TO-DATE
:foodfanSelect:prepareComFacebookFrescoDrawee051Library UP-TO-DATE
:foodfanSelect:prepareComFacebookFrescoFbcore051Library UP-TO-DATE
:foodfanSelect:prepareComFacebookFrescoFresco051Library UP-TO-DATE
:foodfanSelect:prepareComFacebookFrescoImagepipeline051Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServices750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesAds750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesAnalytics750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesAppindexing750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesAppinvite750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesAppstate750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesBase750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesCast750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesDrive750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesFitness750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesGames750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesGcm750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesIdentity750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesLocation750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesMaps750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesNearby750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesPanorama750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesPlus750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesSafetynet750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesWallet750Library UP-TO-DATE
:foodfanSelect:prepareComGoogleAndroidGmsPlayServicesWearable750Library UP-TO-DATE
:foodfanSelect:prepareComMixpanelAndroidMixpanelAndroid460RC1Library UP-TO-DATE
:foodfanSelect:prepareComSquareupLeakcanaryLeakcanaryAndroid13Library UP-TO-DATE
:foodfanSelect:prepareComStripeStripeAndroid100Library UP-TO-DATE
:foodfanSelect:prepareIoIntercomAndroidIntercomSdk104Library UP-TO-DATE
:foodfanSelect:prepareUkCoChrisjenxCalligraphy210Library UP-TO-DATE
:foodfanSelect:prepareDebugDependencies
:foodfanSelect:compileDebugAidl UP-TO-DATE
:foodfanSelect:compileDebugRenderscript UP-TO-DATE
:foodfanSelect:generateDebugBuildConfig UP-TO-DATE
:foodfanSelect:generateDebugAssets UP-TO-DATE
:foodfanSelect:mergeDebugAssets UP-TO-DATE
:foodfanSelect:generateDebugResValues UP-TO-DATE
:foodfanSelect:generateDebugResources UP-TO-DATE
:foodfanSelect:mergeDebugResources UP-TO-DATE
:foodfanSelect:processDebugManifest UP-TO-DATE
:foodfanSelect:processDebugResources UP-TO-DATE
:foodfanSelect:generateDebugSources UP-TO-DATE
:foodfanSelect:compileDebugJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/haominwu/Developer/Select_Git/Android/FoodfanSelect/FoodfanSelect/src/main/java/com/foodfan/entertain/PartnerMainAdapter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:foodfanSelect:preDexDebug
:foodfanSelect:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':foodfanSelect:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 20.781 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by harkin** [comment]
Looks like you have more than 65k methods in your app now. Google have a good guide on how to build an app that exceeds the dex limit [here](https://developer.android.com/tools/building/multidex.html)
