### ISSUE TITLE
Intercom-Android﹕ ERROR: It appears your app is not on a plan that allows message composing As a fallback we are calling displayConversationsList()  

### ISSUE THREAD

**Issue by whmsysu** [intercom/intercom-android#92]
When trying to call the conversation list, it shows an error. Could anyone tell me what's the meaning of this error? I finished the install part and registration part, but fail to load the conversation list.

**Comment by sirvon** [comment]
what plan is need to allow composing?
how was this resolved?

**Comment by harkin** [comment]
@sirvon you need to be on either our [Support or Support Pro plan](https://www.intercom.io/customer-support) to allow composing

**Comment by sirvon** [comment]
@harkin reponses for intercomio are faster using github issues than actually using intercomio on the intercom website....dont't know what that says :)
but thanks!

**Comment by harkin** [comment]
@sirvon generally you will get a faster response through Intercom. Most of our devs are in GMT and that's when github issues are updated. Our customer success team has a lot more timezone coverage. Thanks for letting me know about your message through Intercom, I've raised it internally here that you were waiting
