### ISSUE TITLE
Failed to resolve io.intercom.android:intercom-sdk:1.0.4@aar

### ISSUE THREAD

**Issue by defcon89** [intercom/intercom-android#93]
Hi,

Failed to resolve io.intercom.android:intercom-sdk:1.0.4@aar

**Comment by harkin** [comment]
Are you including the maven url in your repositories?
eg
```
repositories {
    maven {
        url 'https://dl.bintray.com/intercom/intercom-maven'
    }
}
```

**Comment by defcon89** [comment]
Yes, i've included maven url in repositories.

**Comment by harkin** [comment]
Hm, that's the normal reason why it can't resolve the dependency. Are you behind a proxy or something that might be interfering with the http request? Can you open the download link directly in a browser [link](https://dl.bintray.com/intercom/intercom-maven/io/intercom/android/intercom-sdk/1.0.4/)?

Would you mind sharing your apps build.gradle file?

**Comment by defcon89** [comment]
No proxy and i can download directly from your link.

I can't share build.grade because is a private project.

I tried to clean project and the result is:

Could not resolve io.intercom.android:intercom-sdk:1.0.4.
     Required by:
         ?:app:unspecified
      > Could not GET 'https://jcenter.bintray.com/io/intercom/android/intercom-sdk/1.0.4/intercom-sdk-1.0.4.pom'.
         > peer not authenticated
      > Could not GET 'https://dl.bintray.com/intercom/intercom-maven/io/intercom/android/intercom-sdk/1.0.4/intercom-sdk-1.0.4.pom'.
         > peer not authenticated
      > Could not GET 'https://jcenter.bintray.com/io/intercom/android/intercom-sdk/1.0.4/intercom-sdk-1.0.4.pom'.
         > peer not authenticated
      > Could not GET 'https://dl.bintray.com/intercom/intercom-maven/io/intercom/android/intercom-sdk/1.0.4/intercom-sdk-1.0.4.pom'.
         > peer not authenticated

**Comment by harkin** [comment]
Looks like an ssl problem. Could you switch the maven url to `http://dl.bintray.com/intercom/intercom-maven` and try again?

**Comment by defcon89** [comment]
ok, now it works! thanks a lot.

**Comment by harkin** [comment]
Happy to help :)
