### ISSUE TITLE
Intermittent ANR in GcmIntentService and PreviewService?

### ISSUE THREAD

**Issue by dzeikei** [intercom/intercom-android#96]
This started happening, possibly after the latest update.
I haven't really looked into it yet but it happens quite regularly and the user gets ANR dialogs.

```
E/ActivityManager﹕ ANR in com.xxx.xxx, time=124868987
    PID: 9264
    Reason: executing service com.xxx.xxx/io.intercom.android.sdk.gcm.GcmIntentService
```

**Comment by dzeikei** [comment]
Just got another one for `PreviewService`
```
Reason: executing service com.xxx.xxx/io.intercom.android.sdk.preview.PreviewService
```

**Comment by dzeikei** [comment]
Also happens when the app is in the background.
I am running `Intercom.initialize()` in the Application class, so it probably happens when the app starts up in the background due to geofence, GCM, etc.

**Comment by DaleCantwell** [comment]
@dzeikei are there any more details in the ANR or have you seen any stack trace for a crash? Send on anything you spot. I haven't been able to reproduce the issue yet so if you spot any reproducible steps let me know.

**Comment by dzeikei** [comment]
I'll follow up if I can reproduce it consistently.

**Comment by dzeikei** [comment]
I think this is unrelated to intercom.io but with Butterknife

**Comment by dzeikei** [comment]
Actually it was intercom but hasn't happened for a while after updates, will see if it ever happens again.

**Comment by santosh07401** [comment]
Got this anr again  in io.intercom.android.sdk.preview.PreviewService

**Comment by harkin** [comment]
@santosh07401 what version of the library are you seeing this on, what devices are you seeing this on, how frequent is it?

**Comment by harkin** [comment]
We're refactored and rewritten large parts of this for 3.0.0. If there's still an issue please let us know with some information
