### ISSUE TITLE
Notification not showing when Using GCM with Intercom

### ISSUE THREAD

**Issue by msodq** [intercom/intercom-android#97]
I have problem with Using Google Cloud Messaging (GCM) with Intercom for Android. I am following this tutorial http://docs.intercom.io/Install-on-your-mobile-product/using-google-cloud-messaging-gcm-with-intercom-for-android and https://github.com/intercom/intercom-android/tree/master/samples/intercom-gcm-sample but the notification not showing on notification bar.

Any idea or solution?

**Comment by DaleCantwell** [comment]
Hi @msodq, in the gcm sample app after putting in your apps credentials can you see any errors in the logs? It is worth noting that the host app must be closed or backgrounded to receive notifications in the top bar.

**Comment by msodq** [comment]
Hi @DaleCantwell , i don't see any errors.

**Comment by DaleCantwell** [comment]
Could you debug the setUpPush method? You should see some value for regId. Then when sendRegistrationIdToBackend is called it should hit Intercom.client().setupGCM(regId, R.drawable.ic_launcher);
If you have received no error by then we should do a deeper dive into a specific conversation. If we do need to do a detailed investigation it may be worth taking it to a private conversation as we may need to discuss api keys. Contact me at dale.cantwell@intercom.mail.intercom.io

**Comment by DaleCantwell** [comment]
@msodq I'm going to close out this issue for now. Reopen the issue if you are still encountering it on our current version.
Thanks,
Dale
